### ISSUE TITLE
Video player doesn't respect the dimension of the block on playing

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#1037]
Noticed that the video player does't respect the dimension of the block when playing a video.
Once you tap play, the video overlay can getter bigger and also clip out of the actual screen.

https://cloudup.com/c1j8E6q0S-N

Steps to repro:
- Tested in wp-android v1.6 integration branch (https://github.com/wordpress-mobile/WordPress-Android/pull/9941)
- Add a video block
- Record a video with portrait orientation from your device
- Wait until the upload finishes, and then tap on Play icon
- The video player doesn't "stay" in the block, but can grow outside the dimension of the block.

I also noticed that if your rotate the device the video player is completely black and the dimensions are off.

**Tested on Nexus 5X, Android 7.1**

Noticed also a crash, that I'm going to report on wp-android repo.

**Comment by koke** [comment]
Interesting, on iOS we always play fullscreen. It seems there's a [resize](https://github.com/react-native-community/react-native-video#resizemode) prop that could help here. cc @pinarol

**Comment by daniloercoli** [comment]
Updated the issue details with the device details I used for testing, since I noticed the player is working fine on Android 9. I guess it's a problem on the Android platform version 7.X, since I noticed slowness and weird behavior on that version of platform on the native media player.

**Comment by pinarol** [comment]
We can tackle with `resizeMode` but since it has `none` value by default, I wouldn't expect it would have an effect on this. This looks like a react-native-video bug to me. 

How about for Android we use what Aztec editor was using to display video? We can pass the play message to the parent app and let parent app play it the old way. @daniloercoli wdyt? In this case we'd be setting `controls=false` on RN side so user wouldn't see the play/stop etc buttons on the video, we'd put our own play button like we did on iOS.

On the other hand on iOS I think we can continue having react-native-video playback. 

If there's a way to fix it on `react-native-video` level it'd even be better but not sure if that'd even be possible or worth the effort.

**Comment by daniloercoli** [comment]
As mentioned [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1068#pullrequestreview-246120886) i was not able to reproduce the problem now, testing on Android 7.1 / Nexus 5X, the video does respect the dimensions of the block, and it's played "inside" the block boundaries.

**Comment by koke** [comment]
👏 Wonderful, let's close this one then, unless it reappears
