### ISSUE TITLE
[Video] Refine Video block scrim/play-pause button styling

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#1178]
A couple of design details didn't quite get settled during our initial review – let's refine these things in order to add the desired level of polish :)

## Current

![IMG_4013](https://user-images.githubusercontent.com/1200432/60130387-bd496500-975c-11e9-94ef-b001074a2082.jpeg)

## Proposed

![Video with Caption - Focused](https://user-images.githubusercontent.com/1200432/60131021-0352f880-975e-11e9-81d5-634aef4b2270.jpg)

- [x] Make video scrim/overlay `black` (`#000000`) at 40% alpha
- [x] Change `play`/`pause` icons to use either Gridicons (`gridicons-play`/`gridicons-pause`) or Material (`play_circle_filled`/`pause_circle_filled`) variations. Icon should be `white` (`#FFFFFF`) at 70% alpha
- [x] Change placeholder text color to match other placeholder text color (`$gray` IIRC?) https://github.com/wordpress-mobile/gutenberg-mobile/issues/996
- [ ] When the video is focused, outline makes block size jump. Can we consider applying an outer shadow so the block doesn't move when selected?

**Comment by maxme** [comment]
I update the overlay, the icon and the icon size (size used: `64` as it corresponds to your proposition). This is what I get currently:

![Screenshot_1564044472](https://user-images.githubusercontent.com/40213/61860141-c3507400-aec9-11e9-9d05-e200b734ce17.png)


I tried to change the elevation on Android to add an outer shadow, it doesn't work and I think the issue comes from the view hierarchy (parent containers hide the elevation visual effect). I wonder how it's done for images, do we have any visual clue the image block is focused?

**Comment by SergioEstevao** [comment]
> When the video is focused, outline makes block size jump. Can we consider applying an outer shadow so the block doesn't move when selected?

@iamthomasbishop from my tests on the current version of the app (15.0) I only see the issue above, can you elaborate a bit more what do you want to change?

**Comment by SiobhyB** [comment]
It seems all but one of the tasks attached to this issue have been complete, with the last task not being clear and there having been no clarification in three and a half years. As there doesn't appear to be anything actionable here, I'll go ahead to close, but feel free to re-open if I'm missing something!
