### ISSUE TITLE
Content loss in Group block

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1206]
Steps to reproduce:

1. On the web, create a new post
2. Add a Group block and hit its "+" button to add a paragraph block to it
3. Type anything in the paragraph, example: "inside the group"
4. Place the mouse beneath the group, click and type anything. That will create a paragraph outside the Group.
5. Publish the post and open it in the mobile WP app. The post will be opened in the mobile Gutenberg editor.
6. Switch to html mode via the 3-dots menu
7. Notice that the text content in the group is not visible 💥
8. Even not switching to html in step 7 but doing any change to the post and publish (example: move blocks around and publish) ends up in the group content to be gone 💥

**Comment by Tug** [comment]
Most likely will be fixed by https://github.com/WordPress/gutenberg/pull/14443

**Comment by mcsf** [comment]
A heads-up that https://github.com/WordPress/gutenberg/pull/14443 was just merged.

**Comment by jjchrisdiehl** [comment]
> A heads-up that [WordPress/gutenberg#14443](https://github.com/WordPress/gutenberg/pull/14443) was just merged.

Not sure if this was resolved yet @mcsf , recent test:

Tested on WordPress.com Premium

Before
![image](https://user-images.githubusercontent.com/16580129/60904382-f72c6800-a240-11e9-8136-bc9c4aef569a.png)

After editing the post on Mobile app:
![image](https://user-images.githubusercontent.com/16580129/60904399-fc89b280-a240-11e9-9995-004877f716b6.png)

**Comment by Tug** [comment]
@jjchrisdiehl Did you test on the production app or locally? I believe this fix should land soon-ish in the next app updates.

**Comment by designsimply** [comment]
@jjchrisdiehl the 12.9 beta is now available for testing on Google Play if you have requested to join the Beta program at https://play.google.com/apps/testing/org.wordpress.android 

Please see https://make.wordpress.org/mobile/2019/07/16/call-for-testing-wordpress-for-android-12-9/ for more details if you're interested! ❤️

I tested with WPAndroid alpha-181 (12.9 alpha) on Pixel 3 Android 9 and found that the group block is unsupported in the app (currently the expected behavior) and that no content inside the the group block is lost after making edits to the post with the mobile app which is the issue this PR mentions is fixed. 👍

<img src="https://user-images.githubusercontent.com/1119271/61497807-14b6ab80-a97e-11e9-96fe-9c1d665c55f4.png" width="200" alt="Screenshot_20190718-165722"> <img src="https://user-images.githubusercontent.com/1119271/61497817-1ed8aa00-a97e-11e9-9700-8b3f08c0f1b6.png" width="200" alt="Screenshot_20190718-165727">

<sup>Tested with WPAndroid alpha-181 (12.9 alpha) on Pixel 3 Android 9.</sup>
