### ISSUE TITLE
Reduce warnings count produced by the RN toolchain on iOS

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1222]
@diegoreymendez reached out mentioning that apparently, the toolchain produces a big amount of "ignorable" warnings while building, making it hard to notice the ones that really matter. Let's investigate and see if we can mitigate this.

One suggestion by Diego is to use https://github.com/mattijsf/react-native-inhibit-warnings.

**Comment by diegoreymendez** [comment]
The problem I noticed is that WPiOS is showing several warnings coming from the React library that we can do nothing about (and that don't belong in the scope of WPiOS).  This is mostly harmless by itself, but it can make it difficult to spot if we're adding unnecessary warnings to our own codebase.

I've tried fixing this from our WPiOS repo by inhibiting all warnings in may ways, but for some reason this isn't working.  The proposed package above could be a quick solution, if it does what it advertises, so I was wondering if we could give it a shot.

**Comment by etoledom** [comment]
Thanks for the suggestion @diegoreymendez !

I don't think that this library will work for us, since it modifies the .xcodeproj inside node_modules, but we install them via cocoapods.

Maybe there's something similar we can do with out podspec.json script to add those build config directly to the generated podspects.

As another alternative I think we can force some build setting to some dependencies directly in out WPiOS Podfile.

@jtreanor Might also have some other ideas?

From some time already I haven't seen warnings from React Native. I probably did something locally but I can't remember 🤔

<img width="384" alt="Screen Shot 2019-07-12 at 5 56 49 PM" src="https://user-images.githubusercontent.com/9772967/61141721-784c5f00-a4ce-11e9-853a-3372682c7bdf.png">

**Comment by jtreanor** [comment]
I think the situation should improve with 1.7.0. I fixed some issues in https://github.com/facebook/react-native/pull/24467.

I haven't looked recently but can have a look next week.

**Comment by mchowning** [comment]
At planning, we decided to timebox working on this to 1 day.

**Comment by hypest** [comment]
👋 @diegoreymendez , is this still an issue for WPiOS?

**Comment by diegoreymendez** [comment]
No more warnings, sir!  Closing.
