### ISSUE TITLE
Add content alignment options in paragraphs

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1266]
Add support for left/center/right alignment of text in paragraph blocks.

Aztec-Android supports it, Aztec-iOS doesn't.

**Comment by mchowning** [comment]
👋  @iamthomasbishop! Any thoughts on the UI for this? I assume we'll use the relevant dash-icons (i.e., [TinyMCE alignleft](https://developer.wordpress.org/resource/dashicons/#editor-alignleft))? Where do you think these buttons should go? They seem less important than the bold, emphasis, etc. controls for paragraphs, so I was thinking to the right of those with the scrolling toolbar for the time being (that is where they were on Android-Aztec). I don't think we're going to be at the too-many-icons point yet with the paragraph block with this approach, but we may be there once we add alignment to the heading block.

**Comment by iamthomasbishop** [comment]
We can probably just utilize the same icons that Core is using, if that's easy enough. I believe they're either using Dashicons or Material.

In terms of placement, we should probably replicate where Core has them – right after the block type selector. Something like this (first example is collapsed(**) example, which we don't yet have. Second example is closer to what we have now):

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1200432/62886894-b1603500-bd01-11e9-8780-5e84173987b6.png">

** I'd love to start collapsing groups of similar controls (like alignment) but that would probably be a separate project.

You mentioned Heading block – this is how I'd imagine that would look like w/ collapsed section for alignment:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1200432/62887048-13209f00-bd02-11e9-8013-39deed0e26e5.png">

**Comment by koke** [comment]
A user in 2299402-zen is asking about the option to justify text in the app editor.

**Comment by hypest** [comment]
Related #575

**Comment by mchowning** [comment]
2 PRs related to addressing this:
1. https://github.com/wordpress-mobile/AztecEditor-Android/pull/851
2. https://github.com/WordPress/gutenberg/pull/17577

**Comment by mchowning** [comment]
Hey @iamthomasbishop ! I was working on this and doing some RTL checking when I noticed that because the toolbar is reversed for RTL languages, the alignment buttons end up with a very (imo) unintuitive order such that the button for right alignment is the _left_-most of the alignment, and the button for left alignment is the _right_-most of the alignment buttons. 

![image](https://user-images.githubusercontent.com/4656348/67519426-da436580-f674-11e9-97c7-20c1a3846a93.png)

Assuming we do want the toolbar reversed for RTL languages, it seems like we should double-reverse the alignment buttons so that right alignment remains the right-most alignment button. WDYT.

**Comment by mchowning** [comment]
>Assuming we do want the toolbar reversed for RTL languages, it seems like we should double-reverse the alignment buttons so that right alignment remains the right-most alignment button. WDYT?

Or maybe it's not worth bothering since [we want](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1266#issuecomment-520533258) to move the alignment buttons to a dropdown pretty soon.

**Comment by koke** [comment]
I noticed something similar in #1461 and it seems it's not addressed on the web either (https://github.com/WordPress/gutenberg/issues/17922 https://github.com/WordPress/gutenberg/issues/8674 and likely more).

**Comment by iamthomasbishop** [comment]
This is an interesting one. I don't have RTL capabilities set up at the moment, and I won't be able to dig in today. My first question is "what are we doing on Aztec?" because I think @etoledom did some RTL work on Aztec a while back so that would be worth considering. Another thing we should do is reference what other apps like Google Docs, Notion, etc. do in RTL cases – might be some clues there.

My suggestion would be to find a quick solution, and if there isn't one then let's focus on bringing the dropdowns into the mix. Although something tells me we're going to have to figure out the order of those buttons as well, so maybe worth the investigation regardless 😄

**Comment by hypest** [comment]
Fixed with https://github.com/wordpress-mobile/gutenberg-mobile/pull/1489
