### ISSUE TITLE
Add Fullscreen Preview to Image Options 

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1286]
See Parent issue #1263 

The fullscreen preview should behave the same way the fullscreen preview does on Android in the Aztec Editor. 

Video of Image Preview in Android Aztec Editor
![preview-image-aztec-android](https://user-images.githubusercontent.com/1103838/62901416-87af0a00-bd11-11e9-9b20-eb20aae8d292.gif)

**Comment by cameronvoell** [comment]
Adding sketch of Fullscreen image preview menu UI from design feedback issue #1285 

![fullscreenimage-sketch](https://user-images.githubusercontent.com/1103838/63374052-e5f57180-c33d-11e9-9cbf-7110a8c5da89.png)

**Comment by mchowning** [comment]
:wave: @iamthomasbishop ! Was testing out this feature on Android and it's a really nice improvement. One thing I did notice is that currently if you have the caption selected, tapping on the image will open the full screen view. This makes it hard to get back to the image options (edit image, image alignment) because you have to unselect the image block entirely and then tap on the image. I think it would be better if tapping on the image when the caption was selected would just deselect the caption and bring the image edit options back. What do you think?

This is the current behavior I'm seeing where you cannot reselect the image once the caption is selected

![Kapture 2019-11-15 at 14 11 45](https://user-images.githubusercontent.com/4656348/68969044-081e5480-07b2-11ea-936f-334441441ee2.gif)

cc: @cameronvoell

**Comment by iamthomasbishop** [comment]
> One thing I did notice is that currently if you have the caption selected, tapping on the image will open the full screen view. This makes it hard to get back to the image options (edit image, image alignment) because you have to unselect the image block entirely and then tap on the image.

@mchowning I would expect tapping on the caption would remove focus/highlight from the image itself. So essentially if I have the caption focused, the first tap on the image itself shifts focus from the caption to the image (and thus adds highlight to the image), and the second tap shows the preview. Does that make sense?

**Comment by mchowning** [comment]
>So essentially if I have the caption focused, the first tap on the image itself should shift focus from the caption to the image (and thus adds highlight to the image), and the second tap should show the preview. Does that make sense?

That does make sense @iamthomasbishop . That is the behavior we have with respect to the format buttons on the bottom of the screen. The only issue is that the image is still behaving as if it is focused when the caption is focused with respect to the touch for full-screen preview behavior. As a result, tapping on the image when the caption is focused immediately opens the full screen preview. 

My suggestion is that we just make it so that tapping on the image when the caption is focused does not immediately open the full-screen preview but instead shifts focus from the caption to the image, and that tapping on the image a second time after the caption was in focus would open the full screen preview. It sounds like you're in favor of that change as well if I am reading your response correctly.

**Comment by iamthomasbishop** [comment]
Yup, that sounds exactly what I was trying to say, so I’m all good with that 😀

**Comment by cameronvoell** [comment]
@mchowning @iamthomasbishop I fixed the issues around caption focus in my PR's while implementing the iOS side. Code changes can be seen here: https://github.com/WordPress/gutenberg/pull/18618/commits

iOS build and GIF [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/12979) should show that selecting the caption removes the blue border, and once the caption is selected, we need to tap the image once to re-select it (which adds back the border), and a second time to launch the image preview. 

These changes will show up on Android as well once the PR's are merged.

**Comment by iamthomasbishop** [comment]
Looking good! Thanks for the fix!

**Comment by cameronvoell** [comment]
This issue was closed with a combination of PR's on Android and then on iOS:
`WordPress-Android`: https://github.com/wordpress-mobile/WordPress-Android/pull/10714
related `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1577
related `gutenberg`: https://github.com/WordPress/gutenberg/pull/18493

`WordPress-iOS`: https://github.com/wordpress-mobile/WordPress-iOS/pull/12979
related `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1597
related `gutenberg`: https://github.com/WordPress/gutenberg/pull/18618
