### ISSUE TITLE
Media & Text - Alignment

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1312]
Media & Text block text part is not aligning due to alignment options.

![mediaText-alignment](https://user-images.githubusercontent.com/5032900/63532124-a5028600-c512-11e9-8442-f233d0b86a8f.gif)

Since text is shorter than media in this case it is expected that it moves:

<img width="323" alt="Screen Shot 2019-08-22 at 19 28 36" src="https://user-images.githubusercontent.com/5032900/63532337-21956480-c513-11e9-92ed-f8a18fbd1b65.png">

Expected behaviour:

Text part is aligned similar to web:

![mediaText-alignment2](https://user-images.githubusercontent.com/5032900/63532163-b8155600-c512-11e9-8af4-30f57e2e7684.gif)

**Comment by designsimply** [comment]
This came up in 13.5 beta testing. Steps to reproduce:

1. Start a new post.
1. Add a Media & Text block with an image and some text.
1. Rotate the device to landscape to see the media and text side-by-side.
1. Try to use the different alignment options showing for the block.

**Result:** horizontal alignment options don't work in the Media & Text block. It's quite easy to spot on iPad. ([26s](https://cloudup.com/cuIpOnDSxIs))
<sup>Tested with WPiOS 13.5.0.0 beta (TestFlight) on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.1.2.</sup>

<img src="https://user-images.githubusercontent.com/1119271/67526997-27263c80-f673-11e9-92d6-7948209d373f.jpeg" width="270" alt="img_f4f26b8d60e1-1">

<sub>/hat tip @rachelmcr for the report (internal reference: p5T066-136-p2#comment-3658)</sub>

**Comment by koke** [comment]
I was investigating this on Friday, and what I know so far is that we have code in place to make this work, and that in a way it's doing what's expected. When you align some items vertically you'd expect to see something like this:

![Align_Items](https://user-images.githubusercontent.com/8739/67672329-fa766b80-f977-11e9-9e73-b1f273c6f42d.png)

However, there is something making the media container and the inner blocks 100% tall, so even if they're actually aligned, there's no visual difference:

![Align_Items_Tall](https://user-images.githubusercontent.com/8739/67672391-1d088480-f978-11e9-8197-f61984cddd40.png)

I started investigating the nested BlockList because I thought maybe that was problematic. Normally you want to specify a fixed height for a scroll view so its container view is bounded, and it can scroll when the content size is larger than the container:

![InnerBlocks](https://user-images.githubusercontent.com/8739/67672491-5a6d1200-f978-11e9-93f0-5f67631e964a.png)

However, I started a sample project with nested FlatList and it was working fine: https://snack.expo.io/@kokejb/scrollview-flexbox (I'd recommend testing on an iPad)

![IMG_DD591C3B3EE6-1](https://user-images.githubusercontent.com/8739/67672543-72dd2c80-f978-11e9-8fc5-385b3b1cf560.jpeg)
![IMG_D54E65CB7397-1](https://user-images.githubusercontent.com/8739/67672549-74a6f000-f978-11e9-9a38-e9b2b6e32140.jpeg)

I noticed that FlatList is [smart enough to detect when it's nested](https://github.com/facebook/react-native/blob/4c4948b6e83208cd517dd977b3462b1959505e1d/Libraries/Lists/VirtualizedList.js#L1205), and instead of adding a second ScrollView, it will use the context of the parent one. Our `KeyboardAwareFlatList` is not that smart and it adds another `ScrollView` to the hierarchy. I tried replacing it with a `FlatList` and it was still failing in a slightly different way.

Also, our media container is using `ImageBackground` and loading images from the network, which might be interfering with the flexbox calculations, as they re-render once they get the image sizes.

I started #1502, which doesn't have much yet, but the sample content is useful for testing all the cases.
