### ISSUE TITLE
Revisit settings controls API to improve cross platform

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1421]
On native, the controls (TextControl, ToggleControl, etc...) are based on BottomSheet Cells, that has some extra API needed to make them display and behave properly.

Let's revisit this API to make it closer to the Web.

cc @pinarol

**Comment by jbinda** [comment]
According to the discussion on `RangeControl` I have posted here some of the potential solutions. Please check [this comment](https://github.com/WordPress/gutenberg/pull/18036#discussion_r340456358)

**Comment by pinarol** [comment]
I think only `separatorType` is left to remove here, let me know if there's something else.

**Comment by dratwas** [comment]
I have checked the `separatorType` prop and I'm not sure if we should remove it tho. Unfortunately, there is no rule that says which control has which separator type.

I could move the prop to the `PanelBody` to decide what kind of separator should be rendered inside but it will not work in all cases. Check [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/button/edit.native.js#L242-L282), the last Control has a different separator type than others and we would need to do some hacks to make it works. [Here](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/latest-posts/edit.native.js#L138-L167) is another example where this approach will not work because the last cell has no separator.

In most cases, the`separatorType` is set to `none` which means there is no separator at all. So maybe we could remove the separator from the [Cell](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/mobile/bottom-sheet/cell.native.js) and add separator as a component next to `XXXControl`

Something like this
 ```jsx
<TextControl />
<Separator type={isCompatibleWithSettings ? 'fullWidth' : 'leftMargin'} />
<ToggleControl />
<Separator type={isCompatibleWithSettings ? 'fullWidth' : 'leftMargin'} />
<TextControl />
<Separator type={isCompatibleWithSettings ? 'none' : 'fullWidth'} />
```

cc @pinarol

**Comment by pinarol** [comment]
Closing since [the PR](https://github.com/WordPress/gutenberg/pull/21365) is merged.
