### ISSUE TITLE
[iOS] SafeArea is drawn behind block content

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#1424]
This gives the illusion that the SafeArea (space between the bottom toolbar and the edge of the screen on the iPhone X family (and 11 family) is transparent.

On this screenshot, the SafeArea is red, and the block content is noticeably drown on top of it.

![IMG_2A76FBACC416-1](https://user-images.githubusercontent.com/9772967/66457942-d2c76e00-ea71-11e9-8fa1-1a6ea0c4b618.jpeg)

**Comment by etoledom** [comment]
This regression happened on this PR: https://github.com/WordPress/gutenberg/pull/17399
Specifically this line:

https://github.com/WordPress/gutenberg/blob/0e0b65f76d06bcf0cf74bfc659d823289b93bded/packages/components/src/mobile/keyboard-aware-flat-list/index.ios.js#L15

The SafeArea have always been hierarchically behind the Block List, but block list never extended beyond the toolbar.

Now with `overflow: 'visible'`, the table content extends until the bottom of the screen, effectively showing over the SafeArea view.

These are screenshots with the After and Before, where the SafeArea is highlighted:

After
![Screen Shot 2019-10-09 at 9 06 23 AM](https://user-images.githubusercontent.com/9772967/66459212-e7593580-ea74-11e9-9808-df85dc93b7bc.png)

Now:
![Screen Shot 2019-10-09 at 9 08 43 AM](https://user-images.githubusercontent.com/9772967/66459222-ed4f1680-ea74-11e9-8c43-6846c507f191.png)

My guess is that `overflow: 'visible'` is needed for the Floating Toolbar to work properly, so we might need to looks for ideas to fix this somewhere else?

cc @pinarol @koke @lukewalczak

**Comment by lukewalczak** [comment]
@etoledom Thanks for the catch. Actually, we can remove `overflow: 'visibile'` since it's not needed right now and also it's not needed for [FloatingToolbar shippable version](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1413). 
Once the work over the ideal version for FloatingToolbar will be resume I'll investigate it if it's still necessary. Should I prepare quick fix PR for that?

**Comment by pinarol** [comment]
> Actually, we can remove overflow: 'visibile' since it's not needed right now and also it's not needed for FloatingToolbar shippable version.
Once the work over the ideal version for FloatingToolbar will be resume I'll investigate if it's still necessary. Should I prepare quick fix PR for that?

Thanks @lukewalczak, yes please, could you prepare one quickly? 🙏 Otherwise this can be a blocker to ship the new version. As you said we won't need this for `FloatingToolbar shippable version`

**Comment by lukewalczak** [comment]
Sure! Going to prepare it right now
