### ISSUE TITLE
Add Spacer block - 1st iteration

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#1428]
We need to add mobile equivalent of Spacer block, it will look same with web but for the 1st iteration we won't be adding a draggable handle to resize the canvas. The size of the canvas will be determined by block settings.

cc @iamthomasbishop

**Comment by pinarol** [comment]
We will track the draggable handle with a separate issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1429

**Comment by iamthomasbishop** [comment]
Here are some initial sketches:

![image](https://user-images.githubusercontent.com/1200432/66493254-5afe4100-ea7b-11e9-85d2-81a2e82087e8.jpeg)

Notes:

* **Inspector controls**: For the height property, the web uses a stepper input, which is essentially a text input with up/down buttons. I think we could probably use our Slider component (more info [here](https://github.com/WordPress/gutenberg/pull/17282)) and set `min` value of `20` and something like `500` for a `max` value. This Slider component will also have a text input. 

_Note: we could potentially allow the input to go over 500, but the slider itself could be max at 500._

* **On-canvas height adjustment**: As @pinarol mentioned, the capability to resize by drag & drop will be tackled separately (option B here)

**Comment by iamthomasbishop** [comment]
Here is some more detailed design documentation:

![Spacer Block](https://user-images.githubusercontent.com/1200432/66524917-6a9c7a80-eab9-11e9-83e5-55b9da845bf4.jpg)

**Comment by lukewalczak** [comment]
Hello @iamthomasbishop thanks for the detailed design which gives me better insight. 
Currently we are going to follow option A, so I have two question referring to design:

* Should spacer block have blue drag indicator once it's not draggable? (_no 1 on the screenshot_)

* What is the responsibility of spacer button in the toolbar (_no 2 on the screenshot_) if settings button (_no 3 on the screenshot_) is opening the inspector control?

![66524917-6a9c7a80-eab9-11e9-83e5-55b9da845bf4](https://user-images.githubusercontent.com/22746080/66554030-7ab16a00-eb4c-11e9-9119-d5603a73db16.jpg)

**Comment by iamthomasbishop** [comment]
> Should spacer block have blue drag indicator once it's not draggable? (no 1 on the screenshot)

No, the drag handle should be added as part of the “draggable” work [here.](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1429)

> What is the responsibility of spacer button in the toolbar (no 2 on the screenshot) if settings button (no 3 on the screenshot) is opening the inspector control?

That icon is intended to show which block is currently selected, in this case the spacer. But because we don’t currently show this, we can skip for now and work on it in another task.

> Should static spacer have height 20 by default, because it's a min value?

Yes, exactly. It uses the same 20px min-height that the core block does.

**Comment by koke** [comment]
> For the height property, the web uses a stepper input, which is essentially a text input with up/down buttons. I think we could probably use our Slider component

@iamthomasbishop other than because we already have it available, is there a reason why you'd prefer to switch to a slider? At least on iOS we have [steppers](https://developer.apple.com/design/human-interface-guidelines/ios/controls/steppers/) that look more similar to the web implementation.

**Comment by lukewalczak** [comment]
> Note: we could potentially allow the input to go over 500, but the slider itself could be max at 500.

Actually I see some potential problems with that approach. Let's say that user will set a height in input to be 1000, but slider will display the max value - 500. In the same case if the user wants to reduce the height using the slider will start reducing it from 500.

**Comment by pinarol** [comment]
> At least on iOS we have steppers that look more similar to the web implementation.

The problem is Android misses it. I think if we can find a decent Stepper library that works for both iOS/Android it'd be better than using Slider.

**Comment by lukewalczak** [comment]
Should we create a separate issue for investigating `Stepper` or it should be investigated within that issue? It will be good to have also a design for that.

**Comment by pinarol** [comment]
@iamthomasbishop We can put some kind of (-)(+) buttons and make our own stepper but it would be different than the native one in iOS. I mean even if we make it look very close currently, the native one will probably change in upcoming iOS releases. But in terms of functionality it would fit into this case better than the Slider. WDYT? If you have some designs we can give it a try.

We can get inspiration from this one implementation-wise and change its UI:  https://github.com/jadghadry/react-native-custom-stepper

**Comment by lukewalczak** [comment]
@pinarol Just to clarify, are we aiming for `TextInput` with `Stepper` next to it?

**Comment by lukewalczak** [comment]
I think that we can create our custom stepper which will look same on both platforms. 
I can imagine it as a plus/minus (or arrow up/arrow down) buttons with text input in the middle.

**Comment by pinarol** [comment]
> @pinarol Just to clarify, are we aiming for TextInput with Stepper next to it?

Yes that's the idea but let's hear from @iamthomasbishop about not using the iOS native one and making our own in react-native level.

**Comment by koke** [comment]
I'll leave it to Thomas to decide, but I think using the existing iOS control is worth the tradeoff of losing a bit of consistency across platforms. It will probably have better accessibility by default that we would come up with, and possible [some other subtle things](https://developer.apple.com/documentation/uikit/uistepper):

> If you set stepper behavior to “autorepeat” (which is the default), pressing and holding one of its buttons increments or decrements the stepper’s value repeatedly. The rate of change depends on how long the user continues pressing the control.

**Comment by pinarol** [comment]
If React Native provided a Stepper that uses the iOS native Stepper underneath I'd definitely want to go with it, but in this case we'll need to implement our own bridge module for iOS. And we'll need to implement a separate Stepper for Android on RN level. That means separate know how and separate maintenance effort will be required for both of them in the future. I can't deny advantages of using the native one but I think by choosing RN we kinda made a choice between that type of pros/cons. And I am not sure how smooth that `autorepeat` would work through an async React Native bridge so it needs experimenting. I am totally up for discussing this in further detail and I think we should bring in more people to this discussion as it'll effect all contributors. But, even if we choose to move fwd with building our own iOS native bridge module, I'd prefer to defer it to a later date because of the current schedule.

**Comment by lukewalczak** [comment]
Some time ago within library react-native-ios-kit we created a [`Stepper`](https://github.com/callstack/react-native-ios-kit/blob/master/src/components/Stepper.js) in the shape of `UIStepper` but totally built on react-native components. It contains the `autorepeat` behaviour where value is decreasing/increasing repeatedly. I'd say it's worth checking out and even adapt the logic and appearance to our needs.

**Comment by pinarol** [comment]
> react-native-ios-kit

I saw that but I thought it had only support for iOS because of the naming 🤔

**Comment by lukewalczak** [comment]
Generally, it’s made specifically for iOS, that’s why I said we can try to adjust the logic from that lib to our requirements and wrap it in our custom design.

**Comment by iamthomasbishop** [comment]
I suppose at the end of the day, my "ideal" would be to use the 100% native component of a Stepper so we can inherit some of the benefits we'd get in terms of accessibility, platform-native visuals, and future-proofing. But considering it doesn't appear to exist as a component on Android, I think it would make sense to either:

* Option A: Use the 100% native one on iOS, and use a custom one on Android
* Option B: Use a cross-platform RN component with a custom design for each

I'd prefer to go with Option A, because we at least get the iOS benefits and only have to create something for Android.

If we decide to roll our own component (option B), I would essentially provide separate designs for Android and iOS that look basically identical to the native components (Android, [iOS](https://developer.apple.com/design/human-interface-guidelines/ios/controls/steppers/)) with text inputs. That'd look like this:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/1200432/66678029-95f5a580-ec30-11e9-9256-0bcb69c2cd6f.png">

**Comment by lukewalczak** [comment]
Honestly, I would like to first create a custom stepper for both platforms, adjust it for an accessibility and for our design. I think it will be easier to maintain one component without the need of creating native modules. WDYT?

**Comment by pinarol** [comment]
For both option A and B we need to implement a custom Stepper for Android on RN level, so we can start implementing that and see if it is working nicely. Option A needs further discussion with the rest of the team so I'll start that convo and return back here.

**Comment by lukewalczak** [comment]
👍 I'm going to start creating RN `Stepper` according to design above.

**Comment by lukewalczak** [comment]
The question is should we specify `maxValue` on mobile? It doesn't exist on web.

**Comment by pinarol** [comment]
I think we should match web behavior and not provide a `maxValue`.

**Comment by lukewalczak** [comment]
@iamthomasbishop Could you please update the design for `BlockSettings` with a `Stepper`?

**Comment by iamthomasbishop** [comment]
@lukewalczak will put that together today!

**Comment by iamthomasbishop** [comment]
Hey y'all, as I came back to this issue to re-read the backscroll, I realize somewhere along the way I might've mixed up this block (Spacer) with Columns (which I'm also working on). I don't think a Stepper is the appropriate component here, because the range of potential values is very wide.

I think my intention was that we use the Slider w/ TextInput (like the design above) because the range can be very wide – even with repeatability on the stepper, it's going to be a bit much. (Compared to the "number of columns" setting on Columns, which has a much smaller range, in which case a Stepper makes sense).

The only downside regarding this approach is we want to do a max value. Honestly I think that's an okay trade-off vs. a Stepper. We can always iterate or explore other components in the coming weeks, but I think this is the best starting point.

**Comment by lukewalczak** [comment]
We can always pass a `step` value to `Stepper`, but understand that when values are wide it may not be enough. 

If we are returning  to the first idea witha `Slider` I will wait for @jbinda's [PR](https://github.com/WordPress/gutenberg/pull/17282) merge.

Anyway I think it's worth to create a `Stepper` as a controller for other cases in the future. Maybe we should create an issue for that? Wdyt @pinarol ?

**Comment by pinarol** [comment]
> If we are returning to the first idea witha Slider I will wait for @jbinda's PR merge.

Sounds fine 👍

> Anyway I think it's worth to create a Stepper as a controller for other cases in the future. Maybe we should create an issue for that? Wdyt @pinarol ?

I can create the issue once we decide on the approach.

**Comment by jbinda** [comment]
There is another question. Do we merge `Slider` now as we discuss on Slack and do the styling in next iteration. Because II'm not sure if @iamthomasbishop have read our Slack conversation (according to his comment [here](https://github.com/WordPress/gutenberg/pull/17282) )

**Comment by pinarol** [comment]
👍@jbinda left this [comment](https://github.com/WordPress/gutenberg/pull/17282#issuecomment-542115690) on the Slider PR.

**Comment by lukewalczak** [comment]
I would like to discuss one more time setting the maximum spacer height. 
Slider as a component is used to choose the value from the range of values (min and max should be specified). Honestly, I'm not convinced to the idea of not passing the max value and slider usage.

**Comment by iamthomasbishop** [comment]
@lukewalczak I think setting a max is a good starting point, assuming most often this will be set between 20 and maybe 500. (Note: if we have any data on this, which I don't think we do, we might want to confirm // cc @pinarol ). From there, we can iterate based on what we learn from usage patterns. I don't foresee this being a huge problem, but there are always stress cases and we will have the option of increasing the range, or the nuclear option of falling back to a Stepper.

With that said, I would propose we start with a max of 500px for the Slider and see how that feels in practice. It might be too wide a range for the slider to achieve granular selection, but we also have the TextInput to help with that.

I do have a question, though: what happens when someone sets the value on the web to something larger than our max? I have seen this in design tools sometimes when opening an inherited file – where a control's value is larger than the max, but if I edit the field I'm locked back into the min-max range of the control. Would it act like that?

**Comment by lukewalczak** [comment]
> I do have a question, though: what happens when someone sets the value on the web to something larger than our max

I haven't added the logic to save the attribute yet (there was ongoing discussion about which component to use, so I stopped working), but I imagine it this way:

* let's assume the user set height 800 on the website and then edits it on the phone. The maximum value of the slider is then set to 800.

**Comment by iamthomasbishop** [comment]
> let's assume the user set height 800 on the website and then edits it on the phone. The maximum value of the slider is then set to 800. The problem then is that user will not able to increase the value (above the 800).

I think this is slightly better than the scenario I was explaining previously (not perfect, but better 😄 ). Thanks for confirming!

**Comment by lukewalczak** [comment]
Alternatively the value from web can be in the middle of the range, so user can decrease and increase the value as well.
