### ISSUE TITLE
Feature Request: Show all html tags when in html mode.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/gutenberg-mobile#1569]
An iOS user asks if all HTML tags could be visible when editing a post in HTML mode.  Currently some tags, like paragraphs, are not displayed in the mobile editor but are in the web editor. 

Ref 2483588-zen

**Comment by hypest** [comment]
Had a look at that Support ticket and it looks like the html mode is in the Aztec (Classic) editor on iOS.

Aztec performs autop/removep when loading/saving the post and that's why the p tags are not shown.

In mobile Gutenberg, the html mode does indeed show the p tags so, I'll close this ticket. But @aerych , can you open tickets in the Aztec repos if you still want to preserve the feature request? Thanks!

**Comment by aerych** [comment]
Ah! Thanks for clarifying @hypest!  Let's just leave it closed since (as I understand it) the end goal is to eventually sunset the classic editor and be 100% block editor.
