### ISSUE TITLE
Validation error in HTML mode after modifying a html tag

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/gutenberg-mobile#1570]
**Describe the bug**
When I replace a valid tag in HTML mode with an invalid tag gutenberg displays validation error -> eg `<p>` with `<p123>`.

**To Reproduce**
1. Create a post in WPAndroid
2. Type "hello"
2. Switch to HTML
3. Edit `<p>` to `<p123>`
4. Click on title
5. Boom

**Expected behavior**
The app won't crash.

**Screenshots**
![crash-gb](https://user-images.githubusercontent.com/2261188/68681421-acf72280-0563-11ea-81f1-0b513999ca69.gif)

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android API 29
 - Version develop - 6e59663f8c0eda962c8a6fa0a45212fbd17942b1

**Comment by cameronvoell** [comment]
As I'm working on this, I just wanted to comment that since the exhibited behavior is actually a` Block Validation` error (which only show the red banner in develop mode) and not a crash, the behavior for users will not be a full fledged crash, but will actually show disappearing paragraph HTML (the invalid block still shows in visual mode) . There is still something interesting going on here that should be fixed, but it might not have the urgency expressed in the title of this issue, since it is not actually crashing for users. See behavior in non develop build in the following video.

![html-error](https://user-images.githubusercontent.com/1103838/72183851-df769d80-33a3-11ea-93ee-02bd56aca1e1.gif)

**Comment by Tug** [comment]
Related issues on gutenberg:
https://github.com/WordPress/gutenberg/issues/10980
https://github.com/WordPress/gutenberg/issues/12275
https://github.com/WordPress/gutenberg/issues/12350
https://github.com/WordPress/gutenberg/issues/7604

**Comment by geriux** [comment]
I'm closing this PR due to its activity. Currently, there's no easy option to toggle between editors and now if you change the HTML markup and it's detected as invalid, the editor will show a placeholder with an option to attempt to recover it.

Please feel free to re-open it if we happen to get any user reports about it. Thanks!
