### ISSUE TITLE
Create a library/framework that can be used in the apps

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#163]
We want to be able to use gutenberg-mobile in the mobile apps (Android and iOS). More specifically we should be able to:

- run a debug build of the app in Android Studio. or Xcode, and be able to include a debug version of gutenberg-mobile inside it
- include gutenberg-mobile in a release build of WPAndroid/WPiOS

**Comment by koke** [comment]
@etoledom since you're already half way through this, can you make a task list of what needs to be done and add some estimations?

**Comment by koke** [comment]
Also, as we work on this one, let's make sure to keep @wordpress-mobile/platform-9 involved

**Comment by loremattei** [comment]
Hey! Thanks for pinging @koke! 
@etoledom @hypest let me know when we can talk about this :-)

**Comment by etoledom** [comment]
For the tasks mentioned, I believe that **one sprint time** is enough to have a first up-and-running Gutenberg inside the Native apps. But being aware that it will not be a definitive setup.

Ideally we will give a working starting point open to evolve with future requests, realizations and issues that we might encounter.

**Comment by hypest** [comment]
Android subtasks:

- [x] Debug version of wpandroid with Gutenberg-mobile integrated
- [x] Release version of wpandroid with Gutenberg-mobile integrated
- [ ] Move from `git submodule` to `git subtree` to include the editor's code or decide to library-fy in a different way

**Comment by jtreanor** [comment]
👋I have been spending some time taking the feature branches for integration in the WordPress apps for a spin. I'm very impressed with all the progress that has been made.

One thing that I'd like to highlight is where the border between React Native and native should live. In my opinion, the ideal state would be that the apps are not required to have any React Native knowledge in order to consume Gutenberg.

On the feature branch for WP Android, [`AztecEditorFragment.java`](https://github.com/wordpress-mobile/WordPress-Android/blob/feature/gutenberg-mobile/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java) currently does much of the RN bridging logic within the app itself. This makes sense right now to help iterate quickly and feel out the best approach. However, I think we should revisit this closer to the final release. Perhaps this RN context could be moved back to `gutenberg-mobile` or even a new repo.

I discussed this with @hypest and he suggested I post here to capture these thoughts.

**Comment by etoledom** [comment]
Thanks for taking the time to check this out @jtreanor !

On WPiOS, my effort is to expose this header file to the WordPress app: 

https://github.com/wordpress-mobile/gutenberg-mobile/blob/master/react-native-gutenberg-bridge/ios/Gutenberg.h

It expose Gutenberg Editor as a UIView (similar to Aztec), a delegate to receive messages and methods to send messages to Gutenberg. And it doesn't have dependencies on React/React-Native.

My intentions is to firstly try an integration via Cocoapods. Not sure if it's the best option, but it's the one I have found more info about.

Waiting forward to know your opinion about it!

**Comment by loremattei** [comment]
Hey! These messages make me realise that I'm very late in answering a ping from @koke here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/195#issuecomment-433365065. :-) 
About it, I agree 100% with the target of having binary integration for release and no-GB dev builds and source level integration for working with GB in the apps.
Of course, let us know any help Platform9 can give on this.

**Comment by jtreanor** [comment]
@etoledom That looks like a very promising approach and exactly what I was talking about above.

CocoaPods in some form will probably make sense for consistency with the rest of the app. Its possible that distributing the pod as a binary may make sense, though I'm not too sure.

I'll check out the in progress iOS integration some more and let you know if I have any thoughts.

As @loremattei said, if there is anything specific we can help with, just let us know 😄

**Comment by hypest** [comment]
> if there is anything specific we can help with, just let us know

Thanks @jtreanor . I'd say that if there are any spare cycles you can donate, it's be awesome if you could try out what we said on Slack a few days back and is what @loremattei mentioned above: to have a way to rely on binary integration but still have source level integration for debug builds.

**Comment by hypest** [comment]
I think we have completed this task on both platforms so, closing as "done".
