### ISSUE TITLE
Multiple undo levels created while adjusting Spacer height in bottomsheet

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#1635]
**Describe the bug**
Moving and dropping the slider for the Spacer height in the bottomsheet seems to create multiple undo levels, even without dismissing the bottomsheet.

**To Reproduce**
1. Add a Spacer block
2. Tap on the cog icon to open the block settings
3. Adjust the slider a few times by dragging and dropping it in between
4. Dismiss the bottomsheet by tapping outside
5. Tap on the undo button and notice that there are multiple levels created, one for each slider adjustment

**Expected behavior**
I'd expect to only have one undo level, the one created when the bottomsheet gets dismissed.

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 9
 - Version on hash fe1de50f

**Comment by lukewalczak** [comment]
@hypest I've discovered there is a general difference in `UNDO` button behaviour between mobile and web - an issue which you describe affects other components as well. 
Take for example `Heading` block, where `UNDO` button no mobile is shifting back last typed character and on the web is taking back to the initial state, unless that behaviour in case of Heading/Paragraph component is intentional.

web | mobile
--- | ---
![undo_web](https://user-images.githubusercontent.com/22746080/72065015-79bfde00-32dd-11ea-9aaf-068c043d896a.gif) | ![undo_mob](https://user-images.githubusercontent.com/22746080/72065019-7b89a180-32dd-11ea-9d16-bcd2f3436589.gif)

**Comment by lukewalczak** [comment]
Generally, that issue affects blocks which can be changed via options in `BottomSheetSettings`. The same behaviour we can notice in `Image` block component while photo size is changed a couple of times.

Spacer | Image
--- | ---
![spacer_undo](https://user-images.githubusercontent.com/22746080/72072278-e2af5200-32ed-11ea-8245-5ddf8d535bd2.gif) | ![image_undo](https://user-images.githubusercontent.com/22746080/72072287-e5aa4280-32ed-11ea-84af-90792e4fac55.gif)

Block reacts on changes made in the bottom sheet, saving them and then once undo button is pressed it's shifting changes back one after another.
I would like to get your @iamthomasbishop input there, what should be the desired behaviour on that.

**Comment by iamthomasbishop** [comment]
@lukewalczak I took a look at how a couple of other apps handle this type of interaction, to make sure we're aligning with best practices. Google Docs, Apple Pages, Dropbox Paper, and more all work the same way. where every small edit you make in this type of interaction is "logged" so an undo goes back through every one of the edits. 

I think we are probably safe to leave this as-is. We had at one point removed a "reset" button because it was removed on the web-side, and also I could potentially see some sort of "cancel changes" button being useful on these types of sheets, but that's for another time 😄

**Comment by lukewalczak** [comment]
Thanks for investigation and quick feedback! Make sense for me and agree with that ✌️

**Comment by hypest** [comment]
👋 @iamthomasbishop , I wonder, what do you think about the semi-transparent overlay the bottom sheet is casting to the rest of the UI while active, does it play well with the notion that the edits are "live" and registering? Is that shadow used in the other apps you checked out? The sense I get from the shadow is that "you are not exactly editing the content anymore but your are in a modal interaction".

**Comment by iamthomasbishop** [comment]
@hypest Good question, this is something that I've been thinking about lately. 

Most of the time when you see these types of bottom sheets, they by default have a 30-40% overlay (aka "scrim") but for _most_ sheets, I think we might want to make the scrim completely transparent. We might want to keep the scrim for things like Action Sheets (and their Android equivalents, which for us is Menu or RN Bottom Sheet), but for most others (block settings, block library, link editing, etc) we can probably safely remove the scrim.

**Comment by lukewalczak** [comment]
I have the feeling we are kinda discussing a bit different issue right now. Maybe we should close the current one and open an issue with `Technical Debt` label?

**Comment by Tug** [comment]
Seems like the outcome of this issue was decided, closing as wontfix.
