### ISSUE TITLE
Testing: Some UI tests are flaky

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#1662]
Some of our UI tests have flaky results, including on CI, leading to unreliable test results. A couple possible solutions we've discussed:

- Improve reliability of the tests themselves, to reduce flakiness.
- Rerun the tests on CI automatically and only report repeated failures.

Internal ref: p9ugOq-Nl-p2/#comment-1589

**Comment by rachelmcr** [comment]
As reported in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1615#issuecomment-562705259 the `rotate device and continue adding blocks` test has some flaky failures. An example of the test result on one of those failed test runs:

```
Error: expect(received).toBe(expected) // Object.is equality

- Expected
+ Received

  <!-- wp:paragraph -->
  <p>the finer continuum interprets the polynomial rabbit. when can the geology runs? an astronomer runs. should a communist consent?</p>
  <!-- /wp:paragraph -->
  
  <!-- wp:paragraph -->
- <p>the finer continuum interprets the polynomial rabbit. when can the geology runs? an astronomer runs. should a communist consent?</p>
+ <p>the finer continuum interprets the polynomial rabbit. when can the geology runs? an astronomer runs. should a communist cons</p>
  <!-- /wp:paragraph -->
    at EditorPage.toBe (/home/circleci/project/__device-tests__/pages/editor-page.js:124:32)
    at tryCatch (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at tryCatch (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at invoke (/home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:135:20)
    at /home/circleci/project/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:145:13
    at tryCallOne (/home/circleci/project/node_modules/promise/lib/core.js:37:12)
    at /home/circleci/project/node_modules/promise/lib/core.js:123:15
    at flush (/home/circleci/project/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by mchowning** [comment]
I spent some time looking into this, and it appears that there are two separate causes of the flakiness at this time. Although I don't have any fixes (yet), I wanted to go ahead and do a brain dump of what I've found so far.

### 1. Android does not always insert all the text we "type" in our e2e tests

This is the issue that @rachelmcr noted [above](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1662#issuecomment-563227725).

On Android, when we "type" text in an e2e test, all of the text does not always make it to the device. **I was able to reproduce this issue locally multiple times, so this is not an issue confined to CircleCI/Saucelabs.** Sometimes, just rerunning the test would fix the issue, but other times I had to restart the emulator to fix the issue. 

Most recently, I had the test fail probably >30 times in a row while I was trying to investigate the problem. Then I restarted the emulator and the failure stopped happening. Unfortunately, I actually couldn't find a way to cause the failure to occur again locally, which is why I'm taking a bit of a break in my investigation. Unfortunately, CircleCI doesn't seem to share my trouble recreating this issue. 😞 

[Out tests use adb to "type" text to the device](https://github.com/wordpress-mobile/gutenberg-mobile/blob/e5120a3810fbd7bf6742725f3ea3ac8d58845b72/__device-tests__/helpers/utils.js#L178) (essentially using `adb shell insert text "some text"`), and I observed on some occasions that when the tests were failing locally, I was also having trouble just manually sending text to the emulator using adb directly from my terminal. Also, when the tests were failing particularly badly, I found that if I killed the tests manually while running, text would continue being entered into the device for minutes afterwards (at a rate of a character or two every few seconds). I'm not entirely sure what to read from that yet, but it is interesting.

I did verify that updating our version of Appium from `1.16.0-rc.1` to `1.16.0` did not appear to resolve the issue.

### 2. Saucelabs "environment you requested is not available" error

On CircleCI this is reported as "The environment you requested was unavailable." On Saucelabs, it says:

```
Misconfigured -- You've exceeded your Sauce Labs concurrency limit. This test was throttled and ultimately timed out waiting for a free slot to run. You can upgrade your account for higher-concurrency at https://saucelabs.com/pricing
``` 

Looking at the saucelabs dashboard, it appears there is a large back up of tests waiting to run (at this time at least), and I have noticed that a single PR can actually use up all of our "concurrent worker" slots. 

![Screen Shot 2020-01-20 at 9 44 57 AM](https://user-images.githubusercontent.com/4656348/72737930-84e0fc80-3b6e-11ea-889f-2058ee05c658.png)

This seems like it may be a problem for 2 reasons:

1. If a single PR uses up all the slots, then other tests can/will timeout waiting for a slot with the ^above^ error
2. If different PRs use up different slots, then the PRs other tests for that PR may get put in the queue and timeout. I haven't verified this beyond having seen circleCI failures where some android tests failed because of the text entry issue, and other tests failed because of the "environment you requested is not available" issue.

![Screen Shot 2020-01-20 at 10 21 25 AM](https://user-images.githubusercontent.com/4656348/72738019-ac37c980-3b6e-11ea-821b-43cae6a409e5.png)

Obviously there's still some more investigation needed on both of these issues. I'm not familiar with our setup or use of Saucelabs, but I'll look into it some and see see what I can learn.

**Comment by mchowning** [comment]
It looks like there are three ways that queueing can cause tests to fail with Saucelabs:

1. **Only a certain number of tests can be queued.** The number is pretty high though (>150), so this isn't the cause of any of our problems.
2. **A test can only remain in the queue for 10 minutes.** If a test has not been moved out of the queue to run before 10 minutes elapse, the test is removed from the queue and *not run at all.* I believe this is the cause of our problems.
3. **Test runner times out while test is in the queue.** If a test is queued and run later, there is a chance that the test runner will timeout by the time the test is run. In this case, Sauce Labs will start a virtual machine to run the test and then wait for commands from the test runner. If the test runner has already timed-out, our VM will receive no commands. After 90 seconds, Sauce will end the session and shut down the VM. The error message of those tests will be "Test did not see a new command for 90 seconds. Timing out." I've seen this error before on our tests, but I don't think it comes up very frequently.

Info derived from [this page](https://support.saucelabs.com/hc/en-us/articles/360002048214-Queuing-Tests-on-Sauce-Labs).
