### ISSUE TITLE
 RNSVGPath Crash on Start of Example App

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#1703]
**Describe the bug**
Red banner on startup in the example app on Android. 

**To Reproduce**
1. Start the example gutenberg-mobile Example App. 
2. Notice the red banner mentioning RNSCGPath, seen in the screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/1103838/71220138-88dedd80-2295-11ea-91f8-219b8d084d5e.png)

**Additional context**
This error was showing up on branches/commits that were previously working, and is likely related to a change in the build environment/workflow. This error is showing on Android only.

**Comment by mchowning** [comment]
I believe this error is occurring because `react-native-svg` is dynamically pulling in the latest available RN version:

```
 implementation 'com.facebook.react:react-native:+
```

If I replace that with 

```
implementation "com.facebook.react:react-native:0.59.0"
```

the problem goes away. One important qualifier is that I **_had_** to build with `./gradlew clean installWasabiDebug --no-build-cache` to get the fix to take effect. Anything less and the error would remain.

Of course, we don't want to hardcode the RN version, and it actually looks like we may already have that addressed [on the master branch](https://github.com/react-native-community/react-native-svg/blob/master/android/build.gradle#L51) of our `react-native-svg` fork:

```
implementation "com.facebook.react:react-native:${safeExtGet('reactnativeVersion', '+')}"
```

but we aren't using that in `gutenberg-mobile`, and I havne't had a chance to test that out.

**Comment by mchowning** [comment]
Although this issue is only currently causing us trouble in `react-native-svg`, we should probably lock down the RN version for all of our forked RN libraries so they don't cause us similar problems in the future ([for example](https://github.com/wordpress-mobile/react-native-slider/blob/master/src/android/build.gradle#L40)).

**Comment by cameronvoell** [comment]
> Although this issue is only currently causing us trouble in `react-native-svg`, we should probably lock down the RN version for all of our forked RN libraries so they don't cause us similar problems in the future ([for example](https://github.com/wordpress-mobile/react-native-slider/blob/master/src/android/build.gradle#L40)).

We have at least one report (thanks @kmdupr33)  that after `react-native-svg` is fixed that we run into a problem with `react-native-video` almost immediately afterwards. Our fork for that video library already has the `safeExtGet` code mentioned above in [its gradle file](https://github.com/wordpress-mobile/react-native-video/blob/master/android/build.gradle). 

So basically I agree @mchowning  we should try and address the unspecified versions all at once, and likely using `safeExtGet`, but double check how our `reactNativeVersion ` is being populated.
