### ISSUE TITLE
Novice Doubt: How to integrate in my current app & fsevents error

### ISSUE THREAD

**Issue by ubarua123** [wordpress-mobile/gutenberg-mobile#1731]
Hi,
I have a basic doubt. I don't have much knowledge about node.js or npm. I have a couple of questions:

1. Do I need to run a node.js server for this editor to work? Why?
2. I can see I can integrate this in my existing Android App the same way the sample is done. But I am stuck at this error: `Error: 'fsevents' unavailable (this watcher can only be used on Darwin)`. Now I don't know what to do or what not to do.
Any help here would be appreciated.

**Comment by mchowning** [comment]
:wave:

>1. Do I need to run a node.js server for this editor to work? Why?

If you're running a debug build, then the javascript code is not bundled into the app and instead it pulls the code from a connected computer running the metro bundling server. That server is started by running `yarn start` after you run `yarn install`.  On Android you also need to make sure your device can reach the metro server by opening up that port with something like `adb reverse tcp:8081 tcp:8081` (update the port in that command if the metro server is running on a different port). For release builds the javascript code should be bundled into the app so the app does not need to pull any code from the metro server.

>2. I can see I can integrate this in my existing Android App the same way the sample is done. But I am stuck at this error: Error: 'fsevents' unavailable (this watcher can only be used on Darwin). Now I don't know what to do or what not to do.
Any help here would be appreciated.

I'm not sure what is causing that. It sounds like an error with watchman or fsevents not getting installed. It's been a bit since I did the setup for this, but do you have watchman installed. If not, try installing that.

**Comment by ubarua123** [comment]
Thanks for the prompt reply!. 
I understood point (1) very well. So I think to integrate, I create a release build, package everything together and set it up in my app. 
Still stuck with that fsevents, installing watchman didn't help. Doesn't matter, I'll figure out something else. Thanks by the way!
