### ISSUE TITLE
[GlobalStep] “Media & Text” Block’s button to change type does not function

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/gutenberg-mobile#1890]
### Description
Selecting the Text portion of a “Media & Text” block and pressing the button to change the block type does not function.

### Reproduction Rate
4/4 100%

### Expected behavior
The button with the icon displaying that the text block is a Paragraph block should allow the user to change its type.

### Actual behavior
Nothing happens when pressing the button with the Paragraph icon.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Add a “Media & Text” block.
6. Select the Text portion of the block.
7. Press the Paragraph icon.
##### Tested on the following
iPhone XR (12.0.1)
Samsung Galaxy Note 8 (7.1.1)

#### Please see the attached video for more information
[MediaAndTextBlock.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4193209/MediaAndTextBlock.zip)

### Submitted by:
Luis Pimenta

**Comment by SergioEstevao** [comment]
At the moment the ability to convert a block to another is still not available in GB-mobile. But it's something we plan to work on soon.

**Comment by hypest** [comment]
Hmm, I'm not sure we are planning to introduce the transform feature by attaching it to the InnerBlocks navigation bar. Let's close the ticket if there are no such plans. WDYT @iamthomasbishop?

**Comment by iamthomasbishop** [comment]
@hypest That's correct, no plans to attach transforms to the FloatingToolbar, but it might be worth considering in the future; I can see why one could expect to use that because we don't have transforms in the BlockToolbar (where users of web-GB are used to seeing the function). However, we will probably add transforms to the BlockToolbar in the near future.

What we _are_ likely going to do is show a BottomSheet when the user taps the [breadcrumbs on the FloatingToolbar](https://cloudup.com/ckZDiUaiMrG). The BottomSheet would contain a mobile-equivalent of the [block navigation (aka "List View")](https://cloudup.com/c4ZIUjW7LP1).

**Comment by hypest** [comment]
Work on adding transformations is around the corner, closing this ticket in favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2525. We can open again if ever needed.
