### ISSUE TITLE
Image size UI control for Gallery block

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/gutenberg-mobile#1921]
### Description

A PR was recently merged (https://github.com/WordPress/gutenberg/pull/19232) which introduced a new Cycle Picker component. It is used for cycling through the image size options within the Image block settings.

For Gallery block, it would be good to have a consistent UI with the Image block, so this issue is open to consider this change for Gallery as well, which is currently using a Select control for the image size setting.

One consideration I have for this kind of UX is for users with low bandwidth and / or poor connectivity. In earlier tests with Gallery image size options, I noticed that when I change size options, I must wait for a new file to download (each size option must be cached individually). This means that to change sizes with a cycle picker, the user may be required to download all sizes to their device as they cycle through them.

Another consideration is consistency between the native and web implementations of the Gallery block settings. A point was [recently raised](https://github.com/WordPress/gutenberg/pull/20231#issuecomment-586293328) regarding platform divergence on a different settings component which may be applicable here as well.

It may be necessary to find a way to optimize image loading for Gallery images before implementing a Cycle picker, and I think it's worth some design consideration for how that might look on web as well.

**Comment by jhnstn** [comment]
The image size selection has changed since this was opened and both the Gallery and Image block are now consistent 

## Image 
https://user-images.githubusercontent.com/744755/155342883-a16afe50-4e84-46ed-a45a-e4628b848ee1.mp4


##Gallery
https://user-images.githubusercontent.com/744755/155342883-a16afe50-4e84-46ed-a45a-e4628b848ee1.mp4

I'm closing since the primary focus on the issue — UI inconsistencies — is now outdated.

The other concerns about the UI should be brought up in a new issue.

**Comment by mkevins** [comment]
> The other concerns about the UI should be brought up in a new issue.

Actually, I believe the other concerns have been addressed since this issue was opened. At least, from your video, it seems that the cycle picker is no longer being used (which was the source of the issue mentioned). Thanks for circling back to this @jhnstn  :+1:
