### ISSUE TITLE
Quote block placeholder is not visible

### ISSUE THREAD

**Issue by ceyhun** [wordpress-mobile/gutenberg-mobile#1970]
**Describe the bug**

Quote block's `Write Quote...` placeholder is not visible on Android

**To Reproduce**

1. Add `Quote` block
1. The `Write Quote...` placeholder on top of `Write Citation...` placeholder doesn't appear on Android

**Expected behavior**

There should be a `Write Quote...` placeholder on top of `Write Citation...` placeholder

**Screenshots**

Android | iOS
-- | --
<img width="541" alt="android-quote" src="https://user-images.githubusercontent.com/1845482/75560647-dde16180-5a45-11ea-98e3-d6dc7e50a9e1.png">|<img width="540" alt="ios-quote" src="https://user-images.githubusercontent.com/1845482/75560655-e0dc5200-5a45-11ea-8652-ccc284d06bb9.png">

**Smartphone (please complete the following information):**
 - Device: Nexus 5X API 29 x86 emulator
 - OS: Android 10.0
 - Version: 1.24.0

**Additional context**

Realised this while implementing `Pullquote` block: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1920
https://github.com/WordPress/gutenberg/pull/20265

Quote block uses `RichText` to implement the text inputs and issue seems to be with that component. For the `Quote` block the only difference between the quote and citation input fields is that the quote input gets the `multiline` prop passed in: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/quote/edit.js#L45

When `multiline` prop is removed it works as expected.

**Comment by cameronvoell** [comment]
Going to save a few notes on here (perhaps for myself).

We are seeing the missing placeholder because multiline prop/functionality causes empty paragraph tags (`<p></p>`) to be sent to our [AztecText](url), and it needs to be completely empty for the placeholder to be shown. See note in comment here:
https://github.com/WordPress/gutenberg/blob/316c2f9ef46ed821190e2229ba0b71d01c2bd54a/packages/rich-text/src/component/index.native.js#L681-L684

If we simply catch when we have an empty paragraph tag, and set the text to an empty string (`""`), we start seeing some immediate problems. Basically some of the functionality around selecting and manipulating multiline quotations is currently reliant on the paragraph tags being there, even when the actual text content is empty. My strategy so far has been trying to fix all the places that need the paragraph tags even for empty content, in order to work. For example this function was breaking if we simply remove paragraph tags for empty strings https://github.com/WordPress/gutenberg/blob/master/packages/rich-text/src/component/index.native.js#L532-L538

Unfortunately, even after a few small victories, I was still seeing some broken behaviors when merging blocks or doing multiline quotes with my strategy of deleting paragraph tags on empty blocks, and fixing the code reliant on them. An alternate strategy is to go to the `AztecText` on the AztecEditor-Android side and try and catch empty paragraph tags there and still show the placeholder text. As seen in the following link, we're already doing this with some end of line characters, so this could be a viable strategy, but will just be slower to test, and potentially more dangerous with affecting other users of AztecAndroid: https://github.com/wordpress-mobile/AztecEditor-Android/blob/1e09b7daa88498c2c8d62b09cee0c8af8bb86616/aztec/src/main/kotlin/org/wordpress/aztec/AztecText.kt#L1795-L1801

**Comment by cameronvoell** [comment]
>  I was still seeing some broken behaviors when merging blocks or doing multiline quotes with my strategy of deleting paragraph tags on empty blocks, and fixing the code reliant on them.

I was able to get this working with a relatively safe looking change. The code itself appears a bit hacky and unintuitive, and could probably use a larger refactor, but the more minimal change here in the following PR's seemed like the least intrusive way to fix this in the near term: 
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/22561
Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2307
