### ISSUE TITLE
has_gutenberg_blocks analytics not reported properly on Android

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#1972]
On Android, the [number of posts published with Gutenberg](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wpandroid_editor_post_published&interval=day&prop=editor_source&startdate=20200120&stat=uniques) is noticeably higher than the [number of posts published with blocks](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wpandroid_editor_post_published&interval=day&prop=has_gutenberg_blocks&startdate=20200120&stat=uniques). On iOS, however, there is not such a discrepancy ([`editor_source`](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wpios_editor_post_published&interval=day&prop=editor_source&startdate=20200120&stat=uniques) [`has_gutenberg_blocks`](https://mc.a8c.com/tracks/trends/?compareby=prop&eventname=wpios_editor_post_published&interval=day&prop=has_gutenberg_blocks&startdate=20200120&stat=uniques)).

For example, looking at February 27, 2020, which is representative:

| 2/27    |  gutenberg | aztec |   total | gutenberg/aztec diff | 
| --------- | ------ | ------- | ------- | ------ | 
| iOS     | 6003 |  3103 |  9106 | 2900 |    
| Android | 8069 |  3478 | 11547 | 4591 |    

| 2/27   | has-blocks | no-blocks |   total | has-blocks/no-blocks diff |
| ---------  | --------- | ---------- | ------- | ------ |
| iOS    |    6023 |     3142 |  9165 | 2881 |
| Android |    7489 |     4136 | 11625 | 3353 |

Notice that the numbers for iOS are _very_ similar between the two tables with the difference between gutenberg/aztec being 2900 and the difference between has-blocks/no-blocks is 2881. Android, however, is a different story. The difference between gutenberg/aztec on Android is 4591, but the difference between has-blocks/no-blocks is 3353. Based on this, it appears likely that we are failing to properly count some posts that have blocks on Android.

### What Could Be Causing This?

Looking at the code, the logic for detecting if a post contains blocks looks the same on [iOS](https://github.com/wordpress-mobile/WordPress-iOS/blob/c01bfeec1b4861114892313769926658f1912eac/WordPress/Classes/Models/AbstractPost.swift#L122) and [Android](https://github.com/wordpress-mobile/WordPress-Android/blob/c701c44dd58a2b49ae3d72320a15e04c7b338a6c/WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java#L406).

| Platform | Code |
| -- | -- |
| iOS | `content?.contains("<!-- wp:") ?? false` |
| Android | `postContent != null && postContent.contains("<!-- wp:")` |

Since the check itself appears the same, I wonder if on Android we may be failing to perform that check for some posts and update the analytics `has_gutenberg_blocks` value accordingly.

@maxme has noticed that we have a significant number of "empty" posts published on Android (apparently "1" represents an empty post on Android). I'm seeing around 17% of posts being empty on Android with only 4% being empty on iOS. All of these empty posts would return false for `has_gutenberg_blocks`, so this might also explain the discrepancy.

I did find that one scenario where we do not update the `has_gutenberg_blocks` value is when a post is uploaded later in the background:
1. Open a new post
2. Add a block
3. Turn on airplane mode
4. Leave the post (which saves it locally)
5. Turn airplane mode off once we are outside the editor
6. Observe that the resulting `editor_session_end` event does not contain a `has_gutenberg_blocks` property.

It does seem that `has_gutenberg_blocks` is `null` instead of `false` in this scenario, so this does not directly explain the problem discussed in this issue, but it may provide a hint to the underlying problem (and even if it is unrelated, it is still a problem that would be nice to fix).

**Comment by hypest** [comment]
We'll move this to the Release&Maintenance squad's project.

**Comment by SiobhyB** [comment]
I re-ran the numbers from 5th January, 2024, to see if there were similar differences to those noted in the issue's description.

| 5th Jan    |  gutenberg | aztec |   total | gutenberg/aztec diff | 
| --------- | ------ | ------- | ------- | ------ | 
| iOS     | 2421 | 180 | 2601 | 2241 |    
| Android | 3135 |  177 | 3312 | 2958 |    

| 5th Jan    | has-blocks | no-blocks |   total | has-blocks/no-blocks diff |
| ---------  | --------- | ---------- | ------- | ------ |
| iOS    | 2393 | 225 | 2618 | 2168 |
| Android | 3096 | 258 | 3354 | 2838 |

The difference between gutenberg/aztec on Android is 2958 and the difference between has-blocks/no-blocks is 2838, nowhere near the type of discrepancy originally reported between the two numbers.

> Observe that the resulting editor_session_end event does not contain a has_gutenberg_blocks property.
>
> It does seem that has_gutenberg_blocks is null instead of false in this scenario, so this does not directly explain the problem discussed in this issue, but it may provide a hint to the underlying problem (and even if it is unrelated, it is still a problem that would be nice to fix).

I checked the `wpandroid_editor_closed` but don't see the `has_gutenberg_blocks` prop showing up for that event. Perhaps it was removed somewhere down the line. 🤔 

I also checked for times the `has_gutenberg_blocks` prop has been counted as `null` for other events. 

For `wpandroid_editor_post_published`, it's been counted as `null` 10 times or less daily since 2023 (compared to around 50 daily in 2021). For the Jetpack app, `jpandroid_editor_post_published`, there are no records of the `has_gutenberg_blocks` prop being counted as `null`.

These were the other events where I could find the prop, but couldn't find evidence of it being `null`:

* `wpandroid_editor_opened` and `jpandroid_editor_opened`
* `wpandroid_editor_post_scheduled` and `jpandroid_editor_post_scheduled`
* `wpandroid_editor_draft_saved` and `jpandroid_editor_draft_saved`

From my side, I feel like all signs point to the issues with the `has_gutenberg_blocks` prop having been resolved _somewhere_. I couldn't find a specific PR to back this up, but the fact we haven't had similar reports in close to four years is likely a good signal. As such, I'm going to go ahead to close this issue. Please feel welcome to re-open if I've missed something!
