### ISSUE TITLE
Adding HTML anchor to heading block creates a problem displaying block in app

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/gutenberg-mobile#2000]
**Describe the bug**

When I add an HTML anchor to my heading block on the web, the block in the app appears with the error message "Problem displaying block."

**To Reproduce**
1. Create a new post on the web.
2. Add a heading block.
3. In the block settings, under Advanced, enter an HTML anchor.
4. Save or publish the post.
5. Open the same post in the app.

**Expected behavior**

I expect to see the heading block appear in the app with the same settings as on the web.

**Screenshots**

Web editor with HTML anchor settings:

![Screenshot 2020-03-11 16 21 13](https://user-images.githubusercontent.com/8658164/76439737-c181e500-63b4-11ea-820d-5a364f8a271e.png)

App editor:

Visual|HTML
-|-
![2020-03-11 16 22 14](https://user-images.githubusercontent.com/8658164/76439770-cd6da700-63b4-11ea-8f15-56d185f31082.png)|![2020-03-11 16 22 20](https://user-images.githubusercontent.com/8658164/76439778-cf376a80-63b4-11ea-9799-ba4976dcdd70.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 13.3.1
 - Version: WPiOS 14.2 app store version

**Comment by hypest** [comment]
Added the `headinganchor` string as anchor to the block from the web, and app logs show: `'Block validation: Expected attributes %o, instead saw %o.', [], [ [ 'id', 'headinganchor', true ] ]` so, this is a block validation issue that is probably caused by not proper support/preservation of the anchor data. Let's tackle this sooner rather than later.

@ceyhun , can you have a look at this one? Thanks!
