### ISSUE TITLE
[SPT] Design feedback issues

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#2012]
Collecting here a list of design tweaks from https://github.com/WordPress/gutenberg/pull/20718

- [x] Can we add ~12px of padding at the top of the page content? I believe we are applying additional padding on top of the post/page title in the editor, so this would align with that (example: https://cloudup.com/cbMvzmdHb6a)
- [x] The App Bar seems a bit too tall compared to the native one (~9 or 10px too tall). Can we shorten it up slightly to align more with the native one? I believe 56px tall should work across platforms (example: https://cloudup.com/c-hVuBGgeVv)
- [x] [iOS] Dark Mode: border-bottom on the navigation bar is a bit too strong. We can probably dim it down a bit?
- [x] [iOS] Dark Mode: I wonder if we should apply a dark gray bg on the Navigation Bar to match the native one.
- [x] Can we apply a 300ms fadeOut to the inline picker buttons when they disappear? 
> it's not anything critical, but it may be a nice little improvement if it doesn't require a bunch of work

**Comment by koke** [comment]
> border-bottom on the navigation bar is a bit too strong. We can probably dim it down a bit?
> we should apply a dark gray bg on the Navigation Bar to match the native one.

@iamthomasbishop can you give me specific values for these two?

**Comment by iamthomasbishop** [comment]
> can you give me specific values for these two?

Sure can!

_(Note: iOS dark-mode only)_

* Navigation Bar background: It would be worth x-referencing with WPiOS to see what value they're using because I don't believe they're using the translucent materials. If we can't, we can use `#1E1E1E`, which is _almost_ exactly the iOS system-defined "Primary" elevated gray for dark mode used for Navigation Bars.

* Navigation Bar border-bottom: Same suggestion as ⬆️ , let's use the same value as WPiOS if possible, otherwise we can use `#2D2D2D`.

**Comment by koke** [comment]
>  It would be worth x-referencing with WPiOS to see what value they're using because I don't believe they're using the translucent materials

It doesn't seem translucent but the color I'm seeing is #0f1518

**Comment by iamthomasbishop** [comment]
> It doesn't seem translucent but the color I'm seeing is #0f1518

That should work fine 👍
