### ISSUE TITLE
First paragraph block on new post has too much padding when not selected

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#2077]
Note: I’ve only seen this very recently on internal test builds. It doesn’t exist (yet) on the main WP Internal Alpha or the other public betas. So it must be from a very recently merged change. // cc @pinarol 

When creating a new post, the first empty paragraph block seems to have unwanted additional padding, pushing the placeholder text inward.

This extra padding goes away when you select the block or add any content.

![image](https://user-images.githubusercontent.com/1200432/77786822-80ccd180-702c-11ea-99b1-6e23d132f06e.jpeg)

**To Reproduce**
1. Start a brand new post
2. See the empty paragraph block placeholder text has too much padding.
The placeholder text should be aligned to the same 16px key line as other blocks.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro,Android Pixel 4, iPad Pro 
 - OS: iOS 13.3.1 (iPhone 11 Pro), Android 10 (Pixel 4), iPad OS 13.4 (iPad Pro)

 - Version: I’ve only seen this very recently on internal test builds. It doesn’t exist (yet) on the main WP Internal Alpha or the other public betas.

**Comment by jbinda** [comment]
I have check this and it was probably introduced after merge [new bordering logic](https://github.com/WordPress/gutenberg/pull/20769) and is also connected with fix replacing empty paragraph](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2077)

When we open new post we render first `Paragraph` in `DefaultAppender`. It is also wrapped with `View` which has padding of value `16px` applied. After implement new bordering logic it seems it gets extra margin. Will raise PR soon because already fix that
