### ISSUE TITLE
Template picker: Missing emoji characters in API 21

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/gutenberg-mobile#2093]
**Describe the bug**
The "service" emoji is missing on device with API <= 21
![Screenshot_1585743694](https://user-images.githubusercontent.com/40213/78137182-2ca76000-7425-11ea-848b-c7163b8a1c9b.png)

**To Reproduce**
1. Create a new page.
2. Scroll to see the "Service template" button and notice the "X" instead of tool emoji.

**Screenshots**

**Smartphone (please complete the following information):**
 - API 21 (I wonder if there are other missing emojis on lower versions).
 - Android
 - wpandroid 14.5

**Comment by pinarol** [comment]
@geriux could you take a look at this one? It is working fine =>Android 9 devices, but the older versions seems to not support that emoji. Probably that emoji requires a more recent version of unicode.

**Comment by geriux** [comment]
After some discussions, we decided to use 🔧instead of 🛠making it compatible with Android devices running a lower SDK.

While testing I spotted the "Envelope" -> ✉️ emoji wasn't working correctly for API Level >= 21 <=23

![Screenshot_1585757038](https://user-images.githubusercontent.com/4885740/78159688-2f18b280-7443-11ea-992a-f44a18d758a1.png)

I tested going to the [Unicode Version 1.0](https://emojipedia.org/unicode-1.1/) from the emulator's browser and barely some rendered correctly from that list, then I checked [the 6.0 version](https://emojipedia.org/unicode-6.0/) and almost all of them rendered correctly.

I'm not sure if its a device vs emulator thing but @maxme was that screenshot from an actual device or emulator? Did you see any issues with the envelope emoji?

**Comment by maxme** [comment]
> I'm not sure if its a device vs emulator thing but @maxme was that screenshot from an actual device or emulator? Did you see any issues with the envelope emoji?

This is probably a difference in unicode version. I can't test on a real device with API 21, I think that's not a big deal and it's only affecting ~3% of our users.
