### ISSUE TITLE
Heading Block: colors added for the heading block on the web do not appear when viewing the post in the block editor

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2165]
**Describe the bug**

Heading color isn't shown in the editor.

**To Reproduce**

1. Create a new post on the web.
1. Add a heading block and change the color for it in the block settings.
1. Save or publish the post.
1. View the post in the block editor in the 

**Expected behavior**

I expected heading block color to display properly in the editor even if it's not yet a block setting.

**Screenshots**

WPAndroid 14.6-rc-2 | WPiOS 14.6.0.1 TestFlight beta | Safari on iOS
--- | --- | ---
<img src="https://user-images.githubusercontent.com/1119271/79510137-09220f00-7ffa-11ea-8a7a-13a3cabf1aa0.png" width="200" alt="Screenshot_20200416-114622"> | <img src="https://user-images.githubusercontent.com/1119271/79510296-5c945d00-7ffa-11ea-819f-41196825e95a.PNG" width="200" alt="IMG_3635"> | <img src="https://user-images.githubusercontent.com/1119271/79510299-5e5e2080-7ffa-11ea-8e77-6bb009daf650.PNG" width="200" alt="IMG_3636">

**Smartphone**
 - Device: Pixel 3 and iPhone 6
 - OS: Android 10 and iOS 13.3.1
 - Version: WPAndroid 14.6-rc-2 and WPiOS 14.6.0.1 TestFlight beta

**Comment by mchowning** [comment]
I think it makes the most sense to start displaying the heading color when we implement the ability to change that color (https://github.com/wordpress-mobile/gutenberg-mobile/issues/1212). Just my two cents.

**Comment by rezzap** [comment]
We've had a report of something related to this in #3270094-zen with the theme Twenty Sixteen. 

>In Chrome browser on the desktop everything is fine. When I go to Wordpress mobile app, the color setting disappears. If I edit a post on the mobile app, the color settings also disappears in the Chrome web browser on the desktop.

At first, I wasn't able to reproduce this with the theme Independent Publisher active nor could @rossanafmenezes on Baskerville. Both were showing the correct color heading in the app editor even if the option wasn't available to edit it. If we tried to edit the header and update the post, the original color set from the browser was respected.

But then on switching to Twenty Sixteen the issue was seen. After editing the header on mobile, the color setting that was first set in the browser was completely removed and switched back to black. 

I imagine this is mostly related to which themes have the color options built-in and which have these added through the block settings directly. This was tested on Premium plan Simple WordPress.com sites.

**Comment by SiobhyB** [comment]
I tested with Twenty Sixteen and the latest version of the app (`24.3`) and verified this is no longer an issue. The heading's colour now appears as expected when saved on the web and viewed in the editor.
