### ISSUE TITLE
Add: Social icons block

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2191]
We need to add the mobile equivalent of core/social-links into mobile:

<img width="494" alt="Screen Shot 2020-04-28 at 13 45 39" src="https://user-images.githubusercontent.com/5032900/80478814-bc71f880-8956-11ea-88a0-1350d4400247.png">

@iamthomasbishop any design differences you'd want to see on mobile?

**Comment by iamthomasbishop** [comment]
@pinarol Had a chance to dig a bit deeper into the web implementation yesterday and I'm not seeing a ton of stuff that we need to be concerned about, but there are a few notable things that we will probably need to tackle — perhaps some of which could be tackled as separate projects because they affect other areas of the product. Ignoring some of the smaller flow-related and detail-level things I'd prefer to approach slightly differently, here are some of the bigger items:

## Inserter

First and foremost, because we would be introducing _so many_ new blocks, we will need to extend the capabilities of the inserter/block library to include a search function and/or categories. I have some sketches for this already, so it wouldn't require a whole lot of design work. I think this is something we should tackle sooner rather than later because the inserter sheet is already struggling to scale as we add more blocks.

## Link entry 

This is another example of where we could benefit from a "quick link" entry UI of some sort, similar to what is shown when you enter a link on GB web. This would house a single text input and allow the user to quickly add or remove a link. 

However, because we do not have this, I would simply move the link entry either to the block settings sheet (accessed by tapping the `cog` icon), or alternatively, put a `link` icon on the block toolbar which would show a link sheet — which is probably more discoverable. So if you have a single Social Icon block selected, the sheet would house `Link URL` and `Label` (whereas on the web, they have the quick link entry and separately, the inspector houses the label). ([example](https://cloudup.com/cpJQVphcQHS))

## Inline toolbar

I was going to point out that we'll need to change the default movers (vertical) to become horizontal (left/right) as we did on the Buttons block, but we are also working on this [collapsed inline toolbar variation](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2180) for blocks that are very narrow — the child blocks (single Icons) here would be affected by that. _Note: this also affects the block settings button, which is even more reason to move the entry point of link entry to the block toolbar as I mentioned above._

-----------------

Beyond that, I don't think there are glaring differences or things that we need to be aware of. It's a pretty straight forward block and now that we have the nested blocks UI model done, we are in a good place in terms of navigating the complexities.

**Comment by pinarol** [comment]
@iamthomasbishop Thanks for all the clarifications!

> Inserter

I agree definitely, we need to do something about this. Let's tackle that separately though. Please open an issue with the designs you have so we can assign that to someone. 

> Link entry

> put a link icon on the block toolbar which would show a link sheet — which is probably more discoverable

Sounds good to me 👍 

> Inline toolbar

https://github.com/wordpress-mobile/gutenberg-mobile/issues/2180 This is already work in progress. It'll ship before we ship social-links.

> Note: this also affects the block settings button, which is even more reason to move the entry point of link entry to the block toolbar as I mentioned above.

Exactly.

One question: What do you think about hiding the dimmed icons when the block is unselected? As far as I see the social-icons block will just show an empty space in unselected state if none of the buttons have links assigned. I discovered it just by removing the WordPress icon from the initial state and focusing to another block. Do you think we should have the same behavior on mobile?

**Comment by iamthomasbishop** [comment]
> Let's tackle that separately though. Please open an issue with the designs you have so we can assign that to someone.

@pinarol Sounds good, I’ll do that on Monday.

> What do you think about hiding the dimmed icons when the block is unselected?

This behavior on the web feels weird, even if I understand why it behaves that way (it helps with discovery and makes adding the most common icons). I think on mobile I would rather show these placeholder icons _only during the starter state_. Meaning if the user adds the block, we should show those placeholders at first but if they remove selection of the block and come back, only the ones that they have chosen will appear — no more placeholders. In other words, I would rather beef up the starter state.

If it makes more sense technically to use the same flow as web, then we can start there and refine.

**Comment by lukewalczak** [comment]
Hi @iamthomasbishop, do you have some design to share for social links which can be helpful?

**Comment by lukewalczak** [comment]
> Meaning if the user adds the block, we should show those placeholders at first but if they remove selection of the block and come back, only the ones that they have chosen will appear — no more placeholders. In other words, I would rather beef up the starter state.

So I assume that basically after adding social icons block user will see the same pre-defined icons as on web:

![image](https://user-images.githubusercontent.com/22746080/83512116-0909a000-a4d0-11ea-8cdc-c25a43cff14f.png)

Then user should be able to add a link to each of them, if will not do that for some of them, after unselecting the block, icons without link should disappear?

How do we want to handle then adding other icons? Do we want to add an inline appender (_like in Buttons_) which will open an inserter with available icons, or do we want to rely only on the main inserter?

**Comment by iamthomasbishop** [comment]
@lukewalczak I played around with some ideas again today and put together a blueprint to use as a starting point, which you can find on the [design docs](https://zeroheight.com/226850145/p/048e9a-social-icons). Let me know if you have any questions, and I’ll try to answer your questions below.

> So I assume that basically after adding social icons block user will see the same pre-defined icons as on web

I don’t know if others feel strongly about this, but I don’t know if we need to show 6 icons — and I think we should also model the behavior of the Buttons block here. So perhaps we could show the first 3 or 4 _and_ show the inline appender. That would look something like this:

![image](https://user-images.githubusercontent.com/1200432/83682495-953bc600-a5a9-11ea-83f2-d110e25f9271.jpeg)

> Then user should be able to add a link to each of them, if will not do that for some of them, after unselecting the block, icons without link should disappear?

While working on this, I tried out the updated social icons block on web and found this part is still a bit weird to me. Immediately after adding the block, it makes sense to show a bunch of suggestions — which makes sense. But after you’ve added some icons, it doesn’t seem as useful to _always_ show the suggestions when the block is selected. My suggestion would be to hide the suggestions if I’ve made any additions. In other words, only the starter state would show the suggestions. (Note: but we always show the inline appender, so they have an avenue to choose a new one easily).

> How do we want to handle then adding other icons? Do we want to add an inline appender (like in Buttons) which will open an inserter with available icons, or do we want to rely only on the main inserter?

I think we can follow the same behavior as buttons — show the inline appender.

> About link entry, I think we can also add the option to add link via link sheet when pressing the social icon.

Do you mean when the child block (single social icon) is selected, tapping it again would show the link sheet? That would be a slightly diff in behavior from what we currently have on other blocks, but I’m open to trying it in a test build. Another option if that doesn’t feel right would be to show the sheet when the user long-presses on the block.

Another thought regarding the link sheet — I think we can take the same approach to links as we did for the buttons block, where we put a link button in the toolbar that shortcuts to just the link settings but also have the link settings in the block settings sheet. For example:

![image](https://user-images.githubusercontent.com/1200432/83685656-a1765200-a5ae-11ea-964d-21a3e99d1258.jpeg)

**Comment by lukewalczak** [comment]
Hello @iamthomasbishop, thanks for the design details! During the work over it I've gathered some questions:

1. It's not quite clear from a design whether icons should be greyed when are not selected? Also, should they have some bg color (_some of them can be white when are active e.g: Snapchat_)?

unselected | selected
--- | ---
<img width="449" alt="Screenshot 2020-06-04 at 16 53 40" src="https://user-images.githubusercontent.com/22746080/83772706-f46e0900-a683-11ea-8e55-533d2b0acbf1.png"> | <img width="493" alt="Screenshot 2020-06-04 at 16 54 24" src="https://user-images.githubusercontent.com/22746080/83772801-0fd91400-a684-11ea-84b5-fe888d9957c1.png">

2. What should be an icon for `Link label` in link settings, which are opened via link button in toolbar?

<img width="300" alt="Screenshot 2020-06-04 at 17 01 19" src="https://user-images.githubusercontent.com/22746080/83773716-2cc21700-a685-11ea-85d9-c6025a14e4d3.png">

3. Do we want to keep icons without the url (_after the initial block creation, user just add new icon, but didnt fill the URL_)? 

4. Let me know if the design on screenshots is correct (_so far_):

action sheet | block settings | link settings
--- | --- | ---
<img width="493" alt="Screenshot 2020-06-04 at 17 11 49" src="https://user-images.githubusercontent.com/22746080/83774924-a27ab280-a686-11ea-9b6c-1c72343a2be6.png"> | <img width="449" alt="Screenshot 2020-06-04 at 17 12 44" src="https://user-images.githubusercontent.com/22746080/83774955-ac9cb100-a686-11ea-9129-c5b8bb304b2d.png"> | <img width="493" alt="Screenshot 2020-06-04 at 17 13 22" src="https://user-images.githubusercontent.com/22746080/83774976-b4f4ec00-a686-11ea-8751-8f481057cfee.png">

**Comment by iamthomasbishop** [comment]
@lukewalczak Great stuff already!

> It's not quite clear from a design whether icons should be greyed when are not selected?

Ahh good question, and I will update the blueprints to be clearer. Just so we're on the same page, I'm thinking of this in terms of active/inactive (in-use or not) and selected/unselected (block is or isn't selected). 

For all intents and purposes, we are only showing dimmed icons when the block is first added (aka "starter state") — and only the ones that _aren't selected_. So in this "starter state": 

* The WP icon is color-filled by default (because it is active upon creation)
* The others are grayed out (because they are inactive upon creation). When _any_ icon is selected, it is filled
* If I select an inactive icon, it becomes color-filled upon selection, but if I de-select without making changes, it goes back to grayed out
* If I select an inactive icon and make changes, it _stays filled_ until I remove it

This should align pretty well with the starter state on web — our main difference is we are only showing the suggested icons on the starter state. Let me know if all of that makes sense, or if I need to add clarity.

> What should be an icon for Link label in link settings, which are opened via link button in toolbar?

I'm not sure if we need any icons on that sheet. We can remove the one on the Link URL cell.

> Do we want to keep icons without the url (after the initial block creation, user just add new icon, but didnt fill the URL)?

This is a good question, and it's a slight caveat to my points above. My initial thought was that we should remove it after de-selecting if it's empty (because it could get confusing that there is an icon there but it isn't actually showing on the front-end. But after thinking about it a bit I thought of what I believe would be a common use case — I manually added an icon but didn't have a URL on my clipboard. In this case, I need to leave the editor (likely to a browser) to copy a URL, then come back to the editor to add it again.

**My proposal**: In the specific case that I've _manually added an icon_ and deselected it, it should remain on the canvas as an inactive icon so I can easily re-add it when I'm ready to paste/type a URL. It would require fewer actions and less cognitive load.

Here is the path I would see as a result if I've manually added an icon, left the editor to grab a URL, and returned:

1. Tap to select parent Social Icons block
2. Tap the desired icon
3. Open block settings
4. Paste URL (I think we can auto-paste here?)

As opposed to the path if we were to remove it:

1. Tap to select parent Social Icons block, notice that the icon I added _isn't there_
2. Tap inline appender to show inserter sheet
3. Find and tap the desired icon
4. Icon block is added, selected
5. Open block settings
6. Paste URL

Does that all make sense?

> Let me know if the design on screenshots is correct (so far):

Looks great overall, just a couple of notes/questions:

* After looking at this again and comparing against the Button block, I wonder if we need the block settings at all here. The only difference (WRT link settings) I'm seeing on the web is that the Button block links don't have the `Link label` field, which outputs in the HTML as an aria-label on a social icon's link. I'm curious if this is intentionally applied just to the social icon block or just that it hasn't been applied to the Button block 🤔 I'm not super familiar with `aria-label` so maybe there is some semantic rationale for this, but if possible, I would like to re-use the exact same link UI that we use on the Button block. Do you think we could/should find a way to merge the `Link label` field into it? 

cc @youknowriad — any idea whether the `Link label` setting exists on the Social Icon block's link settings but not on Button? ☝️ 

If we do keep the block settings, I have the following thoughts:

* Because we're combining settings that are separate on the web into a single section here, we should either change the title (`[Block title] settings`) to account for that or remove it.

* Is the `URL` input focused when I first open the block settings sheet? If not, I think it would make sense to apply focus to that input.

## Other notes
After seeing this, I realized I'm not entirely happy with the labels on the actionSheet. Here are a few requests (which we can tackle in another ticket if necessary):

* Add a description/header row to the ActionSheet that contains the block title and maybe also the word "options". Iin the example above, it would read `YouTube block` or `Youtube block options`.
* This would allow us to simplify and make the actions more generic. For example, the "move" options would become `Move block left` and `Move block right`, the "YouTube settings" option would become `Block settings`, and the "Remove YouTube" would become `Remove block`.

**Comment by lukewalczak** [comment]
**UPDATES**

* light mode

active | inactive
--- | ---
<img width="493" alt="Screenshot 2020-06-05 at 16 32 44" src="https://user-images.githubusercontent.com/22746080/83888733-880a0d00-a74a-11ea-89c3-2fc7fdfd062c.png"> | <img width="449" alt="Screenshot 2020-06-05 at 16 33 10" src="https://user-images.githubusercontent.com/22746080/83888736-89d3d080-a74a-11ea-9075-a1418c64b8ef.png">

* dark mode

active | inactive
--- | ---
<img width="493" alt="Screenshot 2020-06-05 at 16 32 25" src="https://user-images.githubusercontent.com/22746080/83888890-bd165f80-a74a-11ea-8091-8a09f4be54bb.png"> | <img width="493" alt="Screenshot 2020-06-05 at 16 33 18" src="https://user-images.githubusercontent.com/22746080/83888896-be478c80-a74a-11ea-8b2d-c5fbd1d1f894.png">

**Comment by lukewalczak** [comment]
**Action sheet UPDATES**

1. I removed the option to set url from option, it can be done via link button in toolbar above the keyboard (like in paragraph)
2. I've added a header to action sheet and refactor labels:

android | ios
--- | ---
<img width="427" alt="Screenshot 2020-06-08 at 15 50 22" src="https://user-images.githubusercontent.com/22746080/84038139-d401bf80-a99f-11ea-908a-305428331225.png"> | <img width="493" alt="Screenshot 2020-06-08 at 15 50 30" src="https://user-images.githubusercontent.com/22746080/84038148-d5cb8300-a99f-11ea-8af6-35283f93075f.png">

3. Prepared testing [IOS build
](https://github.com/wordpress-mobile/WordPress-iOS/pull/14259)

@iamthomasbishop please let me know wdyt ✌️

**Comment by iamthomasbishop** [comment]
Hey @lukewalczak, had a chance to test both iOS and Android and this is feeling really close! I have some feedback — most of them are not blockers, so I'll note the ones that I would consider blockers first, then non-blockers, then separate/unrelated issues I wanted to note.

## Blockers

Things I'd like to address before shipping a v1:

- Changes made to block alignment controls aren't visible on the editor (but are applied on front-end)
- [Android-only] Bottom Sheet heading can be changed to a section title ([example](https://cloudup.com/c4zBO57ZEs3))
- The floating toolbar sometimes shows "Social Icon" instead of the proper social icon/block name ([example](https://cloudup.com/cHMPn2dItiR)). I can't consistently reproduce this one but I've seen it a couple of times during testing.
- When adding the social icons (parent) block on an empty post/page, the cursor focus remains on the title
- Per our previous discussion, I think manually-added icons that are inactive should only show when the parent is selected.
- When the last child block is removed, the entire parent should be removed as well (see Buttons for example)

## Not blockers

Things that aren't as important but would be nice to ship v1 with:

- Link sheet
    - I don't think we need to auto-fill the URL field with clipboard contents
    - When a new child block is added, we should open the link sheet right away
- Inserter sheet
    - Can we remove the "Social Icon" child block from the inserter? For reference, I see "link", but don't see "social icon" as an available child block on the web ([example](https://cloudup.com/cHekoJg_mqG) on mobile)
    - The ordering of child blocks in the inserter sheet can feel random esp now that we have a lot of blocks in the list like this. How is the order of the child blocks in the inserter sheet determined? Can we force either alphabetical order or alpha with a few generic ones appended to the front of the list (link, rss feed, mail, but also maybe WP)?
- Can we try your previous suggestion of showing the link sheet when an already-selected child block is tapped? I think you were onto something. Can we also set a long-press (on a social icon in any state) to select the block and open its link sheet? After trying out a build, we can decide which (if any) should stay.
- Instead of applying the color fill to the background immediately when typing into the URL field, can we apply it when the link sheet is closed — perhaps with a slight delay and a smooth 300-500ms transition? So when I type a URL then hit enter, the sheet closes and the background transitions to its active color. Conversely, when I delete the last character from the URL field, the transition would reverse immediately.

## Unrelated

- I forgot to mention this a while back, but the size of the parent block on the floating toolbar is smaller than the selected one — I *think* the selected block icon is the proper size (24?) so can we bring the parent icon up to match? ([example](https://cloudup.com/cHVJZMJzkP6))
- External keyboard: "Delete" key should remove the selected block (exception would be richText blocks)

**Comment by lukewalczak** [comment]
## Blockers

✅ - alignment options works
✅ - changed the header style in Android action Sheet:

<img src="https://user-images.githubusercontent.com/22746080/84661800-26505c80-af1b-11ea-8e13-54b2047550c1.png" width="300" />

> The floating toolbar sometimes shows "Social Icon" instead of the proper social icon/block name (example). I can't consistently reproduce this one but I've seen it a couple of times during testing.

🤔  - True that floating toolbar or action sheet is displaying `Social Icon` instead of a detailed name when you save the post. I need to investigate if we can get a specific name (social name) after saving the post.

> When adding the social icons (parent) block on an empty post/page, the cursor focus remains on the title

🤔  - Need to investigate why that happens

✅ - manually added icons that are inactive are visible only when a parent or other child is selected. They will disappear also after saving the post.

> When the last child block is removed, the entire parent should be removed as well (see Buttons for example)

⌛ - Partially it works, need to do some tweaks.

## Not blockers

✅ - removed auto-fill the URL field
✅ - link sheet is opened when new icons is added
✅ - `Social Icon` is removed from the inserter
✅ - child social icons are sorted alphabetically
✅ - pressing already tapped icon will open the links sheet as well as long-pressing the icon in any state
✅ - added the animation (400ms) of changing icon background color after closing the links sheet. There is also a delay for closing sheet compensation (300ms).

## Unrelated

✅ - parent icon has the same size as selected block (24)

> External keyboard: "Delete" key should remove the selected block (exception would be richText blocks)

⌛ Didn't check yet what we can do there

Testing builds:
Android: https://github.com/wordpress-mobile/WordPress-Android/pull/12124
iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14259

**Comment by iamthomasbishop** [comment]
@lukewalczak Looking good! Here are some notes after testing Android as well.

## General issues

- Undo/redo seemed to be broken but after looking again, I think it might be related to some recent changes to how we handle undo-levels. It appears each character typed on the link settings sheet becomes an undo-level. So if I type "youtube.com/example", there are 19 undo-levels, which feels like a bug in practice // cc @dratwas 
- On the starter state, if you try to remove one of the placeholders, it removes the entire parent block

## Gestures to link settings

Regarding the gestures that open the link settings sheet — I think they feel a bit off to me. Here are some notes on the single-tap and long-press gestures that we were trying out:

### Single-tap

I think this interaction should work in the same way that a text link or a button link does — the first tap places the cursor or selects position, then a second tap shows a  native edit/selection menu. Perhaps we could do the following (imagine the parent block is selected):

- First tap selects a child social icon
- If I tap on a selected child social icon, I would expect to see roughly the same thing as I do when I tap around text or have some text selected — an Edit/Selection Menu (Note: we started working on a  RN-based "[Selection Toolbar](https://zeroheight.com/226850145/p/516090-selection-toolbar)" component a while back, so if we can't use the native component maybe we could use this). There has been a wider discussion around adding link menu items to the native menu, but for the sake of the child social icons blocks, I think an Edit Menu with a single "Edit Link" would suffice. ([example](https://cloudup.com/cgi5FGRGqu3))
- Tapping on "Edit link" would bring up the link settings sheet

### Long-press

The long-press gesture on a selected block also feels a bit odd, and I think it might conflict in the future where we might explore long-press activating a drag & drop block 'layout-editing' type of mode.

## Side notes

- Should we hide the block toolbar when the bottom sheets are open? ([example](https://cloudup.com/cjfon2-CJgK))
- Sorry for changing my mind on this, but I think we can safely remove the section title from the `•••` overflow menu's action/bottomSheet ("XYZ block options").  ([example](https://cloudup.com/cnp2abu_Fjf))

**Comment by lukewalczak** [comment]
Thanks for feedback @iamthomasbishop !

> On the starter state, if you try to remove one of the placeholders, it removes the entire parent block

Sure will fix it, but could you please specify how removal should be handled when removing `WordPress` icon in _starter state_ (the only one active icon in starter state)? Should the whole block be removed?

> Should we hide the block toolbar when the bottom sheets are open? (example)

I think the icon can stay, it's behind the overlay and it doesn't seem to be misleading

> Sorry for changing my mind on this, but I think we can safely remove the section title from the ••• overflow menu's action/bottomSheet 

Do you want to _completely_ go back to the previous solution where each option in `ActionSheet` contained the block name or just remove the header? Tbh I like the current solution, it's more transparent, less confusing.

**Comment by iamthomasbishop** [comment]
> could you please specify how removal should be handled when removing WordPress icon

What I meant was if I create a new social icons block (parent block), then remove a sibling (the Facebook icon for example), the entire parent block gets removed — when I would expect that only the Facebook icon to be removed.

> I think the icon can stay, it's behind the overlay and it doesn't seem to be misleading

Okay, let's leave as-is.

> Do you want to completely go back to the previous solution where each option in ActionSheet contained the block name or just remove the header? Tbh I like the current solution, it's more transparent, less confusing.

I was suggesting only to remove the title, but I'm on the fence about this. I think it works okay as an ActionSheet on iOS, but there's something about this specific `•••` bottomSheet that feels out of place. Perhaps it's because a "typical" Android bottomSheet for quick-selections doesn't have a title, just the list items. 🤔 Let's just leave it for now, because I think I'm going to write some new usage guidelines for actionSheet vs. bottomSheet.

**Comment by pinarol** [comment]
@iamthomasbishop I opened a separate issue to track SelectionToolbar: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2401 It is not going to be super simple, plus there are currently uncertainties about whether it is possible on Android. So it looks like it deserves its own issue.

**Comment by lukewalczak** [comment]
## Updates

The issue with undo/redo buttons is resolved and it should work properly. Also I've implemented _ghost_ placeholder for case when there are added only **inactive** icons.

Unfortunately, the tooltip component which we are using in page template isn't quite flexible and doesn't fit into our case after the initial analysis. Do we want to keep the current single tap mechanism or should it be removed in the worst scenario?

Testing builds:
Android: https://github.com/wordpress-mobile/WordPress-Android/pull/12124
iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14259

**Comment by iamthomasbishop** [comment]
As mentioned in Slack, I reviewed and the issues that I mentioned previously have since been addressed. I think we're in good shape to ship next week. Would y'all (@lukewalczak @pinarol, maybe @dratwas) mind giving this a thorough test before we ship? 🚀

**Comment by pinarol** [comment]
It seems automation couldn't close this one, I'll do it.
