### ISSUE TITLE
Media-Text: Add support for rendering focal point config

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2253]
Recently Media-Text on web started to support Focal point configuration. We don't have a support for that setting yet but we can start with properly rendering the image. Plus, I think we can add the `Crop image to fill entire column` setting as well.

<img width="284" alt="Screen Shot 2020-05-12 at 20 57 50" src="https://user-images.githubusercontent.com/5032900/81728772-a35b6280-9493-11ea-8eb4-d16ecd215d48.png">

**Comment by pinarol** [comment]
Also I want to ask @iamthomasbishop, we can support focal point settings just by adding 2 Sliders, 1 for horizontal and the other for vertical position, wdyt?

**Comment by iamthomasbishop** [comment]
@pinarol  We certainly could, provided that the image focal point is updated in relative realtime on the block itself so that the results are visible. Although I would definitely prefer to have a more visual dragging UI over the top of the image, similar to what @lukewalczak built for the custom color picker — this would work as a v1.
