### ISSUE TITLE
[GlobalStep] [Android] While switching the app language to any "Right-to-Left language" (such as Hebrew,Arabic etc), Paragraph, List, Text blocks icon/buttons appear misaligned.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/gutenberg-mobile#2288]
**Environment:**
Android: Samsung Galaxy s9 (v10), Samsung Galaxy S7 (v8), Samsung Galaxy Tab A (v9).
Build WPAndroid [version]: v14.9

**Steps To Reproduce:**
  1. Install and launch the application.
  2. Tap on "Log In".
  3. Log in to the app using valid credentials.
  4. Assuming app language is changed from English say to any one of the RTL languages e.g Arabic.
  5. Go to My site and tap on "Pages" icon.
  6. Go to Drafts and tap on "CREATE A PAGE" button.
  7. Enter any text at title.
  8. Now from footer tap on "+" symbol to add Paragraph, Buttons, List, Text Blocks, Media Text, Columns.
  9. Rotate the device to landscape mode.
  10. Observe that while switching the device from Right-to-Left language; Paragraph, List, Text blocks icon/buttons are not aligned from right-to-left. 

Note: Compared the template with below link
https://github.com/WordPress/gutenberg/pull/21502

**Actual Result:**
While switching the app language to any "Right-to-Left language" (such as Hebrew,Arabic etc). Paragraph, List, Text blocks icon/buttons are misaligned.

**Expected Result:** 
While switching the app language to any "Right-to-Left language" (such as Hebrew,Arabic etc). Paragraph, List, Text blocks icon/buttons are should be properly aligned.

**Attachment:**
[#2288.zip](https://github.com/wordpress-mobile/gutenberg-mobile/files/4663005/2288.zip)

**Comment by designsimply** [comment]
Note: I wrote the testing instruction wrong for this case. It should have said to change the interface language in the app to RTL, not to change the language of the device. I went back through https://github.com/WordPress/gutenberg/pull/21502 and tested after changing the app interface language to Hebrew and everything looks good to me compared to the screenshots in the pull request.

LTR Gallery|LTR MediaText|LTR Paragraph|LTR List
---|---|---|---
![Screenshot_20200522-082201](https://user-images.githubusercontent.com/1119271/82698051-54e25c80-9c27-11ea-8aed-c92b10f43cf1.png)|![Screenshot_20200522-081917](https://user-images.githubusercontent.com/1119271/82698060-590e7a00-9c27-11ea-9a48-aff8bffe58b6.png)|![Screenshot_20200522-082019](https://user-images.githubusercontent.com/1119271/82698059-5875e380-9c27-11ea-8a3b-2772c154e698.png)|![Screenshot_20200522-082123](https://user-images.githubusercontent.com/1119271/82698057-5875e380-9c27-11ea-9e3b-b67a8fd50f8b.png)

<p style="clear:both;"><sup>Tested with WPAndroid 14.9-rc-1 on Pixel 3 Android 10.</sup></p>

Closing as invalid because the test instruction was wrong.
