### ISSUE TITLE
Inconsistence on translating the word "cover" in Portuguese-Brazil.

### ISSUE THREAD

**Issue by gpxlqa** [wordpress-mobile/gutenberg-mobile#2350]
**Describe the bug**
Clicking on icon "+" shows the panel with options. The icon "cover" is translated in the wrong way in Portuguese-Brasil. The correct word is "capa".

**To Reproduce**
1. Go on Create a Post;
2. Click on button "+";
3. Scroll the panel until the icon "cover".

**Expected behavior**
The correct word of "cover" is "capa" in Portuguese-Brazil.

**Smartphone: **
 - Device: SAMSUNG A5 2016
 - OS: Android 7.0

**Comment by maxme** [comment]
I had a look at translations of "cover" in Portuguese-Brazil. I made a suggestion to use "capa" instead of current translation "cobertura".

https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/pt-br/default/?filters%5Bterm%5D=cover&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
