### ISSUE TITLE
Gallery block: allow editing image

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2389]
Let's focus on bringing image editing into Gallery after completing [the work](https://github.com/WordPress/gutenberg/pull/22788) with Media-Text.

**Comment by geriux** [comment]
Hey @iamthomasbishop 👋 

I'm working on adding media editing for Gallery but I'd need some design specifications for the UI of the buttons.

We need to find a place for the Media editing button, the thing is it shouldn't be too different from Image, Media & Text, and [Cover](https://github.com/WordPress/gutenberg/pull/23280) so we reuse as much as we can since all of them share the same Image component. I'm attaching a screenshot of the new button in Gallery, I had to move the remove button so I could show you better. Let me know any ideas/questions you might have.

Functionality wise, the new button will open the options Edit and Replace. Tapping on the image would open the image in full screen.

Current | With Media editing button
-|-
<kbd><img src="https://user-images.githubusercontent.com/4885740/87042141-88873f00-c1f3-11ea-94b8-c89a5c87893c.png" width="250" /></kbd> | <kbd><img src="https://user-images.githubusercontent.com/4885740/87042149-8b822f80-c1f3-11ea-885c-807a941e7ee5.png" width="250" /></kbd>

Thank you!

**Comment by iamthomasbishop** [comment]
@geriux perhaps we should put the 'x' action in the edit menu to conserve some space?

Question: would a long-press on a gallery image cell open the action sheet like we have on image and now cover blocks?

**Comment by geriux** [comment]
> @geriux perhaps we should put the 'x' action in the edit menu to conserve some space?

I moved the delete action, what do you think?

<kdb><img src="https://user-images.githubusercontent.com/4885740/87161324-aa9cc200-c2c4-11ea-96a4-424dacdf2554.gif" /></kdb>

> Question: would a long-press on a gallery image cell open the action sheet like we have on image and now cover blocks?

Yup, I show it in the gif above as well =)

Thanks!

**Comment by iamthomasbishop** [comment]
@geriux I like that! One tiny nitpick: Can we change "delete" to "remove"? Because we are just removing image from the gallery, not deleting it altogether. 😊
