### ISSUE TITLE
Issue when uploading images on Cover Block

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2412]
**Describe the bug**
Testing on Android @jd-alexander had issues adding images on cover block in pages. 

**To Reproduce**
I wasn't able to reproduce this yet, it needs more investigation.

**Expected behavior**
Cover Block should upload the images

**Screenshots**
![cover_block 2020-06-19 17_03_55](https://user-images.githubusercontent.com/3384451/85179406-e0fb9a00-b24e-11ea-8113-332d865e3f02.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL (physical device) & Pixel 3a XL (emulator)
 - OS: Android X
 - Version 29

**Additional context**

**Comment by mkevins** [comment]
Just noting here: I was able to reproduce this with the "Don't keep activities" developer setting enabled, and also for other blocks, but wasn't able to reproduce it with that setting turned off. Also, this is reproducable with other blocks with that setting enabled, at least as far back as: WordPress-Android version 15.0 (though I predict it goes back farther, since I believe this is happening as a result of EditPostActivity not existing when the selected media is returned).

**Comment by hypest** [comment]
👋 @jd-alexander , taking hints from @mkevins response above, is "Don't keep activities" enabled on the the device you were testing with? And, if the issue is reproducible on your side, can you share steps to repro and what's the error message/stacktrace reported in logcat when this happens? Thanks!

**Comment by chipsnyder** [comment]
> I was able to reproduce this with the "Don't keep activities"

@jd-alexander confirmed this as the case for him too. Closing this issue since it seems to be `develop` environment related
