### ISSUE TITLE
Dynamically generation of screenshots for each template

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/gutenberg-mobile#2416]
**Is your feature request related to a problem? Please describe.**

Currently the each device wants to display slightly different sized in preview images. 

Ideally these images would be dynamically generated by passing in the sizes (width and height) to the api.

**Comment by pinarol** [comment]
I don't think we need dynamic generation of screenshots. We can start with having 3 different variations of each thumbnail pre-generated on back end. Mobile client can send the below 2 query parameters inside the request:

- the screen [resolution](https://developer.apple.com/documentation/uikit/uiscreen/1617836-scale) (e.g. 1.0, 2.0, 3.0) (this is for iOS but Android should have something similar)
- the screen size in pixels (width: screenWidth*resolution, height: screenHeight*resolution)

and the server side can choose the correct thumbnail based on these variables. For most of the cases 3 size variations for each screen resolution is enough that's why I said 3 at the beginning. But if we want to do some fine tuning in the future, "screen size in pixels" can be useful as well.

More info about iPhone resolutions: https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions

@chipsnyder Can you confirm if we can make this approach work for Android as well?

**Comment by chipsnyder** [comment]
Yeah, this will work for Android. We can use [densityDpi](https://developer.android.com/reference/android/util/DisplayMetrics#densityDpi) which maps to `DENSITY_LOW`, `DENSITY_MEDIUM`, and `DENSITY_HIGH` we can then just convert this the 1, 2, 3 for the request.

**Comment by pinarol** [comment]
I am curious about how we can generate the different variants of the same thumbnail? Is there a script for that? We prolly need to write a script to produce different variants of the same image.

And we should use that script for all the layouts, not just the mobile ones.

Plus, we should generate them in a specific folder hierarchy and with a name pattern so the backend can use a kind of pattern matching to find them.

similar to:

template-name + @ + resolution + .png

e.g. "about-1@3x.png"

if we want to serve custom sizes for specific resolutions in the future I think we can put them inside a folder named by using the resolution:

E.g.
1242x2688/about-1@1x.png
1242x2688/about-1@2x.png
1242x2688/about-1@3x.png

But I doubt this will be necessary for the first iteration. I think we should still send the resolution though, just in case.

**Comment by enejb** [comment]
I added a scale attribute to the api endpoint that produced different version of the same image. 

This way the smallest possible preview url gets return by the endpoint. 
The url query that you should pass in to the endpoint are `?preview_width=200&scale=1` the width is a pixel value. 

I am hoping this will work as expected for you. 

One thing that I want to explode is creating preview images based on layout. So that we can keep the screenshot updated more easly

**Comment by pinarol** [comment]
> ?preview_width=200&scale=1

Not sure how this works and I doubt the scale on back end side is the same scale on devices side. If it is returning the same sized image with different resolutions then it doesn't look like the solution we'd want.

On iOS:

`?preview_width=200&scale=1` -> Should return 200*1 = 200 width image

`?preview_width=200&scale=2` -> Should return 200*2 = 400 width image. 

and so on.

@chipsnyder I doubt [densityDpi](https://developer.android.com/reference/android/util/DisplayMetrics#densityDpi) will be enough for our needs. When I try to generate Image Sets via https://www.iconcutter.com/ it gives me an output like [this](https://drive.google.com/drive/folders/1hge5KXkAoQ8PH1XSS7X3FWwUfBhGna-W?usp=sharing). I see lots of other different variations under android folder. Ideally we should have the same variants.

**Comment by pinarol** [comment]
> One thing that I want to explode is creating preview images based on layout. So that we can keep the screenshot updated more easly

We should make sure we are doing this transparently and not making the user wait. The preview generation time shouldn't add up to the service response time. I prefer to filter out all layouts that don't have thumbnails over making the user wait. They can be generated at parallel and only when they are ready they can be included in the response.

**Comment by pinarol** [comment]
This looks like the ideal way for Android:

https://developer.android.com/training/multiscreen/screendensities

> To create alternative bitmap drawables for different densities, you should follow the 3:4:6:8:12:16 scaling ratio between the six primary densities. For example, if you have a bitmap drawable that's 48x48 pixels for medium-density screens, all the different sizes should be:
> 
> 36x36 (0.75x) for low-density (ldpi)
> 48x48 (1.0x baseline) for medium-density (mdpi)
> 72x72 (1.5x) for high-density (hdpi)
> 96x96 (2.0x) for extra-high-density (xhdpi)
> 144x144 (3.0x) for extra-extra-high-density (xxhdpi)
> 192x192 (4.0x) for extra-extra-extra-high-density (xxxhdpi)

It seems to me we can still use the "scale" query parameter to send different density values(0.75, 1, 1.5, 2 etc.) for Android. And the returned images should have different sizes accordingly similar with iOS.

**Comment by pinarol** [comment]
If we want to use photon to generate variations I think all the calculations for the image size can happen on client. No need to send the scale to server in this case right?

**Comment by chipsnyder** [comment]
>  When I try to generate Image Sets via https://www.iconcutter.com/ it gives me an output like this. I see lots of other different variations under android folder. Ideally we should have the same variants.(excluding the devices we don't support)

For the image range shown by that link, [density](https://developer.android.com/reference/android/util/DisplayMetrics#density) would be the way to go. This would be more consistent with what we'd want if we were bundling the images in the app.

However, it all depends on our goals and how granular we'd like to get.

> For most of the cases 3 size variations for each screen resolution is enough that's why I said 3 at the beginning

The [densityDpi](https://developer.android.com/reference/android/util/DisplayMetrics#densityDpi) groups the 0.75-4.0 ranges into the same buckets of data (1,2,3) that iOS does so that allows for fewer screenshots that needed to be generated and cached if that's something we monitor. I originally miss read the quote above and thought we were looking for 3 resolutions instead of 3 sizes per resolution.

**Comment by enejb** [comment]
```
On iOS:

?preview_width=200&scale=1 -> Should return 200*1 = 200 width image
?preview_width=200&scale=2 -> Should return 200*2 = 400 width image.

```
This already happends with this images see the API returns the correct image based on the scale and width provided. 

The parameters to use are 
```
preview_width=
scale=
```
The preview width should be be a constant value between the devices and should reflect the desired width of the preview. 
Scale should math the desired density value.

**Comment by pinarol** [comment]
Great, that sounds like it suits well for our case. 

We should keep in mind these things though:

1. 
> The preview generation time shouldn't add up to the service response time

It should be ok if photon creates the different size images on demand but the very first creation of the preview image takes quite some time(up tp 5 secs or so?) and it shouldn't be added to the service response time. 


2. How do we prevent photon's cache from returning us the old image when we want to update the preview? Should we attach a kind of timestamp to the image name?

**Comment by chipsnyder** [comment]
Closing this as this is now supported in the endpoint
