### ISSUE TITLE
Media Blocks: no warning about exceeding the site storage limit and a generic error appears when over disk quota

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/gutenberg-mobile#2448]
Steps to reproduce:

1. For a WordPress.com Free site, go to My Site > Media.
1. Add items until you run out of space.
1. Go to My Site > Blog Posts > +.
1. Add a title and an image block.
1. Upload an image that exceeds the site storage limit.

**Result:** I expected to see a warning about going over storage capacity but a generic error saying "Failed to insert media. Please tap for options." When I tap the image it says, "Retry uploading?" and has options to retry all, remove, or retry and doesn't say anything about the storage limit. ([1m40s](https://cloudup.com/cVgKeLWLPr5))

<img src="https://user-images.githubusercontent.com/1119271/86070420-e9678800-ba39-11ea-8d3f-31e6d435c55f.png" width="33%" alt="image-block-failed-to-insert-media-wpandroid-15 1-rc-2"> <img src="https://user-images.githubusercontent.com/1119271/86070421-ea001e80-ba39-11ea-8535-01f9ed1a661b.png" width="33%" alt="image-block-retry-uploading-wpandroid-15 1-rc-2">

<p style="clear:both;"><sup>Tested with WPAndroid 15.1-rc-2 from the Play Store on Pixel 4 Android 10 on WordPress.com Free site gotravelrewards.blog logged in as testuser0313.</sup></p>

**Comment by hypest** [comment]
👋 Sheri!

> Add items until you run out of space

Is there some message displayed when you reach that limit while in the Media Library?

**Comment by designsimply** [comment]
Yes, when you reach the storage limit in WPAndroid a persistent notice is displayed at the bottom of the Media screen and a popup notice is displayed after trying to upload an item that goes beyond storage capacity. Note: there is an open request to improve the "EXCEEDS_SITE_SPACE_QUOTA_LIMIT" error message shown after an upload is attempted when the storage limit has been reached at https://github.com/wordpress-mobile/WordPress-Android/issues/12325 (also see internal reference: paaHJt-17e-p2#comment-2413).

> 100% of 3 GB used

> 30 files not uploaded
> EXCEEDS_SITE_SPACE_QUOTA_LIMIT

<img src="https://user-images.githubusercontent.com/1119271/86262346-fe006900-bb7c-11ea-8478-2ce4d6cf42db.png" width="33%" alt="100-percent-of-3-gb-used"> <img src="https://user-images.githubusercontent.com/1119271/86262348-fe98ff80-bb7c-11ea-9d8e-576348f2931d.png" width="33%" alt="exceeds_site_space_quota_limit">

When you reach the storage limit in WPiOS, a generic error is shown after uploading an image past storage capacity (left) and a better error is shown after tapping on the failed image upload (right). Note: a request has been filed to ask for the initial message to be shown sooner at https://github.com/wordpress-mobile/WordPress-iOS/issues/14397.

> 1 post, 1 file not uploaded

> Not enough space to upload
> 100% of 3 GB used on your site

<img src="https://user-images.githubusercontent.com/1119271/86262625-5df70f80-bb7d-11ea-90a2-4470dd475036.png" width="33%" alt="1-post-1-file-not-uploaded-media-library-wpios-15 1 0 3"> <img src="https://user-images.githubusercontent.com/1119271/86262640-62232d00-bb7d-11ea-8cf3-4b39b4195561.png" width="33%" alt="1-post-1-file-not-uploaded-media-library-after-tapping-retry-wpios-15 1 0 3 png">

**Comment by SiobhyB** [comment]
👋 @iamthomasbishop, I'm currently working on improving the overlay that displays in the image block when this error occurs and wanted to check-in for feedback on the design. At the moment, I've only added the reason for the failure between the "heading" about the failed upload and the prompt to tap the block for more options:

| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/154537150-a0de4d9e-a2a7-403c-880d-150a3c464066.png" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/154537693-105cdc3b-fc46-4212-9004-9011b8ab568c.png" width="100%"> |

Note, the reason for the failure may not always be available, in which case the version of the error in the "before" screenshot will be used. 

Is there anything you think should be changed in regards to the appearance here? Looking forward to hearing any thoughts or iterations!

**Comment by iamthomasbishop** [comment]
@SiobhyB Thanks for the ping! I think it'd probably make sense to handle this the same way as the Media Library, which places the error message in the subsequent ActionSheet (presumably in the form of a BottomSheet on Android). If we do that, we can probably also refine the UI copy a little bit to something like "Tap for more info." Here's what that would look like all together: 

<a href="https://user-images.githubusercontent.com/1200432/154545233-337af973-4e4c-47d0-bba5-bba7887b36c0.jpeg"><img src="https://user-images.githubusercontent.com/1200432/154545233-337af973-4e4c-47d0-bba5-bba7887b36c0.jpeg" width="600"></a>

Can we also center the text label on the block message ("Failed to insert media...")? Hadn't noticed that before because the first and second rows of text are almost exactly the same length 😄

**Comment by SiobhyB** [comment]
@iamthomasbishop, there have been improvements that add the error to the action sheet since this issue was created. The current set up seems it's already in alignment with the route you're suggesting:  

| iOS  | Android |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/154546567-2b8e7489-db10-43ce-88fa-24c28ee92f80.png" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/154548491-40071d85-d51c-45b1-969f-b249cd469605.png" width="100%"> |

Separate from this, there's also the following open issue about iterating on the overlay message here, which is what I've been looking into: https://github.com/wordpress-mobile/WordPress-Android/issues/13815 

It sounds like the current set up (with the error only displaying in the action sheet) is preferable to the proposal to add the error to the overlay message. Is that right? If so, I can close that Android issue (as well as this one) and address the other tweaks you suggested separately.

**Comment by iamthomasbishop** [comment]
> there have been improvements that add the error to the action sheet since this issue was created

@SiobhyB Ahh, that's right, my bad!

> It sounds like the current set up (with the error only displaying in the action sheet) is preferable to the proposal to add the error to the overlay message. Is that right? 

I think so. IMO, it makes more sense to defer the more verbose messaging to the ActionSheet/Dialog, provided the label on the overlay is phrased clearly enough.

> I can close that Android issue (as well as this one) and address the other tweaks you suggested separately.

Sounds good and thank you! 🙇

**Comment by SiobhyB** [comment]
Perfect, I'll go ahead to close this issue, as there are now appropriate warnings when a site's storage limit has been hit and will address the tweaks you've suggested to the error message in https://github.com/WordPress/gutenberg/pull/38951.
