### ISSUE TITLE
Add Layout Grid - 1st iteration: Read only version

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/gutenberg-mobile#2531]
What we are aiming on this iteration is rendering the grid correctly on mobile in different content size options but not yet allowing the users to change settings.

There will be a [separate effort](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2516) to decide for which sites we should enable this block on mobile.

@enejb After making an initial investigation please drop a comment explaining how you'll approach developing this, what your sub-tasks will look like. Thanks!

@iamthomasbishop We need some directions about UX, we are planning to start working on this ~Aug 10-13. So the sooner we can clarify somethings the more efficient our work will be. Thanks!

**Comment by enejb** [comment]
The approach I am planning to take is 

 

1. Add block availability data to the editor. So that we can be more confident if a block supports is supported in the editor.
2. Add the https://github.com/Automattic/block-experiments/ to the mobile-gutenberg
3. Register the block behind dev flag
4. Render the block correctly according to UX specs. Develop the block in the sample app, but test the block in the main apps before asking for code review. Create WPiOS and WPAndroid PRs for testing purposes
6. Add the ability to modify the layout block.

**Comment by iamthomasbishop** [comment]
@pinarol @enej thanks for starting the conversation! I'm excited to be working on this. I have been chipping away at this over the last week or so and in the process of wrapping my head around the block and its capabilities, I ended up exploring well beyond "read-only". With that said, I've got a bunch more notes and mockups to share, but I've condensed in order to focus on what I think we can do for a first (read-only) version.

As far as I understand, **the goal for v1 is to ensure *existing* *Layout Grid blocks* can be displayed properly on the canvas** — aka "read-only". We aren't yet going to add any settings or editing capabilities to the grid containers, nor are we going to introduce this block in the block library/via the inserter (yet). Users *will* be able to edit child blocks *within* the columns, just not the settings for Layout Grid and its child Column blocks.

S*ide note: For what it's worth, once we do expand beyond a read-only v1, I don't see any huge red flags or things to avoid in terms of editing/customizing the block because we have most of the controls that I think will be required. I don't expect that we'll want or need to diverge from this block very much, so that's good future news.*

## User Requirements

For this first version, we can scope way down to the following requirements/capabilities. The user can:

- View the block on the canvas
- Change block alignment using the button on the block toolbar ("full-width" or no alignment)
- Preview the layout on different device-sizes using the button on the block toolbar (this warrants further discussion, bc I'm unsure how big of a tech. challenge this would be)

## Block Toolbar

The block toolbar on the web is very minimal, with only 2 options — an alignment control and a device-size control. I think we can probably include alignment assuming the full-width block alignments project is complete by the time we are done with this.

I am on the fence about the device-size preview control, mainly because I'm uncertain how difficult this will be to build. If it's relatively straight forward, I think we should include it. However if it's a large challenge, I think for this version we could utilize our existing breakpoints used for other blocks such as Columns.

## Grid, Spans & Sizing Units

This seems like it will be the bulk of the work, but the good news is that I don't think there's a need to diverge from how grids, spans, and gutters as a whole work on the web. It's a pretty straight forward approach that should translate well to mobile.

### Grid

- Desktop layout is always based on a **12-span grid**
- Tablet layout is always based on an **8-span grid**
- Mobile layout is always based on a **4-span grid**

In practice, here is how each columned layout is applied on mobile, tablet, and desktop accordingly:

<a href="https://user-images.githubusercontent.com/1200432/90831141-b094b280-e308-11ea-9a43-3b4bd0c9bed7.jpeg"><img src="https://user-images.githubusercontent.com/1200432/90831141-b094b280-e308-11ea-9a43-3b4bd0c9bed7.jpeg" width="1000"></a>

A few things worth noting:

- Columns always stack on mobile
- Tablet displays a max of 2 columns per row
- Odd-column count pushes a single column to a new row and spans the full width
- Desktop always presents columns in a single row

### Sizing Units

Gutter and column padding sizes use the following sizing scale on the web, which I think we can follow (other than 1 question I have in the "questions" section at the end of this post):

- Small: 8px
- Medium: 16px
- Large: 24px (default)
- Huge: 48px

## Margins & End Gutters

Our block boundaries are slightly different from the web, which might make things slightly trickier  but I'm hoping the work currently being done by @geriux on full/wide-width block alignments will set us up well. For a quick reference, here is a simplified version of what our current block anatomy looks like:

<a href="https://user-images.githubusercontent.com/1200432/90831381-30228180-e309-11ea-9116-ab55c7370a55.png"><img src="https://user-images.githubusercontent.com/1200432/90831381-30228180-e309-11ea-9116-ab55c7370a55.png" width="400"></a>

- **Block "wrapper"**: has 3px of margin on left/right
- **Inner container**: provides 12px of padding and a 1px outer border — this is the outline that is shown when a block is selected
- **Block content**: the boundaries of the block's contents

**End Gutters**

If `show end gutters` ==`false`, the first and last columns should display flush against the left and right of the screen. Considering the distance between the left/right edges of the block wrapper and contents is always `16px`, in order to align the content with the edges, we need to set left/right margins to `-16px`.  

Conversely, if `show end gutters` == `true`, we need to simply apply the appropriate padding on the left/right of the block so that the contents align to the desired spacing/keyline. With our 16px boundaries in mind, the formula should look like this:

> `z` = `x` - `y`

> `z` = Applied block margins

> `x` = Gutter size

> `y` = Content margin (16px)

## Device-Size Preview (if in scope)

On the web, the default for the device-size preview (segmented control) is Desktop. This works if you're on, well, a desktop machine, but feels counter-intuitive if you're on a tablet or phone. If possible, I think we should **default to the relevant size based on the user's current viewport**. For example: when I view the block on a phone in portrait mode, I would expect the control to default to the "Mobile" segment, whereas on a tablet I expect "Tablet", and so on for larger. We might run into some gray areas WRT breakpoints, but anything we can do here to make it more intuitive would be nice.

## Flow

If we're to use the scope mentioned above, the flow is pretty straight forward. Here is a blueprint of the interactions between the parent/child, and how the device-size preview would work.

<a href="https://user-images.githubusercontent.com/1200432/90831470-6102b680-e309-11ea-8d85-4bc7e64e7985.jpeg"><img src="https://user-images.githubusercontent.com/1200432/90831470-6102b680-e309-11ea-8d85-4bc7e64e7985.jpeg" width="1000"></a>

1. Parent block (Layout Grid) selected
    - Layout defaults to the size of the current device (in this case, "mobile" aka stacked layout)
    - Alignment and device-size controls in the block toolbar
    - No block settings entry point
2. ActionSheet (BottomSheet on Android) to pick device-size 
    - Description of the sheet could be something along the lines of "view layout grid as:", "view layout composition for:", etc.
    - Options for Desktop, Tablet, and Mobile
    - iOS (ActionSheet) would include a Dismiss option (BottomSheet on Android omits the cancel/dismiss option)
3. Switched to 'desktop view': The layout composition is forced to display as it would on a large screen. User can tap the device-size control to show the ActionSheet and again switch views
4. Child block (Column) selected (note: I just realized I didn't include the inline appender button -- a big `[ + ]` button -- that would be included when you have the Column block selected)

Note: the device-size picker is only attached to the parent's block toolbar — although it could be useful to include it on the child as well.

## Grid Compositions

Here are some example grids, using a four-column layout grid and various gutter settings:

<a href="https://user-images.githubusercontent.com/1200432/90831234-e8035f00-e308-11ea-9cca-908fac2e2c54.png"><img src="https://user-images.githubusercontent.com/1200432/90831234-e8035f00-e308-11ea-9cca-908fac2e2c54.png" width="1000"></a>

## Feedback

At this time, I'd love to hear feedback on the following:

- Should we include device-size controls in the v1?
- Is there anything else that we should include for the v1?
- Are there any areas that you think diverge too much from the web?
- Are there any areas that you think we should diverge *more* than what I've proposed here?
- Would it be possible and make sense to show a subtle "guide" that visualizes the gutters (only when the parent block is selected)? [Here is a mockup for example](https://cloudup.com/cG4mhTzr-KB)

## Next Steps

- Gather feedback on the proposal and answer open questions
- I'll then pull together some higher-fidelity mocks and a quick prototype if necessary
- Move on to planning and scoping for the next iteration

**Comment by enejb** [comment]
> At this time, I'd love to hear feedback on the following:
> Should we include device-size controls in the v1?

In order to keep things simple I would skip the device-size contols. I think we should try to solve that on the whole editor vs just the block. There are new controls in Gutenberg itself that allow for writers to preview the blocks on different screen sizes. 
I think we should also skip the manipulation of the span and offset values. Mostly since they are also tied to the device-size controls. But if a user can't control them then the why even use this block vs current cloumns block?

This leaves us with :
- align: full width (option) 
- vertical alignment: top, middle, bottom
- add gutter ends: which is a boolean
- gutter size: which is selection.  (huge, large, medium, small, no) 

>Is there anything else that we should include for the v1?
I think for v1 it would be great to include the following. The empty state. Currently when you add the block on the web you get shown placeholder that lets you choose the number of columns. 

See 
<img width="569" alt="Screen Shot 2020-08-28 at 9 32 10 AM" src="https://user-images.githubusercontent.com/115071/91591206-69fb1580-e911-11ea-867d-39a01fb0d025.png">

We could do something similar to the columns block. 

> Are there any areas that you think diverge too much from the web?

It took me a while to understand the Grid Compositions matrix graphic. Mostly because it is the inverse of what I was expecting to see. The gutters are white and the content is red. I think showing the user a background with gutters as i n your example make sense to me :) 

Should we provide a way to add columns and remove columns? That doesn't seem to be possible on the web right now. But it s something that we offer on the column block. 

> Are there any areas that you think we should diverge more than what I've proposed here?

This is for down the road when we have controls that manipulate each column span and offset. But could we have something that is more visual? So that the user understands the decisions that they are making better in the different view contexts (desktop, tablet and mobile)?

> Would it be possible and make sense to show a subtle "guide" that visualizes the gutters (only when the parent block is selected)? Here is a mockup for example

Yes lets go for it! :)

**Comment by iamthomasbishop** [comment]
> In order to keep things simple I would skip the device-size contols. I think we should try to solve that on the whole editor vs just the block.

Agreed, especially WRT solving at the editor vs. block level.

> I think we should also skip the manipulation of the span and offset values. Mostly since they are also tied to the device-size controls. But if a user can't control them then the why even use this block vs current cloumns block?

I was thinking the same thing -- and it sounds like there may be some upcoming efforts to improve or enhance the core Columns block, so we might as well keep this _super_ simple and iterate in the near future if necessary.

> This leaves us with :
> align: full width (option)
> vertical alignment: top, middle, bottom
> add gutter ends: which is a boolean
> gutter size: which is selection. (huge, large, medium, small, no)

All of that makes sense to me, except I have a question regarding vertical-alignment:

> vertical alignment: top, middle, bottom

The Layout Grid block doesn't have support for this on web -- do you think we should add it? (I would be totally fine with enabling this functionality, just wanted to double-check 😄 )

> I think for v1 it would be great to include the following. The empty state. Currently when you add the block on the web you get shown placeholder that lets you choose the number of columns.

Ah, sorry I didn't make this clearer -- our equivalent on mobile (which was included in the most recent Columns block iteration) looks very similar, but is in the form of a bottom sheet that is triggered when adding the block. On the Columns block, it looks like this:

<a href="https://user-images.githubusercontent.com/1200432/92277897-a1416780-eeb9-11ea-9fe8-fc41a89cbf15.jpeg"><img src="https://user-images.githubusercontent.com/1200432/92277897-a1416780-eeb9-11ea-9fe8-fc41a89cbf15.jpeg" width="300"></a>

> Should we provide a way to add columns and remove columns? That doesn't seem to be possible on the web right now. But it s something that we offer on the column block.

I think that would be useful. We might want to establish a max-columns value, though. Perhaps we should stick to the range that the presets provide (1-4)?

> This is for down the road when we have controls that manipulate each column span and offset. But could we have something that is more visual? 

Absolutely! Ideally, I'd love to have visual adjustment controls on the canvas (which I also would love on other block such as Image, Spacer, etc. Let's keep that in mind for the future.

**Comment by chipsnyder** [comment]
Phase 1 of Layout grid was made available as part of https://github.com/wordpress-mobile/gutenberg-mobile/pull/3513
