### ISSUE TITLE
Pressing backspace after styling all text in paragraph deletes text

### ISSUE THREAD

**Issue by mchowning** [wordpress-mobile/gutenberg-mobile#2638]
**Describe the bug**
On Android only, the cursor is placed at the beginning of a paragraph block after styling all the text in the block, and pressing backspace at that point will delete all the text in the paragraph.

**To Reproduce**
1. Create a paragraph block
2. Type some text in the paragraph block, highlight all the text, and apply (or remove) styling (i.e., bold or unbold) to all the text in the block
3. Observe that the text is now styled and the cursor is at the beginning of the paragraph block
4. Tap the backspace key
5. Observe that all the text is removed from the block.

**Expected behavior**
Pressing backspace at the beginning of a block should not delete any text in the block and instead should either do nothing (if it is the first block in the post) or merge the current block into the previous block.

**Screenshots**

<img src="https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fi.gyazo.com%2F6ddfa543b563a9a2504771ae2309399e.gif">

**Smartphone (please complete the following information):**
 - Device: Pixel 3, Pixel 1
 - OS: Android X
 - Version: recreated on both alpha-244 and the (more recent) 4559ca25 commit

**Additional context**
Thanks to @khaykov for reporting this! 🙇

**Comment by hypest** [comment]
Issue is present in older editor versions as well. I tried v13.9 (January 2020) and it's there, but I'm sure it must be older anyway.

Looks like it only happens if you leave the caret at the where the "bolding" action puts it after applied (puts it at the start of the enbolden text). If you move the caret before hitting "backspace" the issue doesn't occur.

I think the "Medium" priority is fair for this one as it happens after some not-so-typical writing flow actions.

**Comment by guarani** [comment]
I couldn't reproduce this on WPAndroid 18.2-rc-3 and I tried using both the Gboard and the Samsung keyboards.

> the cursor is placed at the beginning of a paragraph block after styling all the text in the block

I don't see the cursor being placed at the beginning of the paragraph block when I style all the text in the block. 

> Looks like it only happens if you leave the caret at the where the "bolding" action puts it after applied (puts it at the start of the enbolden text). If you move the caret before hitting "backspace" the issue doesn't occur.

~~This implies that the bug only occurred if the cursor is manually positioned after applying styling. In my tests today, that's required because styling leaves selection handles in place, so I must manually remove selection by tapping at the first text position to place the cursor there.~~ This implies that the bug only occurred if the cursor is _left in place_ after applying styling. In my tests today, _I needed to manually position the cursor_ because styling leaves selection handles in place, so I must manually remove selection by tapping at the first text position to place the cursor there. From there, tapping backspace doesn't cause text to be deleted. From there, tapping backspace doesn't cause text to be deleted.

Here's a video of what I see:

https://user-images.githubusercontent.com/1898325/133682685-44e362ee-3b5e-43cb-b07c-5f4356da52db.mp4

If others can confirm this is no longer reproducible, I think we could close this.

**Comment by mchowning** [comment]
I'm seeing the same thing as you Paul. Thanks for testing this and seeing that we can close it.
