### ISSUE TITLE
Missing Gradient Color Defaults after web change

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/gutenberg-mobile#2649]
**Describe the bug**
After this Gutenberg web update, default colors and gradients no longer exist in settings: https://github.com/WordPress/gutenberg/pull/25419

That change introduced a  mobile crash that was fixed here: https://github.com/WordPress/gutenberg/pull/25519.

However, we are now missing default color and Gradient options in Cover and Buttons blocks on Mobile. 

**To Reproduce**
1. Go to Cover or Buttons Block
2. Select Color or Gradient option
3. Notice defaults are gone

**Expected behavior**
We should have default options

| Missing Defaults  | Expected |
| ------------- | ------------- |
| ![Screenshot_20200921-143517_WordPress Beta](https://user-images.githubusercontent.com/1103838/93824595-90faed80-fc18-11ea-9555-20cea40450bd.jpg)  | ![Screenshot_20200921-143714_WordPress Pre-Alpha](https://user-images.githubusercontent.com/1103838/93824611-98ba9200-fc18-11ea-8b82-8af621512511.jpg)  |

**Comment by guarani** [comment]
I understand the fix in https://github.com/WordPress/gutenberg/pull/25519 is only temporary, and we plan on addressing this issue before the next release. I noticed a couple of things just now though, and want to document them for completeness:

1. The color picker is sometimes shown without the Cancel and Apply buttons. 

    <details>
    <summary>See screen recording</summary>
    <table><tr><td><img width="300" alt="Screen recording showing color palette missing Apply and Cancel buttons" src="https://user-images.githubusercontent.com/1898325/93826303-ee049c80-fc34-11ea-9431-62e4568795f8.gif"></tr></td></table>
    </details>
2. If you choose a solid custom color, then switch back and forth between Solid and Gradient, the Solid/Gradient toggle suddenly disappears. I confirmed this bug is a side-affect of the lack of default colors and gradients. When this issue is fixed I'm sure this bug will fix itself as well though.

    <details>
    <summary>See screen recording</summary>
    <table><tr><td><img width="300" alt="Screen recording showing Gradient/Solid buttons missing" src="https://user-images.githubusercontent.com/1898325/93826590-8f8bee00-fc35-11ea-88fe-0f929090a7fb.gif"></tr></td></table>
    </details>

**Comment by enejb** [comment]
I created a PR that adds back the default colour back in https://github.com/WordPress/gutenberg/pull/25523 

I am still seeing on iOS that the default text doesn't show up. I am not sure how to debug this yet. 
I am also still seeing the cancel and apply buttons disappearing when using using the custom color settings.
