### ISSUE TITLE
Rotating the device after editing causes the editor to crash

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2681]
**Describe the bug**
Rotating the device after editing a field in the editor causes the editor to crash

**To Reproduce**

1. Create a new Post or Page
1. Make an edit like typing into a paragraph block
1. Rotate the device 
💥 (might need to rotate couple times)

**Expected behavior**
The editor should adjust to landscape mode.

**Screenshots**

<kbd>
<img src="https://user-images.githubusercontent.com/3384451/94613676-f8491b00-0272-11eb-9507-3a7a5d444875.gif" />
</kbd>

**Smartphone (please complete the following information):**

Each of these branches are the current `HEAD` of `develop` at the time of opening
`gutenberg` `ed848a0ac49257c1c8162fef09440a36c48a8375`
`gutenberg-mobile` `3b58aa6f5938873345e31cd5f61bcca33b84ec1f`

`WPAndroid` `bbbbba48832e641bc568aaf65a19a6b33c62cf40` (pointed to the Gutenberg commits above)

Android
 - Device: Pixel 3a
 - OS: Android 10
 - Version: 29

**Comment by cameronvoell** [comment]
In the Android log I'm seeing the following crash:
```
09-30 00:51:48.315 30688  4101 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-30 00:51:48.315 30688  4101 E AndroidRuntime: Process: org.wordpress.android.beta, PID: 30688
09-30 00:51:48.315 30688  4101 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: undefined is not a function, js engine: hermes, stack:
09-30 00:51:48.315 30688  4101 E AndroidRuntime: anonymous@180280:33
09-30 00:51:48.315 30688  4101 E AndroidRuntime: apply@-1
09-30 00:51:48.315 30688  4101 E AndroidRuntime: emit@4004:42
09-30 00:51:48.315 30688  4101 E AndroidRuntime: apply@-1
09-30 00:51:48.315 30688  4101 E AndroidRuntime: __callFunction@3370:49
09-30 00:51:48.315 30688  4101 E AndroidRuntime: anonymous@3083:31
09-30 00:51:48.315 30688  4101 E AndroidRuntime: __guard@3324:15
09-30 00:51:48.315 30688  4101 E AndroidRuntime: callFunctionReturnFlushedQueue@3082:21
09-30 00:51:48.315 30688  4101 E AndroidRuntime:
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
09-30 00:51:48.315 30688  4101 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:919)
```

Using `git bisect`, I believe I narrowed down that this bug was introduced in this change: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2484 

@lukewalczak Could you take a look since you were working on that change last? I also added how I narrowed down to that PR below. Also, I used WPAndroid commit c93ffc4d219aa6c2a6006d0697aa2934bb1797f1 on develop for testing PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/2484 which I believe introduced the bug 

WPAndroid git bisect brought me to 836074c19c9c31d83baa186dc6db5e22456ce763, that change updated gb-mobile commit from 93db88 to 3ed3b0, doing another git bisect in gb-mobile from 93db88 to 3ed3b0 brought me to:
ed50a4d3fb1f3bd69c8c92eae8fbb39f4e6e1e83 is the first bad commit
commit ed50a4d3fb1f3bd69c8c92eae8fbb39f4e6e1e83
Date:   Sat Sep 19 00:31:21 2020 +1000
    Link picker via fetch (#2484)

**Comment by cameronvoell** [comment]
Also worth noting I did verify that the bug is not existing in the previous editor release we sent to WPAndroid app - https://github.com/wordpress-mobile/WordPress-Android/pull/12993

**Comment by hypest** [comment]
Looks like the paragraph block needs to be focused with the caret inside) for the crash to happen. Doesn't happen for me if, say, an image block is focused regardless if I have introduced text changes to a paragraph block.

Also, doesn't seem to happen to the gb-mobile demo app.

**Comment by lukewalczak** [comment]
After debugging we discovered that the crash is caused because of missing/ not passed `onClose` to `BottomSheet` within the `ModalLinkUI`. The regression was [introduced](https://github.com/WordPress/gutenberg/pull/23922/files#diff-98dbdad3726f95887e926868d17b1426L154) as a part of `LinkPicker` feature. I was only responsible for merging the PR (plus small final changes), and have no more context why `onClose` was not passed. However that `onClose` function is needed within the `BottomSheet`, specifically in `componentDidMount()` piece of code:

```
		if ( Platform.OS === 'android' ) {
			this.androidModalClosedSubscription = subscribeAndroidModalClosed(
				() => {
					this.props.onClose();
				}
			);
		}
```

I moved it back in the fixing PR :)
