### ISSUE TITLE
[Home Page Picker] A/B Testing a different screen order - Single Platform (TBD)

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#2726]
## Description
As part of the project for adding a Home Page Picker to the site creation flow, we’d like to A/B test the ordering of the steps for site creation. The flows will be:
A. **Choose a design** > Choose a domain > Success
B. Choose a domain > **Choose a design** > Success

📓This will only be needed for a single platform based on whichever is the best candidate

## Goals
- Users in group A will see **Choose a design** > Choose a domain > Success
- Users in group B will see Choose a domain > **Choose a design** > Success

## Additional context

📓Updated designs will come later than what is currently linked here.
<details>
<summary>Design i1</summary>
<img src="https://user-images.githubusercontent.com/3384451/95901257-0e6dd580-0d61-11eb-8775-9a15bbfd33b9.png"/>
</details>

**Comment by antonis** [comment]
Hello @kyleaparker @iamthomasbishop 👋 
Choosing a domain first (option B) would require changing the action buttons of the screens. A straight forward approach for this can be:
* Domain Screen: *Create Site* => *Choose*
* Design Screen: *Choose* => *Create Site*
* Design Screen: *Skip*: Should we leave skip as is or change it since the action will trigger site creation ([similar to this](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2828#issuecomment-744606544))
Wdyt?

|Design Screen|Domain Screen|
|---|---|
|![device-2020-12-14-200348](https://user-images.githubusercontent.com/304044/102117859-86cb4280-3e47-11eb-974b-96f846c3a23c.png)|![device-2020-12-14-200328](https://user-images.githubusercontent.com/304044/102117872-8df25080-3e47-11eb-9e1d-7f7447f52a20.png)|

**Comment by kyleaparker** [comment]
Another option would be to change both _Choose_ and _Create site_ with _Continue_ . Then the action is always the same and I don't think it really matters that it doesn't explicitly say "Create site". What do you think @iamthomasbishop ?

**Comment by iamthomasbishop** [comment]
> Another option would be to change both Choose and Create site with Continue .

@kyleaparker I think that'd work great!

**Comment by chipsnyder** [comment]
I'm going to close this issue out since we have a more extensive version of site creation in the works
