### ISSUE TITLE
Gallery: Can't change the gallery image size. 

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/gutenberg-mobile#2880]
**Describe the bug**
When I am in the gallery block settings. I am not able to update the image size setting.

**To Reproduce**
1. Insert the gallery block. 
2. Add a few images to the block. 
3. Open up the gallery settings. 
4. Notice that after selecting the gallery image size. That the UI doesn't get updated.

**Expected behavior**
I expected to be able to change the gallery size via the settings UI.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro, Samsung A8
 - OS: iOS,  Android

**Comment by guarani** [comment]
> When I am in the gallery block settings. I am not able to update the image size setting.

When I change the "Image size" setting, the images themselves do appear to change in the editor (best seen when changing to the Thumbnail size). However, the label to the right of "Image size" does not update to reflect the selected size.

Also, when publishing the post from the app, I do see some change in size between Thumbnail and "Full Size", but it's not significant.

I also noticed that this issue is present on the web:

| <img src="https://user-images.githubusercontent.com/1898325/101672293-74f73300-3a34-11eb-9076-02dc291197c4.gif" alt="Screen recording showing the same image size setting broken on the web" width="350">  |
| - |

Finally, noting that I can reproduce this in 16.2 so it's not a new regression.

**Comment by guarani** [comment]
> Also, when publishing the post from the app, I do see some change in size between Thumbnail and "Full Size", but it's not significant.

Testing again with WPiOS 16.2, I see that the URLs of the images in the final published post does change when I switch image size:
- Thumbnail: https://pschrottkyicloud.files.wordpress.com/2020/12/img_9817.jpg?w=300
- Medium: https://pschrottkyicloud.files.wordpress.com/2020/12/img_9817.jpg?w=600
- Large or "Full Size": https://pschrottkyicloud.files.wordpress.com/2020/12/img_9817.jpg

So I think this is working (in 16.2) in the final published post, it's just not too noticeable. The issue with the editor UI not showing the selected size is of course still an issue. I haven't tested 16.3 or the 16.3 (gutenberg mobile 1.43.0) versions, but I'm reasonably sure it's the same situation there as well.

**Comment by Gustavo-Hilario** [comment]
A user reported this issue here: 5211171-zen

I have also filled out a similar bug report about this on Automattic/wp-calypso/issues/59372

This seems to be affecting multiple blocks with images where the option `Image Size` isn't doing anything but reducing the image quality. I think we should reopen and investigate this further.
