### ISSUE TITLE
[Home Page Picker] Add a sample URL to the Choose a Domain Screen

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/gutenberg-mobile#3019]
**Is your feature request related to a problem? Please describe.**
As part of our recent site creation empathy challenge @geriux mentioned it would be nice to include a sample URL to our "Choose a Domain" screen. The web has something similar:

<kbd><a href="https://user-images.githubusercontent.com/3384451/104966150-326b3380-59ae-11eb-909b-b862b0569582.png"><img width="500" src="https://user-images.githubusercontent.com/3384451/104966150-326b3380-59ae-11eb-909b-b862b0569582.png"/></a></kbd>

**Describe the solution you'd like**
We could either add this as part of the prompt text or design a similar UI 🤷‍♂️ 

@iamthomasbishop @kyleaparker What are your thoughts?

**Comment by iamthomasbishop** [comment]
@chipsnyder I think we do already show the browser frame on the final step of the site creation flow, so perhaps we could add that on the domain selection step. Theoretically, we could position the text input so that it appears "inside" the device frame or bump the browser frame downward a bit below the domain search input (and fade it out or change its form once the search results start coming in). I think it'd be be tricky to make the transition to the next step of the flow feel natural, but not insurmountable.

@kyleaparker, do you have any thoughts or ideas?

**Comment by iamthomasbishop** [comment]
I misread the original proposal @chipsnyder 😆 What you proposed is a bit simpler, and my mind took it to a more dynamic thing where when you type in the input, the placeholder text would become what you typed. What you were asking for would be more straight forward, just the frame of the browser w/ `https://example.com` in it, but regardless what I mentioned about the transition might still be a bit tricky. 😃

**Comment by kyleaparker** [comment]
Do you mean we could change the "Search domains" placeholder text to a sample domain instead? I think that could work 👍

**Comment by chipsnyder** [comment]
Yeah I think a really quick/simple change would be to change `Search Domains` to `https://example.com` or change the prompt from `This is where people will find you on the internet.` to something like:
`This is where people will find you on the internet. Like https://example.com`

**Comment by kyleaparker** [comment]
Do we know people are confused or unsure what to search on this screen?

I think the prompt becomes a bit too long and complicated if try to include it there. My preference would be to change the placeholder but I do like that it includes the action right now telling people what to do.

**Comment by chipsnyder** [comment]
> Do we know people are confused or unsure what to search on this screen?

The only touch point I have is It was something that came out of the recent site creation empathy challenge. A relative doing the exercise asked "what's a domain?"

**Comment by kyleaparker** [comment]
A couple of ideas: 

Update the placeholder text so that it's more relatable and prompts people to search: 
![Domains 2](https://user-images.githubusercontent.com/712873/105494615-0ccd7b00-5c89-11eb-8b5d-b943edb8a644.png)

Include an illustration in the empty space to help explain the concept of domains: 
![Domains 1](https://user-images.githubusercontent.com/712873/105495793-9467b980-5c8a-11eb-9994-12803c04754e.png)

I think the first option is probably enough to prompt people to start searching, they will then start to see domain names immediately. What are your thoughts @iamthomasbishop ?

**Comment by iamthomasbishop** [comment]
@kyleaparker I like aspects of both of your examples. I like the copy in the first example, and prefer the second one visually. On the second, I wonder if we can either re-use the browser frame from the last step of the site creation flow or make the mock browser window taller to make it look more like a phone’s aspect ratio in portrait-mode? (obviously that’d mean it’s partially out-of-viewport bc the keyboard would be over it, but that’s fine)

**Comment by kyleaparker** [comment]
Here are a couple of options. The browser frame matches the one on the last step of the flow. The third option includes the drop shadow (it's not quite right, I'd need to get the correct values if we want to include this)

<img width="1211" alt="Screen Shot 2021-01-27 at 1 07 37 PM" src="https://user-images.githubusercontent.com/712873/106034333-ca4cd980-60a0-11eb-8a81-cca335fe3c72.png">

I prefer either the first or second one, the shadow feels a little heavy in this context.

**Comment by iamthomasbishop** [comment]
@kyleaparker Awesome! Very much a personal opinions below, but I prefer the second because of the skeleton UI — nice subtle detail. I don't dislike the third one either, and agree the shadow is a bit strong but I think it could work if we were to reduce the opacity on the shadow to a very low value — just enough that it's visible but not strong. 

One other thing, it also be worth rounding the corners of the browser frame to go with the rounded corners of the address bar input? But again, all personal preference, this looks great as-is!

**Comment by kyleaparker** [comment]
I've gone ahead and rounded the corners and added a more subtle shadow to the second option: 

<img width="957" alt="Screen Shot 2021-01-29 at 8 03 37 AM" src="https://user-images.githubusercontent.com/712873/106278341-9260a600-6208-11eb-899c-40a028ffb5aa.png">

I proposed some updates to the [site created screen](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3053) which should be consistent with whichever option we choose for this. 

My preference right now is the flat layout, it feels like a better fit with the UI but it's subjective and I'd be ok with either.

**Comment by iamthomasbishop** [comment]
Sounds good @kyleaparker, let's roll with that! Nice work!
