### ISSUE TITLE
Switching from Solid to Gradient doesn't scroll to end when having customised gradient

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#3104]
**Describe the bug**
Related to test case: [Color Settings - Test Cases - TC003 - Scroll color palette to the end](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/color-settings.md#scroll-color-palette-to-the-end).

When having a customised gradient, switching from Solid to Gradient doesn't scroll the colors list to the end.

**To Reproduce**
1. Go to a post/page
2. Add `Buttons` block
3. Tap on gear button
4. Tap on `Background color` option
5. Tap on `Gradient` option
6. Tap one gradient color
7. Tap on `Customize Gradient`
8. Change `Gradient Type` to `Radial` (it also works changing other options)
9. Tap on back arrow button
10. Tap on `Solid` option
11. Tap on `Gradient` option again
12. Observe that the scroll doesn't go to the end where the custom gradient is shown

**Expected behavior**
The scroll should go to to the end showing the custom gradient color when switching between Solid and Gradient options.

**Screenshots**

https://user-images.githubusercontent.com/14905380/106886020-b417cc80-66e3-11eb-97ad-71cb90db8656.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android 10
 - Version 16.5

**Comment by chipsnyder** [comment]
Related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2882

**Comment by dcalhoun** [comment]
@chipsnyder @fluiddot I have found that **_the "Custom" button is now no longer displayed at all when customizing the gradient_**, in addition to not scrolling to the end. I was about to create a new issue, but then found this one. Happy to create a separate issue if that is more appropriate. 

<details>
<summary>Details of missing "Custom" button issue</summary>

## Description
When customizing the gradient of a block, the color list does not add the "Custom" button to the end of the color list. It also does not remove the "Custom" button when switching from a customized gradient to a predefined gradient. This was found in the steps within the [GB Mobile TC005 color settings test case](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/color-settings.md#tc005). 

## Step-by-step reproduction instructions
1. Launch block editor on WPiOS or WPAndroid. 
2. Add a Button block. 
3. Open Button block settings. 
4. Tap Background Color. 
5. Tap Gradient. 
6. Select a gradient. 
7. Tap Customize Gradient. 
8. Tap Radial. 
9. Tab back arrow. 

## Expected behaviour
The horizontal list of gradients is scrolled to the end to reveal a "Custom" button. Switching to a predefined gradient animates removing the "Custom" button. 

## Actual behaviour
A "Custom" button is never added or removed. 

## Screenshots or screen recording (optional)
https://user-images.githubusercontent.com/438664/114904769-d01fa480-9ddd-11eb-9363-9a754210eada.MP4

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v10.3.2-with-autocomplete-perf-fix
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: iPhone SE
- Operating system: iOS 14.4.2
- WordPress app version: 16.9

</details>

**Comment by chipsnyder** [comment]
Thank you for adding more details @dcalhoun! I think keeping this in one issue is the best way to go.

**Comment by antonis** [comment]
Fixed with https://github.com/WordPress/gutenberg/pull/30994
