### ISSUE TITLE
[Analytics] Sessions reporting having unsupported blocks differ a lot between Android and iOS

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#3228]
I took a look at the number of editor sessions that report having unsupported blocks and looks like there's a huge difference between Android and iOS, to the degree that doesn't make sense to me on first look, hinting to a possible bug at reporting.

Here's a short capture of the data on a weekly basis:

Week (2021) | Session counts Android | With unsupported Android | | Session count iOS | With unsupported iOS
-|-|-|-|-|-
March 01 | 833,175 | 27,387||606,674 | 79
February 22 | 795,269 | 26,509||522,920 | 108
February 15 | 768,914 | 27,349||496,394 | 121
February 08 | 762,708 | 27,480||471,946 | 101

The "with unsupported block" sessions on iOS are 2 orders of magnitude lower than Androids, while Android's sessions seem to hover around 3% of sessions having unsupported blocks. Without looking further into the data, the 3% feels quite natural to me, so I wonder if the iOS reports are undercounted.

**Comment by mchowning** [comment]
@guarani is planning to take a look at this soon.

**Comment by guarani** [comment]
The issue here was that events were being rejected by Tracks because they were malformed. The `editor_session_start` has both a `has_unsupported_blocks` and a `unsupported_blocks` custom event properties. `unsupported_blocks`, which is a list of unsupported blocks, was not being stringified on WPiOS before being sent to the backend, causing these events to be discarded.

The backend doesn't allow for custom event properties of complex types such as arrays or objects. From what I can tell, what the WPAndroid tracks library does is convert any lists to strings before sending them to the backend, so that's why this bug wasn't present there.

`editor_session_start` isn't affected by this bug because it does not include the `unsupported_blocks` event property.

---

The easiest solution is to stringify `unsupported_blocks` explicitly. There is a chance there are other events being rejected because of problems similar to this, so we could fix this issue here first, then look at updating the Automattic-Tracks-iOS library to handle this transparently, similar to how I think Android does it.

**Comment by guarani** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/16360 is merged and this is now fixed.
