### ISSUE TITLE
Arbitrary link added when inserting media from library

### ISSUE THREAD

**Issue by ashleyleia** [wordpress-mobile/gutenberg-mobile#3234]
When adding an image to a draft post from the Wordpress media library, an arbitrary link is attached to the image.  In particular, the app is adding a link to a Youtube video that I have embedded elsewhere on my site.

This is consistent across multiple images and multiple draft posts.  Tested on iPhone 8, iOS 14.4, WPiOS 16.7.1.

![IMG_2645](https://user-images.githubusercontent.com/77593027/110342434-3dbb0280-7fe0-11eb-9b09-a60c5b95749e.PNG)

**Comment by hypest** [comment]
Thanks for reporting @ashleyleia !

I think what happens there is that the URL (to a YouTube video in this case) happens to be in the clipboard and is picked up automatically by the image block. I replicated the issue on WPiOS v16.8 on my end.

Steps to reproduce:
1. Go to a browser on the device visit a site and copy its URL
2. Return to WPiOS, create a new post and add a new image block
3. Select an image from the media library
4. Open the block settings (cog wheel icon) and notice that the "Link to" field is already populated with the URL from the clipboard 💥

Auto-filling URLs is a feature in some cases ([like this one](https://github.com/wordpress-mobile/gutenberg-mobile/issues/680)) but looks like an issue here since the user flow does not involve an explicit attempt to set the link.

To investigate, 👋 @chipsnyder , can this perhaps be a regression from [this Button PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1958) that involves auto-filling?

In the meantime, I'll move this ticket to the gutenberg-mobile repo where we keep tickets specifically about the native mobile block editor.

**Comment by chipsnyder** [comment]
Yes, thank you for calling this out. It does seem to be related to that fix and we should only be setting the text when taking the explicit action of opening the link settings. I'll get this in the pipeline to fix.

**Comment by KokkieH** [comment]
We've had another report of this in https://wordpress.com/forums/topic/unwanted-links-5/

Noting I'm able to replicate it on WP Android 17.2-rc-3 as well.

**Comment by antonis** [comment]
This is resolved along with https://github.com/wordpress-mobile/gutenberg-mobile/issues/4058. Please reopen if that is not the case.
