### ISSUE TITLE
[Embed block] Detect when an embeddable URL is pasted into an empty paragraph

### ISSUE THREAD

**Issue by ceyhun** [wordpress-mobile/gutenberg-mobile#3280]
### Description
- Detect when an embeddable URL is pasted into an empty paragraph (including a paragraph inside a Media & Text block)
- Trigger a bottom sheet to open when a paste is detected (bottom sheet functions will be implemented in another issue)
- Should not to trigger when pasting in the middle of a text

### Screenshot
<img width="300" src="https://user-images.githubusercontent.com/1845482/111492441-f4d02000-873c-11eb-9950-9e21d33c1459.png">

**Comment by jd-alexander** [comment]
Hi @fluiddot So I started working on this task. I haven't created a PR as yet but so far this is where my exploration has led me. 

### Web 

On the web, it seems that embeddable URLs are detected within the `Paragraph` blocks via the `RichText` component and then converted to an Embed block. The mechanisms for this detection are as follows: 

1. The `RichText` component is passed a prop of [__unstableEmbedURLOnPaste](https://github.com/WordPress/gutenberg/blob/8013882db7c0e118136f7bb0196243c472d40334/packages/block-library/src/paragraph/edit.js#L141) . 

2. Internally, the `RichText` component utilizes a [PasteHandler](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/index.js#L349)
that sanitizes the input and decides how the handler should go about transforming the content. In this case, the content should be transformed into an Embed block. 

3. I can see where `onReplace` is called with `content` generated from the `PasteHandler`. However, I wasn't able to replicate the functionality from a debugging standpoint because when I spun up a test instance of Gutenberg, I was getting a version of the script that was minified so I wasn't able to step through with the debugger to follow the path to block creation. 

`SCRIPT_DEBUG` is set to true within the instance but I still was getting minified content. Let me know if you have been able to successfully traverse the Gutenberg sources when deployed via `wp-env start`. 

## Mobile 

1. The `Paragraph` and `RichText` blocks behave similarly to the web. The main caveat here is the `RichText` component on mobile, went on a different path after being separated from the web version so the usage of the `PasteHandler` differs. What I noticed was when a URL was pasted the content was just being set within the paragraph block but no Embed block was being created even though `__unstableEmbedURLOnPaste` was being added as a prop below this [prop](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph/edit.native.js#L85).

2. Is it that I need to utilize some form of transforms mechanism to get this working as expected? 

3. Also from an implementation standpoint, I am realizing that our implementation differs from the web because we show a bottomsheet when we detect a URL. Therefore, I was wondering if we would need to create some form of interceptor logic within the [onPaste](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/rich-text/index.native.js#L374) function that would provide a mechanism for us to create the bottom sheet. From a responsibility standpoint, should the `RichText` component displays such a bottom sheet here? I was wondering if it would be best to pass in a prop that can be implemented in the Paragraph block to encapsulate the functionality there.

4.  To expound more on the bottom sheet, I was thinking to replicate the bottom sheet functionality utilized in the [EmbedPlaceholder](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/embed/embed-placeholder.native.js#L22) and utilize methods from the utils for the `Create embed` and `Create link`. 

5. `Create embed` would work via some transforms.js mechanism or an Embed block could be created and passed to the `onReplace` function. 

6. `Create link` could leverage the [fallback](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/embed/util.js#L236) function that is within the utils file.

-----

Let me know if you have any thoughts here.  I will be thinking through these ideas more to come up with a solution. Thanks for the help!

**Comment by fluiddot** [comment]
> Let me know if you have been able to successfully traverse the Gutenberg sources when deployed via wp-env start.

I couldn't follow the trace once the execution reaches [this point](https://github.com/WordPress/gutenberg/blob/cddb04629216056789e268e100793c7e30120667/packages/block-editor/src/components/rich-text/use-paste-handler.js#L182-L188) and calls `pasteHandler` 😞 .

> What I noticed was when a URL was pasted the content was just being set within the paragraph block but no Embed block was being created even though __unstableEmbedURLOnPaste was being added as a prop below this prop.

From what I see in the `pasteHandler` logic, I think the magic happens in the [`shortcodeConverter`](https://github.com/WordPress/gutenberg/blob/cddb04629216056789e268e100793c7e30120667/packages/blocks/src/api/raw-handling/paste-handler.js#L156-L158) that relies on the block transformations, so most likely transformations are somehow related to the issue.

I recall that we disabled some transformation in the native version of the embed block ([PR reference](https://github.com/WordPress/gutenberg/pull/33745)), I'd investigate what changes were made because it's probably related.

**Comment by jd-alexander** [comment]
> > Let me know if you have been able to successfully traverse the Gutenberg sources when deployed via wp-env start.
> 
> I couldn't follow the trace once the execution reaches [this point](https://github.com/WordPress/gutenberg/blob/cddb04629216056789e268e100793c7e30120667/packages/block-editor/src/components/rich-text/use-paste-handler.js#L182-L188) and calls `pasteHandler` 😞 .
> 
> > What I noticed was when a URL was pasted the content was just being set within the paragraph block but no Embed block was being created even though __unstableEmbedURLOnPaste was being added as a prop below this prop.
> 
> From what I see in the `pasteHandler` logic, I think the magic happens in the [`shortcodeConverter`](https://github.com/WordPress/gutenberg/blob/cddb04629216056789e268e100793c7e30120667/packages/blocks/src/api/raw-handling/paste-handler.js#L156-L158) that relies on the block transformations, so most likely transformations are somehow related to the issue.
> 
> I recall that we disabled some transformation in the native version of the embed block ([PR reference](https://github.com/WordPress/gutenberg/pull/33745)), I'd investigate what changes were made because it's probably related.

Thanks for these thoughts @fluiddot they were very helpful in filling the gaps in what I had encountered during my exploration. I have a WIP PR here https://github.com/WordPress/gutenberg/pull/35204  I will be cross-referencing this comment for behavior verification and alignment.
