### ISSUE TITLE
[Embed block] Alignment options

### ISSUE THREAD

**Issue by ceyhun** [wordpress-mobile/gutenberg-mobile#3284]
### Description
- Enable alignment options and implement block styling based on selected option

### Screenshot
<img width="300" src="https://user-images.githubusercontent.com/1845482/111494917-29dd7200-873f-11eb-8b2e-123580606939.jpg">

**Comment by fluiddot** [comment]
I verified that the alignment options on the first version work as expected without including any implementation for the native version. However, I wouldn't close the issue because most likely this feature would require to be revisited once we implement the embed preview.

## Results

Here we can see the different alignment results with its preview:

### Align left (Twitter embed)
Editor|Preview
--|--
<img src=https://user-images.githubusercontent.com/14905380/124616016-0bc68980-de76-11eb-8412-b42fbfcf8488.png>|<img src=https://user-images.githubusercontent.com/14905380/124616023-0cf7b680-de76-11eb-9bd1-d9c14d01b6ab.png>

### Align center (Tik Tok embed)
Editor|Preview
--|--
<img src=https://user-images.githubusercontent.com/14905380/124616208-2d277580-de76-11eb-8b31-8e55d2fbd41c.png>|<img src=https://user-images.githubusercontent.com/14905380/124616217-2e58a280-de76-11eb-952f-334ae6fb3adb.png>

### Align right (Tumblr embed)
Editor|Preview
--|--
<img src=https://user-images.githubusercontent.com/14905380/124616253-36b0dd80-de76-11eb-8f3c-6f5b54f8b19a.png>|<img src=https://user-images.githubusercontent.com/14905380/124616260-37e20a80-de76-11eb-904c-a6c4dfc9943c.png>

### Wide width (YouTube embed)
Editor|Preview
--|--
<img src=https://user-images.githubusercontent.com/14905380/124616297-40d2dc00-de76-11eb-8320-bc7b8e33bb4a.png>|<img src=https://user-images.githubusercontent.com/14905380/124616301-42040900-de76-11eb-8a83-185818ddfaa3.png>

### Full width (Spotify embed)
Editor|Preview
--|--
<img src=https://user-images.githubusercontent.com/14905380/124616344-49c3ad80-de76-11eb-8f5c-7fa7eeb82d0e.png>|<img src=https://user-images.githubusercontent.com/14905380/124616350-4a5c4400-de76-11eb-8194-a902634d4ab7.png>
