### ISSUE TITLE
Support @-mentions while editing

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#331]
It would be nice if we could support @-mentions while editing, to add an explicit mention to a site user.

**Comment by koke** [comment]
Just adding that rather than mentions specifically, Gutenberg supports a customizable system of [autocompleters](https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/autocomplete/), so whenever we implement this we should build on top of that.

**Comment by designsimply** [comment]
This came up in a mobile request from @elibud after it was reported in some feedback that @ mentions were not working in expanded view for comments on WPiOS (now fixed) and we did a full audit of mentions after that. Username mentions are expected to work while composing a post and because this is an important feature when working remotely, can we move this request up in prioritization? @hypest can you help me with that by letting me know what release we can try for to get this added to?

<sup>(internal reference: p4a5px-2vE-p2)</sup>

**Comment by hypest** [comment]
@SergioEstevao will do a spike on this one to see what are the pieces missing/etc. This feature is probably also going to need some design (headsup @iamthomasbishop).

**Comment by elibud** [comment]
I'd like to see this one prioritized please.

**Comment by hypest** [comment]
@SergioEstevao is a bit busy at the moment and will be on some rotations the following 2 weeks so, @mchowning will step in next week to pick up this feature.

**Comment by mchowning** [comment]
:wave: @iamthomasbishop ! Do you have an svg icon to be used for the button?

**Comment by iamthomasbishop** [comment]
@mchowning Assuming you mean the `@` symbol, I don't at the moment but I will create one today.

**Comment by iamthomasbishop** [comment]
As mentioned in DM, icon was added to the [design docs](https://zeroheight.com/226850145/p/345d49-icons/b/78279c).
