### ISSUE TITLE
Remove code for older editors (Legacy, Visual)

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#336]
With the addition of the block editor the main WP apps will sport 4 editors (Legacy, Visual, Beta/Aztec, Gutenberg). There [seems to be a consensus](https://github.com/wordpress-mobile/WordPress-Android/issues/8611) about removing the couple oldest ones (Legacy, Visual) so, let's make a plan for it.

The following assumes a gradual transition and phase out of the oldest editors, giving some clues
Proposal:
1. Collect usage statistics to assess impact. Use the data to inform the next steps or dates.
2. Set a date at which the 2 oldest editors will become unavailable in the apps. A proposal: mid-end of Q2 2019, which is some time after the Block editor will be available to users.
3. Rename newer editors to Gutenberg->"Block Editor" and Beta->"Classic Editor" in internal and beta builds
4. Add some form of a prompt in the oldest editors, informing the user that the editor will be retired at mid-end Q2 2019 (or whatever date it's decided)
5. At the designated retirement date, remove the UI options to select the oldest editors and default to the Block Editor. Leave the actual editors' code in the app for a couple of app releases to monitor for problems.
6. Remove the oldest editors' code from the apps

What do you think @koke?

**Comment by koke** [comment]
> Collect usage statistics to assess impact

Looking at posts published on WordPress.com:

- Aztec: 96.8%
- Visual: 2.4%
- Legacy: 0.8%

I don't think it's worth delaying this so much, IMO we're ready to drop the older editors and the remaining questions to me are:

- How much effort does this take and if it's worth it. I think it's probably worth it since it will simplify the rollout of gutenberg-mobile but I don't know how much effort it will take.
- How we communicate this. Aztec has been on the apps for a while now, and it should be able to replace "Visual" smoothly except for some performance issues. I'm leaning towards just dropping them without making a big deal about it.

**Comment by koke** [comment]
OK, let's do this. We'll skip some steps and just remove the existing selector. Everyone using visual or legacy would get switched to Classic (Aztec).

We can leave the removing of old code for after the release

**Comment by hypest** [comment]
We have merged https://github.com/wordpress-mobile/WordPress-Android/pull/9208 which disables access to the old editors on the UI. That's the only aspect needed for the February release. Moving this ticket back to the backlog.

**Comment by hypest** [comment]
I think this can be closed since the editors' code were indeed removed from WPAndroid? Can you confirm @maxme ?

**Comment by maxme** [comment]
I confirm, the remaining bits of the hybrid and legacy editors were removed from the repository.

**Comment by maxme** [comment]
Ref: https://github.com/wordpress-mobile/WordPress-Android/pull/10368
