### ISSUE TITLE
Search Block: Make button appearance customizable

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#3478]
In the Search Block, the search button has some customization options already (icon vs label, inside the search bar vs outside it), however users may want the ability to customize it further.

The Button Block has options for text color, background color, and border radius which would be nice to have for the search button.

Note: there are some other buttons folks might want to customize, such as the "download" button in the file block. If we decide to implement customization for these sorts of buttons, we should first audit existing blocks to make sure we don't miss any with buttons.

Brought up in beta testing: p5T066-2eB-p2#comment-8125

**Comment by AmandaRiu** [comment]
Note: This isn't currently possible for mobile because the web version of the search block doesn't support any of these options. In order to have these features added to mobile they will first need to be added to the web version.

**Comment by hypest** [comment]
👋 @thehenrybyrd , thanks for this ticket! Yeah, as @AmandaRiu noted above, the shared Search block will need to go through the design and implementation processes that govern the web version of Gutenberg too (i.e. the enhancement proposed here doesn't sound to be native mobile specific) so, can I invite you to migrate this ticket to https://github.com/WordPress/gutenberg/issues? Thanks!

I will close this now but we can always reopen if it turns out to be native mobile specific 👍
