### ISSUE TITLE
Search Block: Block width option does not appear

### ISSUE THREAD

**Issue by villanovachile** [wordpress-mobile/gutenberg-mobile#3480]
**Describe the bug**
The search block does not display the width options, neither in portrait, nor landscape modes.

**To Reproduce**
1. Add a search block
2. Tap on search block, Align option appears, but not width options

**Expected behavior**
The width options should be appearing as per https://github.com/WordPress/gutenberg/pull/29275

**Screenshots**
https://d.pr/i/g6Wvh1

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max, iPhone 6, iPhone 12 Pro Max, iPhone 12 Mini
 - OS: iOS 14.2 & iOS 14.5.1
 - Version WordPress iOS 17.3

**Additional context**
This issue is reproduce under numerous scenarios including:
- Draft Post
- Published Posts
- Saving post, exiting editor, returning to Post in Editor

**Comment by AmandaRiu** [comment]
Hi @villanovachile 👋  This setting was [intentionally removed](https://github.com/WordPress/gutenberg/pull/29541/commits/112a3ec0510ae6278c67bfed9d20b675cd6e33ba) per the mobile designs for the search block. It was decided to remove this setting since it's difficult to configure width effectively on mobile. Additional details are documented in p9ugOq-1Kq-p2. I recommend closing this ticket as this is not a bug.

**Comment by villanovachile** [comment]
Thanks so much!
