### ISSUE TITLE
Make heading styling distinguishable from paragraph

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#351]
Currently, the `h4` setting for a heading makes it look too close to the styling of the normal paragraph block

Let's update it to be more distinguishable.

![screenshot 2018-12-11 at 18 25 58](https://user-images.githubusercontent.com/1032913/49814404-390c3300-fd72-11e8-97ae-47d4d0911cc4.png)

**Comment by pinarol** [comment]
@iamthomasbishop What's your opinion on this? I am also attaching some screenshots to demonstrate heading heights. 

Here's the corresponding font sizes on iOS side:
                .h1: 36,
                .h2: 24,
                .h3: 21,
                .h4: 16,

Aztec editor:

<img width="328" alt="screen shot 2019-01-22 at 15 55 13" src="https://user-images.githubusercontent.com/5032900/51538838-5cdb9200-1e63-11e9-8313-82c8a3b8655a.png">

Gutenberg editor:

<img width="329" alt="screen shot 2019-01-22 at 15 55 33" src="https://user-images.githubusercontent.com/5032900/51538852-636a0980-1e63-11e9-83cf-48a5c0c6acc9.png">

Both Aztec and Gutenberg use the same font size values in the background so the change will affect Aztec editor also.

**Comment by iamthomasbishop** [comment]
Hey @pinarol, here are the current proposed values for mobile GB, in terms of font-size/line-height:

* H1: 24/32
* H2: 22/28
* H3: 20/26
* H4: 18/22
* H5: 16/20
* H6: 14/18 

Note, all blocks share the following:

* Color: `$gray-dark` ( `#2E4453` )
* Font: `Noto-Serif`, `Bold`
* Internal padding within blocks (`top/bottom = 12pt`, `left/right = 16pt` – Because of this, the optical vertical margin between text elements is 24pt)

Here's what that looks like in practice:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/1200432/51558797-fac06400-1e45-11e9-8c0e-bd954caa712b.png">

**Comment by iamthomasbishop** [comment]
Another note: we should make sure this is responsive to OS-level accessibility preferences like text-size, zoom, etc. // cc @etoledom

**Comment by pinarol** [comment]
as discussed with @iamthomasbishop it looks like we are going to mimic web's behavior about this.
In the web side, they don't visually bold anything in the editor, it just applies to the front end result.

![ezgif com-video-to-gif 7](https://user-images.githubusercontent.com/5032900/51746281-a2dc6400-20b6-11e9-8095-5bf0a860e1d7.gif)

so I am planning to do this in 2 steps:
1. Bold by default, but customization to non-bold will also be available
2. Web's behavior as seemed in the gif. <- Planning to open a separate PR for this

Although I'd like to ask @iamthomasbishop once again, how strong are you feeling about item 2? Because after digging in a bit it looks like a bit problematic to implement that on iOS side. It will require us to detach RN side "bold" attribute from the main app side and adding exceptions on the current format attribute propagating logic. At least I can say that it is not as straight forward as just setting the font. So I wanted to take your opinion once more before introducing this complexity.

**Comment by iamthomasbishop** [comment]
> Web's behavior as seemed in the gif. <- Planning to open a separate PR for this

For the record I'm not a fan of the web behavior – it's confusing because there is no visual feedback when you tap "bold". The trick here is that we don't know what the theme's styles are, so telling the editor how a heading should display sets the expectation that it's going to appear as on the theme/front-end. A few paths we could go down, ordered by preference from my perspective:

1. Default headings to bold (display in `bold` font-weight and highlight the toolbar button) and when the "bold" button is tapped, intentionally set the `font-weight` to `normal`. This seems like the most natural path to me.

2. Remove the "bold" option in the toolbar altogether. Not a preferred solution, but at least it won't be there to cause confusion, and tbh I'm not sure how often folks will use this – we'd need to dig up data before going down this path.

3. Use web behavior: tapping `bold` does nothing inside the editor – this is confusing and feels like something is broken because nothing visually changes (as it does with italic), because we don't have a heavier weight than bold.

What do you think would be the most preferred path, considering the complexity and user expectation challenges of each?

**Comment by pinarol** [comment]
Hey @iamthomasbishop, I've been experimenting on this and I think I might have found sth that can solve both user experience issues and the code complexity issues.

Here is a preview:
![heading0 6-0 1-iphone7-html](https://user-images.githubusercontent.com/5032900/51827464-87619b00-22fa-11e9-94e4-88e8af67e4e8.gif)

So what I am doing is I am using a shadow effect to mimic the bold effect here. The shadow here doesn't have any blur so it looks like we are using a bolder font. We can also play with the thickness of it (vertical and horizontal thicknesses can be customized separately) (the above screenshot has shadow offset of horizontal: 0.6, vertical: 0.1). I can provide more samples to choose if we decide to move fwd with this. Also note that animated gifs are making everything look more blurry and the shadow is looking thicker than it really is, so I'll send you a quicktime capture from slack.

This is also not adding complexity to the current architecture because it will only requires overriding some formatting behaviors for heading blocks, the decision mechanisms about how things are working will remain same.

So what do you think @iamthomasbishop ?

**Comment by pinarol** [comment]
After discussing with @hypest and @iamthomasbishop we decided to make this change on standalone Aztec level so classic editor will also be affected, gutenberg will automatically inherit those changes.
