### ISSUE TITLE
Editing unsupported blocks is not disallowed on Classic-enabled Atomic sites

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/gutenberg-mobile#3544]
**Describe the bug**
Following the [TC004 test case](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc004) steps with an account registered _after December 2018_, presents the "Edit using web editor" button, even though the Classic editor is enabled and set as the default. Tapping the button loads an empty web view. The expectation is that there should not be an option to edit the block in a web browser.

**To Reproduce**
Precondition: A WP.com Atomic site (i.e. a WP.com site with a Business plan) with the Classic editor set as the default. Here are the steps for creating this if necessary:

1. Find a site with a Business plan or higher
1. Install and activate the Classic Editor plugin
1. In Calypso choose your site and go to Tools | Plugins | Installed Plugins, then tap Settings under the Classic Editor plugin and set Default editor for all users to Classic Editor

Reproducing: 
1. On the site described above, add a post, then add a block that's not yet supported on mobile (e.g. Jetpack Markdown at time of writing)
1. Log into the WordPress mobile app using the site's WP.com account
1. Open the post and expect to see the block rendered as a placeholder with the text "Unsupported"
1. Tap the (?) icon and expect to NOT see an option to edit the block in a web browser

**Expected behavior**
There should not be an option to edit the block in a web browser. 

**Screenshots**

https://user-images.githubusercontent.com/438664/119186357-9de90e80-ba3d-11eb-8b98-9582e4b93d0e.MP4

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 14.4.2
 - Version: 17.4

**Additional context**
Likely related to #3425.

**Comment by guarani** [comment]
Thanks for creating the issue, @dcalhoun! I just updated it since the Audio block is no longer an unsupported block (I've made a PR for updating the test cases here: https://github.com/wordpress-mobile/test-cases/pull/78).

**Comment by guarani** [comment]
In fixing [Editing unsupported blocks is disabled on Jetpack and Atomic sites accessed via older WP.com accounts](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425), we also fixed this issue, although the resolution is different to what you put down as expected behavior above, @dcalhoun. I think the difference can be explained, so let me summarize here.

We added an error screen that states _"Unable to load the block editor right now. Please ensure the block editor is enabled on your site and try again."_ if a user tries to load the Unsupported Block Editor and for whatever reason the block editor is unavailable (see https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-840416798 for details).

I tested the steps to reproduce above and see this new error screen with the explanatory message on both platforms:

#### WPiOS 18.1

https://user-images.githubusercontent.com/1898325/133286471-e5b5e429-0b14-4449-9e02-b825c857e0fb.mp4

#### WPAndroid 18.2-rc-3

https://user-images.githubusercontent.com/1898325/133284468-458f7153-aa3c-4169-b250-222bce1e8968.mp4

### Conclusion

Ideally, we'd be able to prevent the "Edit using web view" option from showing up in the first place, which is what you mentioned in the issue above @dcalhoun. For that we would need an API to verify which editor is available on the backend. We did have this API, but it was unreliable (see https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-840223555) and we removed it.
As mentioned in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-848194586, in the unlikely scenario a user has the block editor unavailable, the error message might be sufficiently explanatory. 

Given this, do you agree that we can close this, @dcalhoun? I can take care of updating the test cases to reflect this.

**Comment by guarani** [comment]
It's worth mentioning that [there's an enhancement issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2480) open that proposes finding a way to make the Unsupported Block Editor work even if the site is classic-enabled. I don't think there's a known way to achieve this at the moment, so it probably won't be possible to achieve it for the time being. In the mean time, the current messaging seems like the best compromise.

**Comment by guarani** [comment]
If this issue can be closed, we can also update the test cases, and for that I've opened https://github.com/wordpress-mobile/test-cases/pull/87.

**Comment by dcalhoun** [comment]
> Given this, do you agree that we can close this, @dcalhoun? I can take care of updating the test cases to reflect this.

@Guarani I agree we should close this, as the spirit of this issue was accomplished. Thank you for following up on this. 🙇🏻

**Comment by guarani** [comment]
> @guarani I agree we should close this, as the spirit of this issue was accomplished. Thank you for following up on this. 🙇🏻

Thank you for filing the issue @dcalhoun! 👍
