### ISSUE TITLE
Tapping on an empty editor area

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/gutenberg-mobile#358]
When you have little content and tap on an empty area below it, some people might expect something to happen, like adding more text. Let's discuss here what should happen.

@iamthomasbishop suggested adding a limited area below the last block where you can tap:

![image](https://user-images.githubusercontent.com/8739/49869915-2cd7b280-fe12-11e8-9a37-dbc8dca36ba8.png)

@hypest suggested adding some UI to it to make it discoverable, like the web has on hover:

![image](https://user-images.githubusercontent.com/8739/49869970-55f84300-fe12-11e8-880d-68d384e6a09c.png)

I think it'd be also interesting to explore how the perception changes when we implement view/edit modes in #204

**Comment by iamthomasbishop** [comment]
Side note on @hypest's comment: There _is_ a minimal version of that example @hypest gave on mobile web, but only on "hover" (which means it didn't show until second tap) on a newly-created empty block, which kinda defeats the purpose here. Here's what it looks like:

![image](https://user-images.githubusercontent.com/1200432/49894215-0108fc80-fe13-11e8-8a57-c950bed9fcd4.png)

**Comment by hypest** [comment]
Just to add clarity, on the native mobile editor the "on hover" action doesn't make much sense so, the idea was to have the "ghost block" always shown at the end of the post, always available to tap into.

**Comment by iamthomasbishop** [comment]
I keep coming back to this issue, mostly after I've added an Image block. Usually after I've added an Image block the writing flow is essentially blocked unless I tap the inserter. This same issue concept applies to other media blocks, page break, more, separator, etc etc. Another sketch from the other day:

![image](https://user-images.githubusercontent.com/1200432/58055140-6976ab00-7b22-11e9-9074-a594e3d0ed69.jpeg)

**Comment by hypest** [comment]
I wish we would bump up the priority of this ticket or similar.

As a example of how I stumbled on this again, I recently noticed that even though sharing a photo from the photo app into the editor is quite streamlined, trying to add a simple text below the the image has friction since I need to tap on the Inserter first, locate the Paragraph block and tap it to insert it. I'd gladly tap on a "placeholder" at the end of the post and quickly start writing in it instead.

**Comment by koke** [comment]
I agree, I've encountered this a few times while testing, and it's quite frustrating. It's back on the project.

**Comment by SergioEstevao** [comment]
What about just having a (+) kind of inserter block always on the end of the content?

**Comment by iamthomasbishop** [comment]
That’s been explored a bit, but the rationale is that we want to have *one* consistent and clear entry point (the blue (+) button in the toolbar) for the inserter to limit confusion. If we decide to add anything at the end of the canvas, I’d want to prefer some alternatives. 

Tbh, I’m not sure if it’ll even be a problem if/when we implement this ghost block behavior, since it seems that a bunch of folks have stumbled onto the same expectation of tapping at the end of the canvas. It’s a very subtle thing but it seems to be an expected behavior.

**Comment by hypest** [comment]
Can we do something super minimal here, like reusing the placeholder we have when starting a new post but have it say "Tap to write here"?

That said, I think we should at least do the "tap in the empty/invisible area" shown in Thomas' [comment above](https://github.com/wordpress-mobile/gutenberg-mobile/issues/358#issuecomment-494170425) and iterate on it.

**Comment by iamthomasbishop** [comment]
IMO, it would be really weird to have a stray "tap to write here" or similar – at that point we might as well put a `(+)` icon there, but I want to avoid doing that for the reasons mentioned earlier.

The more I use the editor, the more strongly I feel about an "invisible tap area" at the end of the canvas being the intuitive solution because I find myself (and have seen others using the editor do the same) intuitively tapping on that area to add more content – like most content editing applications.

This also solves the other issue that I have in that there isn't any whitespace at the end of the canvas.

**Comment by koke** [comment]
I'll add that I find myself often tapping on that empty space expecting to add more text, I think it'd just feel natural to append add a touchable section at the bottom of the list, even if it's blank

**Comment by hypest** [comment]
Implemented (tapping on empty area) with #1200.
