### ISSUE TITLE
Reusable Blocks: App editor shows text color as default even though it is color on web and in preview. 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/gutenberg-mobile#3615]
### Expected behavior
Reported by @osullivanchris: 
I set the text to pink on web. In the editor on web, the text is pink. In the app, the text is not pink in the editor, although it is in preview. I feel like we should be consistent on web/app in terms of what is WYSIWYG. Either it changes to look like the front end, or it has a neutral style in the editor. But it shouldn’t change between web editor and app editor.

### Steps to reproduce the behavior
1. Create a resuable block on web and set the font to any colour that isn't default 
2. View on web preview, it's the color you chose
3. Use that reusable block on the iOS app, the font is default color in the editor
4. View in preview from the app and it's the color you selected on web 

##### Tested on iPhone 12 Pro, iOS 14.6, WPiOS 17.5.0.1

**Comment by fluiddot** [comment]
I think this issue is not totally really related to the reusable block as it can be reproduced with a regular Paragraph block.

**Steps:**
1. Add a Paragraph block to a post/page and set the font to any colour that isn't default
2. View on web preview, it's the color you chose
3. Edit the same post/page on the iOS app, the font is the default color in the editor
4. View in preview from the app and it's the color you selected on the web version

**Comment by osullivanchris** [comment]
Spoke to @iamthomasbishop about this and he said its something planned to bring to Gutenberg in future, but expected behaviour today. So I think we can close this issue?
