### ISSUE TITLE
Android: Keyboard gets dismissed when writing and pressing enter to create a  new block

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/gutenberg-mobile#381]
When typing on a paragraph or Title block and tapping `Enter` to create a new block, the soft keyboard is dismissed, thus interrupting the writing flow.

![jumpiness](https://user-images.githubusercontent.com/6597771/50013608-63dbce80-ffa0-11e8-99f6-e8a92b83f241.gif)

**Comment by daniloercoli** [comment]
I've investigated this issue going back in git history, and found out that the culprit is this PR here:  https://github.com/wordpress-mobile/gutenberg-mobile/pull/341

The problem lays in the GB side PR https://github.com/WordPress/gutenberg/pull/12765
If you comment the code added in the PR above, the keyboard is not dismissed anymore on Enter.key pressed event, of course, you will re-introduce the issue the original pr fixed. 

Putting some log in the code also shown that the calls are made correctly, first the `blur` method of the old field is called, (that in turn executes `TextInputState.blurTextInput(ReactNative.findNodeHandle(this));`), then the call to `focus` on the new field is made and `TextInputState.focusTextInput(ReactNative.findNodeHandle(this));` executed.

**Comment by mzorz** [comment]
Thanks for digging into it @daniloercoli ! I was wondering maybe we could put a flag somewhere, so to prevent Blur from being called if the flag is set, i.e. for example when we know we are doing a block split, we set the flag on, once the split ends, we set the flag off. This would probably require 2 actions on the redux store. IDK, just a thought.
