### ISSUE TITLE
UBE: Android text selection toolbar is blocking access to dropdown menus

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/gutenberg-mobile#3862]
### Expected behavior
I expected the Android text selection toolbar to be dismissed after clicking the page menus so the results from the user's last action would be fully accessible.

### Actual behavior
Android text selection toolbar is not dismissed and blocks the access to the 'more settings' and to the 'options' dropdown lists.

### Steps to reproduce the behavior
1. Open a post with unsupported blocks (p2/task in this case)
2. Click on the question mark in the block
3. 'Edit using web editor'
4. Select part of the tex
    * Android text selection toolbar is displayed
5. Click the chevron icon to expand the edition options
6. Try to select 'Inline code'
    * Expected: By clicking outside the Android text selection toolbar it should be dismissed and the result of the user's last action would be completely accessible.
    * Observed: Android text selection toolbar is not dismissed and the 'Inline code' is not accessible.

##### Tested on Samsung Galaxy Note20, Android 11, WPAndroid 18.0-rc-2 and Play Store version (17.9.1)
https://user-images.githubusercontent.com/42008628/129751141-0d9c2b0d-d2dd-4e30-bb3c-196842b8d62c.mp4

**Comment by hypest** [comment]
> Try to add big margins in the content inside the UBE so scrolling can reveal the obscured menu items.

@guarani , you have some experience with the UBE, I wonder what are your thoughts on the level of "hackiness" of this avenue or how easy/hard this might be to perform in the UBE? While at it, pinging you @SiobhyB too since this might be a CSS-hack and you had some recent experience with CSS-hacking the UBE. Thanks!

**Comment by guarani** [comment]
> Try to add big margins in the content inside the UBE so scrolling can reveal the obscured menu items.

@hypest if I understand correctly, this would cause the editor to always have side-scroll, is that correct? I have it a quick try but wasn't able to locate the right element to add the spacing to. It does feel very hacky, but better alternatives are not clearly available.

> Try to suppress the contextual action bar (the popup menu Android shows when selecting text) when the chevron menu is triggered.

Since the contextual action bar has a similar function to the "More" menu, I agree it would be nice to have a way to only show one at a time.

I was looking at a couple of Stack Overflow questions about this. [This one](https://stackoverflow.com/questions/49654886/how-to-hide-actionpopupwindow-of-text-selection-handler-of-edittext) is for someone in a similar situation to us. This one suggests it was possible (in older Android versions) to keep text selection while hiding Android's menu. [This one](https://stackoverflow.com/questions/63130918/handle-touch-outside-textview-after-selectable-text-menu-appears-in-android) asks whether it's possible to dismiss Android's menu while retaining text selection.

**Comment by SiobhyB** [comment]
> While at it, pinging you @SiobhyB too since this might be a CSS-hack and you had some recent experience with CSS-hacking the UBE. Thanks!

While testing this, I noticed that the text selection toolbar also persists when the `Show more settings` dropdown item is tapped, ending up with it overlaying the new window: 

https://user-images.githubusercontent.com/2998162/130691752-f23c59b5-0336-4879-95ce-31b1ccfc5b95.mov

I don't believe there's a CSS hack that would solve the above case, so the second idea of finding a way to suppress the toolbar when dropdown items are tapped seems preferable to me. 

Something I haven't been able to wrap my head around is why the toolbar is correctly dismissed when the bold, italic, or link menu items are tapped, but not when any of the dropdown items are first tapped. It's also confusing to me that simply tapping anywhere within the dropdown window (when it's opened) dismisses the toolbar (and correctly leaves the text selected):

https://user-images.githubusercontent.com/2998162/130694250-a0702f49-d277-4c6a-9841-4542cded22ab.mov

From the links Paul shared, all signs seem to point to focus not being correctly "taken away" when the dropdown items are first tapped. Maybe exploring some custom JS with [the `.focus()` method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) would be a good next step? I'd be happy to try experimenting with that this week unless others have more ideas or get there before me.

**Comment by hypest** [comment]
Interesting insights @SiobhyB , thanks for sharing! +1 for keep digging into this for a bit more, thanks!
