### ISSUE TITLE
RichText: mark onSplit prop as unstable 

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/gutenberg-mobile#394]
`onSplit` prop is an being revised in [#gb-11005](https://github.com/WordPress/gutenberg/pull/11005), and in the meantime it was marked as unstable here: https://github.com/WordPress/gutenberg/pull/11926

We should mark it as unstable on mobile too.

**Comment by koke** [comment]
@daniloercoli I'm moving this to the Future column, since it doesn't seem like a bug that would affect users, and the discussion seems to be still going in https://github.com/WordPress/gutenberg/pull/14765

I don't understand the implications of this (I'd appreciate a quick explanation), so we might still want to tackle it soon, but I'd keep it out of the bug fixes column until then, and leave that for things that affect the UX.

**Comment by mkevins** [comment]
@daniloercoli https://github.com/WordPress/gutenberg/pull/14765 has been merged. I think this PR can resolve this issue: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1013.

**Comment by daniloercoli** [comment]
Right @mkevins. #1013 updated the mobile side.
