### ISSUE TITLE
Tiled Gallery columns and rounded corner settings for Square layout

### ISSUE THREAD

**Issue by illusaen** [wordpress-mobile/gutenberg-mobile#3947]
Add settings (BottomSheet) to the tiled gallery block..

Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/3874

**Comment by guarani** [comment]
👋 @illusaen, I'm wondering if we should close this issue or leave it open, but I'm not sure of its scope. If we just look at the Square layout, the only part left-over was the "Link To" functionality, for which I've created a new issue in https://github.com/wordpress-mobile/gutenberg-mobile/issues/4156. 

So in short, if this issue is specific to the Square Layout, I think it can be closed. If however it's scope includes other layouts, we could leave it open. Either way, I think it's best to have small-scoped issues.

**Comment by illusaen** [comment]
@guarani I agree, I think closing this makes sense. We can make separate issues for the other layouts.
