### ISSUE TITLE
Block Inserter Search: Bottom Sheet fills screen before Search is tapped

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/gutenberg-mobile#3948]
**Describe the bug**
In Android, the bottom sheet comes all the way up as soon as "+" is tapped.

**To Reproduce**
1. Open the block editor, in either a post or page.
2. Tap the "+" icon to add a new block.
3. Note that the Block Inserter fills the whole screen and you can see nearly all the blocks.

**Expected behavior**
Based on screenshots in https://github.com/WordPress/gutenberg/pull/33237, the bottom sheet should come up halfway, and only come up all the way when search is tapped.
In the previous release, as well as on iOS, the bottom sheet comes up only halfway.

**Screenshots**

https://user-images.githubusercontent.com/15107387/132846544-f48778e1-67b2-4f99-892d-d44c27c481a2.mp4

**Smartphone:**
Samsung Galaxy S21, Android 11, WPAndroid 18.2-rc-2

**Additional context**
Found in beta testing

**Comment by jhnstn** [comment]
Hi @thehenrybyrd, this is the expected behavior for Android. We ran into some animation issues with the inserter when the keyboard opens. Making the inserter menu fullscreen by default was the best workaround we found. There is a short discussion here https://github.com/wordpress-mobile/WordPress-Android/pull/15044#issuecomment-883750475 .
