### ISSUE TITLE
Navigation icon in bottomsheet is too dark on Dark Mode

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#3956]
**Describe the bug**
The "back button" in the navigation section on a nested page of the bottom sheet is too dark.

**To Reproduce**
1. On the demo app on a device with Dark Mode enabled
2. Add a paragraph block and tap on the cog icon to bring up the block settings
3. Tap on "Font Size" just to go deeper in the nav hierarchy
4. Notice the "back" button being too dark 💥

**Expected behavior**
The back button should be lighter. Checkout [the screenshot on this ticket](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3922) as an example.

**Screenshots**
<img src="https://user-images.githubusercontent.com/1032913/133244873-d979ce83-f573-4ac4-b782-24756469a642.png" width=250/>)

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - Version `develop` based on 1.61.0 (hash: 37564bee)

**Additional context**

**Comment by antonis** [comment]
I confirm that the issue is not reproduced in the [`18.2-rc-3`](https://href.li/?https://github.com/wordpress-mobile/WordPress-Android/releases/tag/18.2-rc-3) available in Google Play.

|`18.2-rc-3`|`develop`|
|---|---|
|![device-2021-09-14-140541](https://user-images.githubusercontent.com/304044/133246827-ab591bd1-f77f-4df7-984f-25cf9533090b.png)|![device-2021-09-14-140558](https://user-images.githubusercontent.com/304044/133246825-52c73e24-5257-461d-ae08-2f9b36d570fc.png)|

_Test device: Pixel 5 (Android 12 beta)_
