### ISSUE TITLE
[Feature request] Allow copy pasting text when creating Story post

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#3988]
**Is your feature request related to a problem? Please describe.**
Currently, when we create a Story post in the app with text, the text will have to be entered through the keyboard. We're not able to paste the text copied from another source.

**Describe the solution you'd like**
Allow copy-pasting text when creating a Story post in the app

**Additional context**
Originally requested here: 4309425-zd-woothemes

**Comment by hypest** [comment]
👋 @aforcier ! Can you help triage this ticket? Thanks!

**Comment by aforcier** [comment]
Hi 👋 This seems to be an iOS only issue, and also related to the story creator (Kanvas) rather than Gutenberg mobile. Looks like we already have an open issue for it: https://github.com/tumblr/kanvas-ios/issues/52.

So, I think we can close this one out as a duplicate. cc @bjtitus in case I've missed any nuance.
