### ISSUE TITLE
Replace dash icons with Gridi icons

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#403]
Currently, we are re-using gutenberg code which is using [dash icons](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/dashicon/index.js) as icons in the app. 

Based on [discussion](https://github.com/wordpress-mobile/gutenberg-mobile/issues/350) with @iamthomasbishop and @koke we can try to replace dash icons with Grid icons - currently, it will only affect Toolbar (both inner and format Toolbar).

**Comment by iamthomasbishop** [comment]
Worth note: We are currently using Gridicons across the native apps. If we don't already have access to them within Gutenberg, it might be useful to configure those for easy utilization.

**Comment by koke** [comment]
I don't think we have anything in place right now, do we need any Gridicons for the beta?

**Comment by marecar3** [comment]
I think that this one still has value as @iamthomasbishop would love to see grid icons/material icons instead of dash icons :)

**Comment by iamthomasbishop** [comment]
I would love to just banish Dashicons because they're not easy to use and it'd be beneficial technically and design-wise to simplify to two icon sets (Gridicons and Material – the former which we use elsewhere in the apps, and also these two play well together stylistically). I don't know if I'd call it a blocker, but it is a pain in the arse on the design side :)

**Comment by SergioEstevao** [comment]
@iamthomasbishop Taking in account the new icons introduced in Gutenberg recently does this issue still make sense?

**Comment by iamthomasbishop** [comment]
@SergioEstevao I think we can safely close this one.
