### ISSUE TITLE
Global styles - Font size - Heading and Preformatted block

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#4112]
**Describe the bug**
After implementing font size support, an issue was found on **iOS** where the `Heading` and `Preformatted` block won't change their default font size.

The Header [formatter (On Aztec)](https://github.com/wordpress-mobile/AztecEditor-iOS/tree/develop/Aztec/Classes/Formatters/Implementations) should use the font size that the default font has set but it's using the one from the respective `h1`, `h2`, etc tags default sizes.

The `Preformatter` block uses a font that is set in `FontProvider.shared.monospaceFont` (On Aztec) so there needs to be a way to customize the size as well.

**To Reproduce**
- Open the app on iOS in development mode (to be able to see the font size picker)
- Add either a `Heading` block or a `Preformatted` block
- Change the font size
- See the font size **is not** changed

**Expected behavior**
The font size should change for these blocks when changing the value

**Screenshots**
<kbd><img src="https://user-images.githubusercontent.com/4885740/137141199-a568c366-79af-47f0-a878-67a383c42bc7.gif" width=200 /></kbd>

**Smartphone (please complete the following information):**
 - Device: Any iOS device

**Additional context**
- [Aztec Editor iOS repo](https://github.com/wordpress-mobile/AztecEditor-iOS)

**Comment by mkevins** [comment]
@geriux  :wave: :smile: 

I've made some progress on this within these POC branches:
* https://github.com/wordpress-mobile/AztecEditor-iOS/compare/try/fix-custom-font-size-gutenberg-heading-and-pre-blocks
* https://github.com/WordPress/gutenberg/compare/rnmobile/try/fix-custom-font-size-gutenberg-heading-and-pre-blocks

In this approach, we use the font-size from the default to create a font-scale, preserving the relative differences in size between the various heading levels, based on [this commit](https://github.com/wordpress-mobile/AztecEditor-iOS/commit/909cb045674b73782dc65801f74ed775310fe07b). This is not ideal, however, since it can alter the behavior of Aztec, so we'd need to also find a way to condition this scaling to Gutenberg usage.

In [this commit](https://github.com/wordpress-mobile/AztecEditor-iOS/commit/8df81c393f22c1167a411e64b7940fcaf5e753d1), I found a way to do that, however it feels inelegant. Essentially, we are passing a `isForGutenberg` boolean through the layers of Aztec, and I don't really like the idea of deeply bifurcating the stack in this way. Otoh, I'm struggling to find a cleaner alternative. Perhaps this kind of "Gutenberg awareness" is inevitable within Aztec. We could also find more meaningful names for the interface - but it'd still be driven by "is this for Gutenberg?" within Aztec. :man_shrugging: 

I'm curious if you have ideas about this - and also, what we ultimately _want_ with regard to the behavior of custom font sizes in heading blocks. For example, if we have two headings: `<h1>`, and `<h6>`, and each has a custom-font set to: "Large (36px)", do we want them to appear the same size? If so, perhaps we want the semantics (i.e. actually font-size in pixels) of "Small", "Normal", "Medium", "Large", and "Huge" to change based on the heading level?

Aside from the [dead code](https://github.com/WordPress/gutenberg/issues/37090), I noticed [this comment](https://github.com/WordPress/gutenberg/compare/rnmobile/try/fix-custom-font-size-gutenberg-heading-and-pre-blocks#diff-3523b4a5a519e3975d67f8a202df9e8f91b3e3aff0168c86598c9e2abcbdf890R107) and wonder whether this still holds true. It would be good to also confirm this, and update it if not.

**Comment by geriux** [comment]
Hey @mkevins 👋 thank you for continuing investigating this and making progress with this task.

I like that idea of a flag to be able to use a custom heading font size and not use the default values from the formatter, as you mentioned I agree that having that flag Gutenberg related is probably not ideal to be within the Aztec code. 

I had this idea after our chat a few weeks ago about a configuration flag to customize this behavior, I put together two branches with these changes and it's a bit more cleaner in a sense of not having something related to Gutenberg within Aztec.

On Aztec iOS, [I added](https://github.com/wordpress-mobile/AztecEditor-iOS/commit/47d69e9e7e52cb201e0faeaf71fb789aa5aca9f6) `customHeadingFontSize` within the `Configuration` file, then within the HeaderFormatter, if this flag is `true`, it'll use the defaultSize and not the one that it has for each level.

On RCTAztecView, [I set to true](https://github.com/WordPress/gutenberg/commit/bfbb71c02ab329cd6b00609a579058cf90b79c7b#diff-3523b4a5a519e3975d67f8a202df9e8f91b3e3aff0168c86598c9e2abcbdf890) the `customHeadingFontSize` flag within the `commonInit` I left a comment where we should enable this only for block-based themes, I know we have this data stored within WordPress iOS but I didn't get to investigate how to get it 😅

Then it should just use the font size that's being set in the `defaultFont`. I also had to make some tweaks in the [RichText component](https://github.com/WordPress/gutenberg/commit/bfbb71c02ab329cd6b00609a579058cf90b79c7b#diff-7af18df9c3e07e67518894550a2e1d9d627feb879a2003a2e231ef927d4d06f8) to update the font size if the `tagName` changed, for the case where you change the level of a heading block.

What do you think of this approach? It's based on yours but avoiding passing a Gutenberg flag to Aztec.

In regards to the font scale I think we could do that in RCTAztecView, I was thinking that since we are passing the `tag` we could check if it's a heading block and do the scale there when we set the font size. But I think we could focus on that on a separate task if we decide we want to have this font scaling system, what do you think?

**Comment by mkevins** [comment]
Thanks for the thoughtful reply Gerardo!

> What do you think of this approach? It's based on yours but avoiding passing a Gutenberg flag to Aztec.

I like this better, as it's not touching as many layers (the static "global" setting can just be written / accessed directly).

By this:

> to update the font size if the tagName changed, for the case where you change the level of a heading block.

did you mean something like this?

> perhaps we want the semantics (i.e. actually font-size in pixels) of "Small", "Normal", "Medium", "Large", and "Huge" to change based on the heading level?

This is one area I was wondering about / looking for clarity on. I understand that the spec doesn't require size differences, but that often browsers default styles will use `em` units to distinguish the ranks. Otoh, these could easily be distinguished in other ways while preserving the semantics of the heading and implied section (or subsection), e.g. weights, or even horizontal rules.

> But I think we could focus on that on a separate task if we decide we want to have this font scaling system, what do you think?

For reasons above, I agree totally with this. While it isn't totally clear how it will look as a block setting (if meanings of "Small", "Large", etc. will be on a "per rank" basis), I think this can (and should) be deferred to a separate task. The hack I had in place on the POC branch actually makes assumptions that "Normal" == 16, but even this is dependent on a particular interpretation of semantics, so keeping this as simple as direct font size manipulation provides us a more straightforward foundation for later developments, imo.

>  I know we have this data stored within WordPress iOS but I didn't get to investigate how to get it :sweat_smile: 

That part is a little tricky, I think, since we can't have `gutenberg` depending on WordPress iOS - my guess without researching it is that we'd use a similar mechanism as we do for other theme information that is passed with `initialProps` (and updated when the cache is invalidated after a fetch response).

**Comment by geriux** [comment]
> By this:
> 
> > to update the font size if the tagName changed, for the case where you change the level of a heading block.
> 
> did you mean something like this?
> 
> >

I meant when you change an H2 to H1, or another level, 3, 4, 5, etc... Since this change is happening on Aztec, once this value is updated in RichText we need to get the default font size for that level.

> I think this can (and should) be deferred to a separate task.

I agree!

> The hack I had in place on the POC branch actually makes assumptions that "Normal" == 16, but even this is dependent on a particular interpretation of semantics

Yeah for this case we'd need to set this "default" normal value from the theme data.

> That part is a little tricky, I think, since we can't have gutenberg depending on WordPress iOS 

Oh but this would happen in `RCTAztecView` which is part of `react-native-aztec`. But yeah it'd make sense to enable this from the editor once it has the `theme.json` data available.

**Comment by geriux** [comment]
Quick update on this, I drafted the PRs with a working implementation:

- Gutenberg: https://github.com/WordPress/gutenberg/pull/37663
- Aztec iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1345

I'll work on getting a testing build ready and updating the PRs descriptions.
