### ISSUE TITLE
Bug: Editing unsupported block using web editor in app created draft posts

### ISSUE THREAD

**Issue by devNigel** [wordpress-mobile/gutenberg-mobile#4130]
When you edit an unsupported Layout block in the web editor and closes it, it creates a draft post. A new draft post is created each time this is done.

### Expected behavior

Editing using web editor in the mobile app should not be creating new draft posts.

### Actual behavior

It created draft posts.

### Steps to reproduce the behavior

* First, create a page or post with a Layout Grid grid and add some text content to it from WordPress.com website.
* Open the Android app to edit that page from mobile.
* You will notice that the Layout grid is unsupported and suggests to `Edit using web editor`.
* Open using web editor, make some changes in the content added in the Layout Grid.
* Close the web editor by clicking on X button at the top left corner to go back to the mobile editor screen. It is not necessary to press on the tick icon. 
* Close the mobile editor.
* Check the Posts > Draft section in the app or the Posts section in WordPress.com website dashboard. You will notice Draft posts with empty titles.

### Screenshot

![image](https://user-images.githubusercontent.com/33957570/115223363-56632000-a129-11eb-855a-fb2860c5ffa8.png)

![image](https://user-images.githubusercontent.com/33957570/115224755-e48bd600-a12a-11eb-997d-28475d82b94f.png)

**Comment by dcalhoun** [comment]
Do not have a fix yet, but capturing what I found so far.

From debugging, this appears to related to the auto-save functionality within the _web editor_, and not directly related to the native editor. The issue can be recreated with the following steps on _both Android and iOS_:

1. Save or publish a post in the web block editor that contains an unsupported block by the native editor, e.g. Tiled Gallery as of writing. 
2. Open the same post with the native block editor. 
3. Tap the `?` icon found on the unsupported block. 
4. Leave the editor alone for 60+ seconds. 
5. In the web admin, visit/refresh the Drafts post lists. 
6. ⚠️ There is an extra, untitled draft that contains the contents of the Unsupported Block Editor (UBE) for the post. 

We have code to [disable the web editor auto-save](https://github.com/WordPress/gutenberg/blob/ae12d948f10378016cf436f8e5890f70072181e6/packages/react-native-bridge/common/gutenberg-web-single-block/prevent-autosaves.js#L2-L5), but it appears to be broken. 

When running the WordPress mobile apps in a local development environment, the UBE still requires a Jetpack connection to a _remote_ WordPress admin. So, fixing this issue will require a staging environment to test changes deployed to the web block editor. I am unfamiliar with if/how we can set up a staging environment, so I will need to familiarize myself with that before I can find a fix for this issue.

**Comment by guarani** [comment]
👋 @dcalhoun I could also reproduce this on Android and iOS. Since this affects both platforms, would it make sense to transfer this issue to https://github.com/wordpress-mobile/gutenberg-mobile?

**Comment by guarani** [comment]
> When running the WordPress mobile apps in a local development environment, the UBE still requires a Jetpack connection to a _remote_ WordPress admin.

Just in case this info helps: while the UBE currently supports only WP.com and Jetpack-connected self-hosted sites, there's plans to allow it on self-hosted sites (see https://github.com/wordpress-mobile/gutenberg-mobile/issues/2482).

**Comment by dcalhoun** [comment]
Closing this issue as it was addressed in https://github.com/WordPress/gutenberg/pull/35639. However, because of the nature of the issue and the architecture of the Unsupported Block Editor (UBE), the fix will only be delivered when the site edited with the UBE receives the fix through a Gutenberg update — via plugin or core update. 

To elaborate, the UBE loads a web view of the remote WordPress site itself. Therefore, the version of Gutenberg installed to the remote WordPress site is the version loaded. Until that installation is upgraded to the version containing the fix, this bug will continue to occur within the UBE. So, resolving this bug is site-specific. 

An alternative "fix delivery" solution would be to "package" a Gutenberg version within the UBE, but that re-architecture would likely be significant and come with tradeoffs that would need to be considered (e.g. version mismatch between app and site). There are no plans to explore this architecture at this time.

**Comment by guarani** [comment]
Makes sense @dcalhoun, thanks for explaining that here 🙇
