### ISSUE TITLE
Tiled Gallery doesn't serialize correctly when multiple rows are used

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4142]
**Describe the bug**

The block doesn't serialize properly when the number of columns in its output HTML is less than its number of images, i.e. it breaks when it has multiple rows in its output HTML.

After further investigation, we've found that the issue with multiple rows is a structural issue (i.e. having multiple `<div row><div col></div></div>` is failing. The attribute differences are a separate issue that we will look at in the[ issue where we will revisit the workaround.](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4137)

NOTE: I forced the `isValid` boolean result to `true` in a test and the editor rendered the block perfectly fine, implying that there's some mismatch between the validation (generated block content vs original block content) instead of an actual issue with the HTML.

**To Reproduce**
1. Checkout the `add/tiled-gallery-block` feature branch
2. Run `git submodule update --init --recursive` to grab the corresponding Jetpack code
3. Run the packager: `npm run start:reset`
4. Run the app, e.g.: `npm run ios`
5. Add the Jetpack Tiled Gallery block and add two or more images to it
6. Change the block's settings to 1 column
7. Switch to HTML mode and cut the HTML 
8. Switch back to Visual mode
9. Switch to HTML mode again (these steps force the visual editor to update)
10. Paste in the HTML that was cut
11. Switch back to Visual mode
12. Notice the "Problem displaying block"

**Expected behavior**
The block should be deserializable from HTML.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15

**Comment by illusaen** [comment]
Looking at the HTML that the web produces, I found two things:
1. The attributes for the `save` workaround that I changed are in a different form on the web; I have a suspicion that when a user makes a post with a JTG on the web and then tries to load it on the phone, there will be a PDB error. The workaround, ofc, makes it so that saving a post on mobile and then loading it should work; however, both parts need to algn and work successfully.
2. The 1 column HTML serialized from the web looks just like the HTML serialized from mobile, other than the above mentioned attributes. I don't think the issue lies with the save function but does lie with the validation.

Web 1 column HTML:
```
<!-- wp:jetpack/tiled-gallery {"className":"is-style-square","columns":1,"columnWidths":[["30.83011","69.16989"]],"ids":[15,16]} -->
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-square"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row columns-1"><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="2400" data-id="15" data-link="https://sandbox1359387942.wpcomstaging.com/placeholder-image-6/" data-url="https://sandbox1359387942.wpcomstaging.com/wp-content/uploads/2020/10/image-from-rawpixel-id-432177-jpeg.jpg" data-width="1600" src="https://sandbox1359387942.wpcomstaging.com/wp-content/uploads/2020/10/image-from-rawpixel-id-432177-jpeg.jpg" data-amp-layout="responsive"/></figure></div></div><div class="tiled-gallery__row columns-1"><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="1067" data-id="16" data-link="https://sandbox1359387942.wpcomstaging.com/placeholder-image-7/" data-url="https://sandbox1359387942.wpcomstaging.com/wp-content/uploads/2020/10/image-from-rawpixel-id-593165-jpeg.jpg" data-width="1600" src="https://sandbox1359387942.wpcomstaging.com/wp-content/uploads/2020/10/image-from-rawpixel-id-593165-jpeg.jpg" data-amp-layout="responsive"/></figure></div></div></div></div>
<!-- /wp:jetpack/tiled-gallery -->
```

Mobile 1 column HTML:
```
<!-- wp:jetpack/tiled-gallery {"columns":1,"columnWidths":[[360]],"ids":[1,1]} -->
<div class="wp-block-jetpack-tiled-gallery aligncenter is-style-rectangular"><div class="tiled-gallery__gallery"><div class="tiled-gallery__row"><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="100" data-id="1" data-url="https://cldup.com/cXyG__fTLN.jpg" data-width="100" src="https://i0.wp.com/cldup.com/cXyG__fTLN.jpg?ssl=1" aria-label="image 1 of 2 in gallery"/></figure></div></div><div class="tiled-gallery__row"><div class="tiled-gallery__col"><figure class="tiled-gallery__item"><img alt="" data-height="100" data-id="1" data-url="https://cldup.com/cXyG__fTLN.jpg" data-width="100" src="https://i0.wp.com/cldup.com/cXyG__fTLN.jpg?ssl=1" aria-label="image 2 of 2 in gallery"/></figure></div></div></div></div>
<!-- /wp:jetpack/tiled-gallery -->
```

Diff: Web on left, mobile on right. Note that the essential structure (row/col divs) are the same, and this is what is breaking on mobile. However, also note the attributes that are different -- aria-label, data-amp-layout, resize on src url, etc. These are what were changed in the workaround.
![image](https://user-images.githubusercontent.com/13263478/139316477-e56c473e-5590-42f5-8671-ba936322832f.png)

**Comment by illusaen** [comment]
Note: 
- PDB = Problem Displaying Block
- JTG = Jetpack Tiled Gallery

**Comment by guarani** [comment]
I've updated the issue to capture our most recent finding which is that this issue affects the block when it has multiple rows in its output HTML.

**Comment by illusaen** [comment]
Resolved with PR https://github.com/Automattic/jetpack/pull/21597
