### ISSUE TITLE
Media & Text block: Excess "failure" notification

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#4247]
**Describe the bug**
On WPAndroid, when trying to upload an image or a video in the Media & Text block while offline, there are 2 different failure notifications going on: one at the bottom and one at the top. See screenshot:

<img width="300px" src="https://user-images.githubusercontent.com/1032913/141989776-ca567fc9-d0f5-47e8-a827-14b6a73ad59c.png"/>

**To Reproduce**
1. With the device in offline mode (no connectivity), open WPAndroid and go edit a post with the block editor
2. Add a Media & Text block
3. tap on the media placeholder and choose to upload an image or video from the device
3. Notice how the app notifies in 3 ways that an error has occurred:
   * Red sliding panel at the top reading "Failed to insert media"
   * Image block placeholder notes: "Failed to insert media..."
   * Snackbar looking panel at the bottom reading: "Media upload failed. The connection to the server was lost".

**Expected behavior**
I'd expect only one of the two ephemeral notifications (at the top and the bottom) to be there.

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - Version WPAndroid version alpha-328

**Comment by mchowning** [comment]
**In addition to the Media&Text block, the Audio block also displays two banner notifications.** Image, Gallery, Video, Cover, and File blocks only display the bottom notification though (they do not show the notification with the red text at the top).

This is only an issue on Android because WPAndroid displays the bottom notification, and Gutenberg displays the top one. WPiOS does not display any notifications here, so on WPiOS the Image, Gallery, Video, Cover, and File blocks do not display any notification of the error apart from the in-block error messaging, and on the Media&Text and Audio blocks WPiOS shows the top banner from Gutenberg.

We already have error messaging within the block itself, and that seems to be sufficient (it's all iOS has for most of the media blocks). So I think the best solution is to remove both of the notification/banner style messages and instead to just rely on the in-block messaging. That has the added benefit of removing the question of which side (main app vs Gutenberg) should display a banner message.

Removing the banner messaging from the bottom on Android feels lower priority to me, so my suggested way to proceed here would be to remove the top-banner message that Gutenberg uses with the Media&Text and Audio blocks ([draft PR](https://github.com/WordPress/gutenberg/pull/39694)). That would leave the bottom banner message on all blocks for WPAndroid and no banner messaging on WPiOS. Do you have any thoughts here @iamthomasbishop ?

If it is straightforward to remove the message on Android as well, we could do that too, but I'm not sure it's worth us spending much time on it now. In other words, I think it's ok for the editor to have the error banner on the bottom in WPAndroid, but not to have that banner on WPiOS.

**Comment by mchowning** [comment]
> my suggested way to proceed here would be to remove the top-banner message that Gutenberg uses with the Media&Text and Audio blocks

@hypest and I talked about this, and decided to proceed with this approach for now. Certainly open to revisiting this if there are other ideas for how to handle this though.

**Comment by iamthomasbishop** [comment]
@mchowning @hypest That should work, thank you!
