### ISSUE TITLE
Verify that the Tiled Gallery works when used in Reusable Blocks

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4286]
The aim here is to verify that the Tiled Gallery works as expected when used inside a reusable block.

**Comment by SiobhyB** [comment]
I tested this by first creating a reusable block on the web that contained the Tiled Gallery block. When attempting to add the reusable block on the app, with the feature branch checked out, I get a `problem displaying block` error:

<img src="https://user-images.githubusercontent.com/2998162/143611130-2c569ca6-89e3-4048-9ffd-b9bb121eca5e.png" width="50%"/>

I also tested creating reusable blocks with the Contact Info and core Gallery blocks. Both of those worked as expected, so this issue seems specific to the Tiled Gallery block.

**Comment by guarani** [comment]
Thanks for checking, @SiobhyB! 

(I'd forgotten to provide an issue description here, so I added that now.)

While this issue was given medium priority, do you think we should create a new issue with the bug you've uncovered and we can prioritize that alongside other issues? That way we can make sure we're working on the most impactful issues.

**Comment by SiobhyB** [comment]
> While this issue was given medium priority, do you think we should create a new issue with the bug you've uncovered and we can prioritize that alongside other issues? That way we can make sure we're working on the most impactful issues.

@guarani, that makes sense! I've gone ahead to create a new issue at https://github.com/wordpress-mobile/gutenberg-mobile/issues/4309.

**Comment by guarani** [comment]
> @guarani, that makes sense! I've gone ahead to create a new issue at #4309.

Thanks @SiobhyB!
