### ISSUE TITLE
The Mosaic layout should respect image aspect ratios

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/gutenberg-mobile#4300]
**Describe the bug**

When previewing the Mosaic layout of the Tiled Gallery block, the site's front-end is showing all images square. Instead, images aspect ratios should be respected (i.e. if an image is rectangular, it should still be rectangular when used in the Mosaic layout).

**To Reproduce**

<details>
<summary>Setup to test from the main apps</summary>
<p>
<ol>
<li>Run the packager from the <code>add/tiled-gallery-block</code> branch: <code>npm run start:reset</code></li>
<li>Run either of the main apps (WPiOS or WPAndroid)</li>
<li>Open a new post in the main apps and expect the editor to load from the running packager</li>
</details>

Then:
1. Add a Tiled Gallery block with a few images that use different aspect ratios
2. Preview the post
3. Notice the images are all squares

**Expected behavior**
Image aspect ratios should be reflected accurately in the Mosaic layout.

**Screenshots**

| Correct (Web) | Incorrect (Mobile) |
| - | - |
| <img width="500" alt="Screen Shot 2021-11-26 at 11 22 13 1" src="https://user-images.githubusercontent.com/1898325/143597363-0e517c7d-f5e3-43fd-9c92-baec3f709f8f.png"> | <img width="500" alt="Screen Shot 2021-11-26 at 11 42 25" src="https://user-images.githubusercontent.com/1898325/143597351-3175ee13-b716-412b-8410-0384c61b7f14.png"> |

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 15
 - Version: Current `add/tiled-gallery-block` branch

**Comment by SiobhyB** [comment]
I originally suspected that this issue was caused by the block contexts added as part of https://github.com/Automattic/jetpack/pull/21166 and https://github.com/Automattic/jetpack/pull/21278. However, following some experimentation, this doesn't actually appear to be the case. 

Instead, I believe this issue is related to how the column widths value is being calculated on mobile. If I save a mosaic gallery that was created on mobile on the web, the column widths are automatically adjusted and the aspect ratio resolves itself.

I therefore think it makes sense to wait until https://github.com/wordpress-mobile/gutenberg-mobile/issues/4303 is worked on and then test this issue again. cc: @guarani

**Comment by guarani** [comment]
Thanks @SiobhyB! I agree it could be related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/4303. I also think https://github.com/wordpress-mobile/gutenberg-mobile/issues/4306 or https://github.com/wordpress-mobile/gutenberg-mobile/issues/4316 might also cause this issue.
