### ISSUE TITLE
Gallery: Cancelling an individual image creates empty placeholder

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/gutenberg-mobile#4317]
**Describe the bug**

After cancelling the upload an individual image in a gallery, an empty placeholder is left behind, both in the editor and on the site's front-end.

**To Reproduce**

1. Add a gallery block and tap "Add Media".
2. Select "Choose from device".
3. Select multiple images from the device and confirm the selection.
4. While the images are uploading, tap on one to view a prompt around cancellation then cancel its upload.
5. Verify that, following the cancellation, there is now an empty image placeholder in the gallery.

**Expected behavior**

After cancelling an individual image, I'd expect it to be removed completely from the gallery, similar to what I'd expect if I removed an individual image.

**Screenshots**

The following video shows the steps to replicate the issue, including a preview of the site's front-end where the empty image placeholder can be viewed:

https://user-images.githubusercontent.com/2998162/144097814-6f4dd1bf-8b89-4c59-a612-e906018ca05b.mov

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.6
 - Version: 18.8

**Comment by mchowning** [comment]
I've looked into this a bit, and I'm wondering if removing the block really is the desired/expected behavior because if you cancel the upload of a normal image block it doesn't remove the block itself. Also, it's not an unexpected scenario to have empty image blocks inside a gallery block since you can add empty image blocks by using the block inserter (as opposed to using the gallery block appended). 

https://user-images.githubusercontent.com/4656348/159050568-d6aa00e5-d7b9-47a3-9c0a-4bd7374dd15f.mp4

My feeling is that this behavior (leaving the empty image block behind after canceling an image upload) may be ok, but wdyt @SiobhyB and @hypest ?

FWIW, in investigating this, I did uncover a bug on Android where all of the empty image blocks in a gallery block can get removed after uploading a new block: https://github.com/WordPress/gutenberg/issues/39588

**Comment by SiobhyB** [comment]
@mchowning, ah, good point about it being possible to add empty image blocks via the block inserter! I don't see a way to add empty image blocks to a gallery on the web, but agree it doesn't really seem to be an issue as long as it's not causing problems with the gallery's functionality.

The main thing that feels off to me is that the empty blocks create an empty space in the gallery when previewing the front-end of the site. I feel like empty image blocks shouldn't impact the gallery's appearance on the front-end. What do you think?

**Comment by mchowning** [comment]
> I don't see a way to add empty image blocks to a gallery on the web

I think you can do that using the inserter similar to mobile.

https://user-images.githubusercontent.com/4656348/159261958-368245b9-52f2-4e95-94ea-94d7c8334a92.mov

> The main thing that feels off to me is that the empty blocks create an empty space in the gallery when previewing the front-end of the site. I feel like empty image blocks shouldn't impact the gallery's appearance on the front-end. What do you think?

👍  That's a really good point, and something I overlooked. I'm seeing the same behavior if I create a gallery on the web with empty blocks, so I don't think it's a mobile-specific issue, but I agree with you that it does seem like an issue.

**Comment by SiobhyB** [comment]
Ah, I see! The steps for adding an empty block within the gallery weren't super clear to me, but I see now. Thanks for the screen recording! I've created an issue for the web at https://github.com/WordPress/gutenberg/issues/39612 and will go ahead to close this one, as you're right it isn't mobile-specific. 🙇‍♀️
