### ISSUE TITLE
[Drag & Drop blocks] Support iPad OS/Trackpad

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/gutenberg-mobile#4783]
## Description

In relation to https://github.com/wordpress-mobile/gutenberg-mobile/pull/4691#issuecomment-1105817538, when using an iPad with a trackpad (the magic keyboard with trackpad and also a standalone trackpad) the dragging is not working. Looks like the long-press gesture is working, as the chip is showing up, but the dragging movement is disabled.

([Video](https://cloudup.com/c0ByjLffPve))

**Comment by geriux** [comment]
I tried using the trackpad, taking into account the current issues focusing on text, and without selecting any text-based block I was able to drag & drop blocks correctly:

https://user-images.githubusercontent.com/4885740/164729435-e0198d9f-89e8-43fc-a7d4-e2e9f0a18625.mov

So let's see once the fix for the issue with [text editing](https://github.com/WordPress/gutenberg/pull/40480) is solved, maybe it will solve this reported issue as well.

**Comment by geriux** [comment]
This issue is [no longer present](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4691#issuecomment-1112692856) so I'll close this.
