### ISSUE TITLE
Display word, character count on overflow menu Action Sheet

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#506]
On Aztec iOS, we recently added _word_ and _character_ counts as a description to the Action Sheet that is shown when pressing on the `•••` menu. I'd prefer to maintain this in the same location for Gutenberg if possible. For reference:

![img_1647 trim 2019-01-25 22_57_23](https://user-images.githubusercontent.com/1200432/51782816-a0006400-20f4-11e9-82c3-4383dee5bd24.gif)

Note: I'm not sure if/how we inherit this type of Aztec improvement in parallel, but I'd like to make sure we maintain them if possible for the sake of user expectations.

**Comment by koke** [comment]
> I'm not sure if/how we inherit this type of Aztec improvement in parallel

From what I can see, "sort of" 😁 The action sheet code actually has the title code there but commented out for Gutenberg, since it's the responsibility of either Gutenberg or Aztec to count the words. Gutenberg already has this functionality since it shows a word count in the TOC, we'd just need to connect the right things.

**Comment by rezzap** [comment]
We have had a few users requesting this or getting confused with it not showing in the same way for both editors. The latest report is in 2755136-zen.
