### ISSUE TITLE
Image block: Image looks cut off or not centered on certain devices

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/gutenberg-mobile#5091]
**Describe the bug**
Initially reported in 5465772-zd-woothemes. The image looks cut off in the app's editor on an iPad. On an iPhone 11, the image wasn't cut off but wasn't centered. We can't reproduce this on iPhone SE.

**To Reproduce**
1. Copy the image from this post: pqyTp-4p8-p2
2. Add the image to an Image block on a test site via the web editor
3. View the image on the app's editor

Note:
* Not sure if this is related, but the theme on the site is Intergalactic 2
* The user reported the issue on a Reusable block, but according to the testing done on iPhone 11, the image on both the Reusable block and Image block looked the same (i.e., not centered in the app's editor).

**Expected behavior**
The image is centered and not cut off in the app's editor.

**Screenshots**

**Screenshot taken on an iPad**

![IMG_7920](https://user-images.githubusercontent.com/40906847/184270625-16bca717-cd93-4431-8357-243b1b625112.jpg)

**Screenshot taken on an iPhone 11**

Top image: Reusable block
Bottom image: Image block

![IMG_6A64509461DF-1](https://user-images.githubusercontent.com/40906847/184270687-fa8f55ca-5ac8-4e8b-9ec0-c40bb425115a.jpeg)

**Screenshot taken on an iPhone SE**

![Image from iOS](https://user-images.githubusercontent.com/40906847/184270759-2945ea9d-737d-4cdb-a6e7-4ec520688519.jpg)

**Smartphone (please complete the following information):**
 - Device: iPad Pro (11-inch), iPhone 11, iPhone SE
 - OS: 15.6
 - WPiOS 20.4

**Comment by fluiddot** [comment]
Thanks for reporting this @reginabally 🙇 !

I might be overlooking a reproduction step but so far, I couldn't manage to reproduce this issue in WPiOS/JPiOS 20.5 and 20.4.

**Steps:**
1. Download [the image](https://newspaceeconomy.files.wordpress.com/2022/07/306826ab-4675-4932-b71b-ee2998fb531e.jpeg) displayed in the referenced post (pqyTp-4p8-p2).
2. Change the site's theme to "Intergalactic 2".
3. Create a new post.
4. Add an Image block.
5. Insert the image from the device.

_Tested on:_
- _iPad (6th Generation) - iOS 14.8.1_ - Jetpack iOS 20.4.0.3
- _iPhone 11 - iOs 15.4.1_ - WordPress iOS 20.5.0.0

iPhone 11|iPad
--|--
<video src=https://user-images.githubusercontent.com/14905380/185118576-e7ca08d7-cf5a-41d4-b5e9-3048f0347ce0.MP4>|<video src=https://user-images.githubusercontent.com/14905380/185118395-407e58ec-ff72-439a-bd6c-8931f1ca6f66.MP4>

<hr>

@reginabally Not sure if you did something different to trigger the issue 🤔 .

**Comment by reginabally** [comment]
Hi @fluiddot, I'm so sorry for leaving out the part that the image has to be added via the web editor! I edited my post for clarity.

I've also invited you to my test site. You can view the image in a draft post titled "Reusable block test". Let me know if that works for you!

**Comment by fluiddot** [comment]
> Hi @fluiddot, I'm so sorry for leaving out the part that the image has to be added via the web editor! I edited my post for clarity.

@reginabally Ah ok, thanks for expanding that part 🙇 , I'll use the web editor for reproducing it 👍 .

> I've also invited you to my test site. You can view the image in a draft post titled "Reusable block test". Let me know if that works for you!

Great! I'll try to reproduce it with my test sites but if I don't manage to reproduce it I'll use yours, thanks!

**Comment by fluiddot** [comment]
I finally manage to reproduce it by using your test site @reginabally. Looks like the issue is related to the Image size and changing the Image dimensions via the Image block settings.

Here are the **reproduction steps** I used:
1. Download [this image](https://newspaceeconomy.files.wordpress.com/2022/07/306826ab-4675-4932-b71b-ee2998fb531e.jpeg).
2. Go to the web version of the editor.
3. Create a post.
4. Add an Image block and insert the image previously downloaded in step 1.
5. Open the Image block settings.
6. Change the Image size to `Full Size`.
7. Change Image dimensions to `25%`.
8. Save the post.
9. Go to the app.
10. Open the saved post.
11. Observe that the image is cut.

**Result:**
<img src=https://user-images.githubusercontent.com/14905380/185449175-4f337bf3-a29c-42f0-8062-1671c247af8d.jpeg width=200>

However, this can't be reproduced consistently with different images. Looks like the size of the image inserted into the block is also involved in the issue 🤔. I'll set the High-priority to the issue as it's related to a top-used block.
