### ISSUE TITLE
When user clicks on the Edit button he should see action sheet with media options

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/gutenberg-mobile#532]
![image](https://user-images.githubusercontent.com/28219092/52111382-e0d00f80-2603-11e9-8147-28d12a3deff4.png)

**Comment by iamthomasbishop** [comment]
How are we going to handle these types of situations on Android? Bottom Sheet? Menu? Dialog? I think my preference would be in that order – Bottom Sheet being most reachable, but Menu or Dialog wouldn't necessarily feel out of place.

**Comment by marecar3** [comment]
Hey @iamthomasbishop , please see how it's implemented
: https://github.com/WordPress/gutenberg/pull/13656

**Comment by iamthomasbishop** [comment]
Ok awesome – a Bottom Sheet :)

Do we have control over which sheet options show per-platform? For example, the actions on Android and iOS are slightly different:

* The Android version (Bottom Sheet) doesn't need a "dismiss" action because it is dismissible by swiping or tapping outside of the Sheet.

* The iOS version will contain an "Other...", which launches the iOS File Picker. AFAIK, this isn't available/necessary on Android.

With that said I'm imagining the options per platform to be something along these lines:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/1200432/52235349-6e706100-2889-11e9-9e33-87f6dd54bfda.png">

**Comment by hypest** [comment]
Just wanted to we should make an effort to lose the menu based approach when we get the chance. It's fine to keep it for ease of implementation for the February Beta but yeah, let's not get too cosy with it :)

We [manged to remove the so call 7-items monstrosity back in 2017](https://github.com/wordpress-mobile/WordPress-Android/pull/5644) on Android and we need to plan some effort to go that route again.

**Comment by marecar3** [comment]
Hey @iamthomasbishop , I have spoken with @SergioEstevao about further changes on Bottom Sheet. If we want to follow your proposal, it would need additional work on iOS side.

We are sharing thoughts that we should stop here for beta as we have other tasks that we should resolve and let's continue after the beta release, WDYT ?

**Comment by SergioEstevao** [comment]
@marecar3 and @iamthomasbishop just to make clear, what I was proposing was to limit the options for Choose From Device, Take Photo and Media Library. The other two while implemented in the main app still need the necessary hooks on the JS side.

**Comment by iamthomasbishop** [comment]
@SergioEstevao @marecar3 Thanks for clarifying. I think it makes sense if we have to limit the options just for the beta, although we should push to enable all of the options as soon as possible. For the sake of clarity, heres's what we're proposing for the beta:

<img width="1009" alt="screen shot 2019-02-05 at 9 47 31 am" src="https://user-images.githubusercontent.com/1200432/52284972-1ab65400-292b-11e9-984a-4385b062273b.png">

Note: I added icons on Android for the sake of mocking them up. We can exclude them for now, unless it's minimal work to add them.

**Comment by marecar3** [comment]
cc: https://github.com/WordPress/gutenberg/pull/13656
