### ISSUE TITLE
Clean up styling of starter paragraph block/placeholder

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/gutenberg-mobile#549]
## Initial "starter" block

This is in reference to the first block that appears when creating a new post – the one that has the label of "Start writing...".

<img width="977" alt="image" src="https://user-images.githubusercontent.com/1200432/52372000-917f4a00-2a1c-11e9-86b6-d9d959ee21d2.png">

#### Punch list

- [ ] Change font-family to Noto Serif (it looks like it is currently the system default sans-serif)
- [ ] Swap in (+) icon if possible – the unicode character feels out of place
- [ ] Make sure placeholder text color is `$gray` aka `#87a6bc`

**Comment by koke** [comment]
I've tried swapping the unicode character with the icon and it works, with some limitations:

- Since it's an inline image, it seems to be ignoring CSS, and I'm not sure if we can apply any styling to it
- The paragraph placeholder uses `RichText.placeholder`, which I doubt will support the attributed strings right away.
