### ISSUE TITLE
Expand usage of BlockListCompact for other blocks that have InnerBlocks

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#5617]
In order to improve consistency across blocks that use InnerBlocks, we would like to add support for using the `BlockListCompact` component for more than just the `List Block`. Currently, the `BlockListCompact` component is only used by the `List Block` and serves as a lighter version of the `BlockList` component. By adding support for other blocks that use InnerBlocks, we can improve the performance by simplifying the component tree being rendered.

The blocks that would benefit from this change include the Group block, Cover block, Columns block, Buttons block, and potentially others. These blocks all have varying degrees of complexity when it comes to their implementation of InnerBlocks, but they all share the need for a lightweight and efficient way to render their child blocks.

In order to make this change, we will need to update the blocks to utilize `BlockListCompact` instead of their existing implementation of InnerBlocks. We will also need to ensure that all necessary props are passed down to `BlockListCompact` so that it can properly render the child blocks. Additionally, we will need to thoroughly test the updated blocks to ensure that they are functioning correctly with this new implementation of InnerBlocks.

**Comment by dcalhoun** [comment]
I drafted https://github.com/WordPress/gutenberg/pull/50107 refactoring Group block to leverage BlockListCompact. It lacks displaying the “insertion point” when inserting a block before or after a selected, nested block (e.g. Paragraph). I’ll explore adding that feature tomorrow. 

Through familiarizing myself with the related code and implementing the changes, I encountered a few preexisting bugs, which I captured: 

* https://github.com/WordPress/gutenberg/issues/50111
* https://github.com/WordPress/gutenberg/issues/50112
* https://github.com/WordPress/gutenberg/issues/50154

**Comment by geriux** [comment]
Thanks for the update! It's nice to see the Tree difference for the Group block already with these new changes 🤩 

Nice catch with the insertion point missing and for creating the issues to track them 👍

**Comment by dcalhoun** [comment]
The more I spend time working on this and becoming familiar with the features of the block list, the more I wonder what an ideal final solution looks like. Is `BlockListCompact` that solution? 

`BlockListCompact` was originally added as — what I perceive to be — a [temporary solution](https://github.com/WordPress/gutenberg/pull/43431) for a performance issue. It added a somewhat duplicative block list component, which will become more duplicative as we copy additional features from `BlockList` to `BlockListCompact` for usage in with block types. 

In contrast, the web editor has taken strides to reduce duplication, even to the point of [_treating all blocks "inner blocks,"_](https://github.com/WordPress/gutenberg/pull/29895) if I understand it correctly. 

Should we refactor so that `BlockList` and `BlockListCompact` can compose shared features? Alternatively, should we instead combine `BlockList` and `BlockListCompact` and use props to toggle the "deep tree" that is incompatible with the native editor for inner blocks?[^1] This subject likely relates to https://github.com/wordpress-mobile/gutenberg-mobile/issues/5616, so there may be scope/code conflicts that arise here. 

[^1]: What, specifically, are the `Views` that create too deep of a tree? The virtual list? Something else? 

@geriux do you have thoughts on this?

**Comment by geriux** [comment]
I didn't think about it but after reading your comment I think it'd make sense to go in that direction of merging both BlockList and BlockListCompact.

> BlockListCompact was originally added as — what I perceive to be — a https://github.com/WordPress/gutenberg/pull/43431 for a performance issue.

That's correct, I'd say it was an experimental approach that turned out to be working and that it improved the performance in general.

> Alternatively, should we instead combine BlockList and BlockListCompact and use props to toggle the "deep tree" that is incompatible with the native editor for inner blocks?

I like this proposal of combining them, the current BlockList code is a bit big but there are quite a few things we should remove that I think that adding the other logic to render a "compact" version wouldn't make the code too complex.

> This subject likely relates to https://github.com/wordpress-mobile/gutenberg-mobile/issues/5616, so there may be scope/code conflicts that arise here.

I don't think it would interfere with that task but maybe I'm missing something 😅 let me know if there's something that could block or relate to code conflicts if we work in parallel refactoring the BlockList/Merging with the BlockListCompact.

This is a great suggestion! 🚀 You have my +1 if you also agree on combining the two components, if not like you said we can also share features between them.

**Comment by dcalhoun** [comment]
Capturing my current plans to [combine `BlockList` and `BlockListCompact`](https://github.com/wordpress-mobile/gutenberg-mobile/issues/5617#issuecomment-1527371446): 

- [x] https://github.com/WordPress/gutenberg/pull/50252
- [x] https://github.com/WordPress/gutenberg/pull/50293
- [ ] ~Move post title to `VisualEditor` to mirror the web editor~ (Not feasible, header needs to be within virtualized scroll view)
- [ ] ~Consolidate block appenders (invisible end-of-list, inner block, empty list)~ (Likely not feasible, they each serve unique contexts now captured [in tests](https://github.com/WordPress/gutenberg/blob/923761a612cc7b76900975fd7d828bc25cb6581c/packages/block-editor/src/components/block-list/test/index.native.js))
- [x] Toggle composition (deep tree) with a new `virtualization` prop https://github.com/WordPress/gutenberg/pull/50447
