### ISSUE TITLE
Add `Replace Image` button to Image Settings bottom-sheet

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/gutenberg-mobile#586]
As shown in the blueprint:

<img width="376" alt="screen shot 2019-02-12 at 3 50 43 pm" src="https://user-images.githubusercontent.com/9772967/52643782-fd125d00-2edd-11e9-8a9f-3c584950a7c4.png">

**Comment by SergioEstevao** [comment]
@iamthomasbishop do we still want to do this now that we have this has an option on the block toolbar?

**Comment by iamthomasbishop** [comment]
@SergioEstevao I'd like to run a narrow usability test on this to understand if the block toolbar button is clear enough — my gut tells me it's not the most obvious icon, and also we have the new(ish) edit icon on the top-right of the image, so we might be able to consolidate actions as well. I will run a quick test and report back later in the week.

**Comment by iamthomasbishop** [comment]
@SergioEstevao I ran a quick usability test using some screenshots from the current version (which now includes a `media-edit` button ([example](https://cloudup.com/c0x51oF1hOk)) on the top-right of the image cell) and the results are pretty clear: 

* The new `media-edit` button outperforms other options by a wide margin (44%)
* In second place is the settings icon (16%)
* Third is the `replace` icon in the block toolbar (8%). I suspect this is low because the block toolbar is tucked along the bottom edge while you have an image block selected, so some probably miss it

My proposal: close this ticket because the `media-edit` button performs well and I'd rather not add another entry point. In terms of the block toolbar button, I'm on the fence because folks familiar with the web editor will expect to see that option — for now, let's leave it as-is. All that to say, let's close this and not change anything. 😄
