### ISSUE TITLE
The Paywall block icon is displayed in an unexpected green color

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/gutenberg-mobile#6099]
### Steps to Reproduce

1. Create a post with a Paywall block: `<!-- wp:jetpack/paywall /-->`
2. Tap and hold the Paywall block in the mobile editor. 

1. Create a post with a nested Paywall block. e.g.:
    ```
    <!-- wp:group {"layout":{"type":"constrained"}} -->
    <div class="wp-block-group"><!-- wp:jetpack/paywall /--></div>
    <!-- /wp:group -->
    ```
2. Select the parent block. 

## Expected Outcome

The icon displayed while dragging or in the floating toolbar is black and white. 

## Actual Outcome

The icon displayed while dragging or in the floating toolbar is Jetpack brand green. 

| Dragging | Toolbar
| - | - |
| <img width="300" alt="Paywall block display incorrect icon color while dragging" src="https://user-images.githubusercontent.com/438664/262467094-7634f1a2-ee24-422d-9916-e9b1e8e5710a.jpeg" /> | <img width="300" src="https://user-images.githubusercontent.com/438664/262473953-bb136ce9-ae9b-401a-adbd-a45077f485c2.png" /> |

**Comment by dcalhoun** [comment]
Much like Contact Info, the Paywall block [relies upon `getIconColor`](https://github.com/Automattic/jetpack/blob/ab0eb7095fd08862c9cdd8db6f74a0f739494c50/projects/plugins/jetpack/extensions/blocks/paywall/index.js#L35C1-L35C1). I'm unsure why Contact Info is working as expected, but the Paywall block is not. Maybe we have native-specific code somewhere modifying the icon or its color?

**Comment by derekblank** [comment]
> Much like Contact Info, the Paywall block [relies upon getIconColor](https://github.com/Automattic/jetpack/blob/ab0eb7095fd08862c9cdd8db6f74a0f739494c50/projects/plugins/jetpack/extensions/blocks/paywall/index.js#L35C1-L35C1). I'm unsure why Contact Info is working as expected, but the Paywall block is not.

The difference between the Paywall icon and the Contact Info icon is that there is no `fill` being set on the Path element itself on the [Contact Info icon](https://github.com/Automattic/jetpack/blob/ab0eb7095fd08862c9cdd8db6f74a0f739494c50/projects/plugins/jetpack/extensions/blocks/contact-info/index.js#L25-L27). On the current Paywall block icon, `getIconColor` is being set on each Path, while the parent SVG element has a property of `fill="none"`. These fills are outside the [settings object](https://github.com/Automattic/jetpack/blob/ab0eb7095fd08862c9cdd8db6f74a0f739494c50/projects/plugins/jetpack/extensions/blocks/paywall/index.js#L35C1-L35C1), and are possibly what is  overriding the logic in [getIconColor](https://github.com/Automattic/jetpack/blob/c57e511b7d740a14ee417908ac8d5d6d2ab6fb96/projects/plugins/jetpack/extensions/shared/block-icons.js#L17-L25) for when the core block styling color should be expected (i.e., not Jetpack green).

In both files, `getIconColor` logs out to `#069e08`, which is Jetpack brand green. So instead of the icon appearing black within the mobile app, it appears Jetpack green because of these explicit fill properties on the Path elements. (Again, referencing that on the [Contact Info icon](https://github.com/Automattic/jetpack/blob/ab0eb7095fd08862c9cdd8db6f74a0f739494c50/projects/plugins/jetpack/extensions/blocks/contact-info/index.js#L25-L27), no fill property is being set.)

My guess as to why these explicit fill properties are being set on the Path elements in the Paywall icon is that `fill="none"` was being set on the Paywall parent SVG element, possibly by accident. Without any explicit fill color set on the child Path elements, the icon would now appear to be invisible. A diverging behavior between web and mobile is that on web, Jetpack blocks are displayed as green in the inserter, while on mobile they are not. This is my hypothesis for why the Jetpack brand green color was set on the icon itself but not noticed until we tested the mobile changes.

#### Validating this within the Inserter
Had we added the Jetpack block to the mobile inserter, we likely would have noticed this sooner. To test this yourself, you can replace the Paywall block icon code with in the Contact Info file:


<details><summary>paywall-icon-in-contact-info.patch diff</summary>

```diff
diff --git a/projects/plugins/jetpack/extensions/blocks/contact-info/index.js b/projects/plugins/jetpack/extensions/blocks/contact-info/index.js
index cd9a2b775f..046bb63da7 100644
--- a/projects/plugins/jetpack/extensions/blocks/contact-info/index.js
+++ b/projects/plugins/jetpack/extensions/blocks/contact-info/index.js
@@ -1,6 +1,6 @@
 import { InnerBlocks } from '@wordpress/block-editor';
 import { createBlock } from '@wordpress/blocks';
-import { Path } from '@wordpress/components';
+import { SVG, Path } from '@wordpress/components';
 import { __, _x } from '@wordpress/i18n';
 import { getIconColor } from '../../shared/block-icons';
 import renderMaterialIcon from '../../shared/render-material-icon';
@@ -23,7 +23,16 @@ const save = ( { className } ) => (
 export const name = 'contact-info';
 
 const icon = renderMaterialIcon(
-	<Path d="M19 5v14H5V5h14m0-2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 9c-1.65 0-3-1.35-3-3s1.35-3 3-3 3 1.35 3 3-1.35 3-3 3zm0-4c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1zm6 10H6v-1.53c0-2.5 3.97-3.58 6-3.58s6 1.08 6 3.58V18zm-9.69-2h7.38c-.69-.56-2.38-1.12-3.69-1.12s-3.01.56-3.69 1.12z" />
+	<SVG width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
+		<Path d="M4 16.7134L20 16.7134V15.106H4V16.7134Z" fill={ getIconColor() } />
+		<Path d="M16 21H20V19.3925H16V21Z" fill={ getIconColor() } />
+		<Path d="M14 21H10V19.3925H14V21Z" fill={ getIconColor() } />
+		<Path d="M4 21H8V19.3925H4V21Z" fill={ getIconColor() } />
+		<Path
+			d="M11.471 6.37162C11.2294 6.55286 11.1538 6.74395 11.1538 6.88519C11.1538 7.02644 11.2294 7.21752 11.471 7.39877C11.7108 7.57865 12.0728 7.70953 12.5 7.70953C13.1349 7.70953 13.7344 7.90158 14.1907 8.24382C14.6451 8.5847 15 9.11491 15 9.77039C15 10.4259 14.6451 10.9561 14.1907 11.297C13.8758 11.5331 13.4928 11.6978 13.0769 11.7771V12.0373C13.0769 12.3788 12.8186 12.6556 12.5 12.6556C12.1814 12.6556 11.9231 12.3788 11.9231 12.0373V11.7771C11.5072 11.6978 11.1242 11.5331 10.8093 11.297C10.3549 10.9561 10 10.4259 10 9.77039C10 9.42893 10.2583 9.15213 10.5769 9.15213C10.8955 9.15213 11.1538 9.42893 11.1538 9.77039C11.1538 9.91163 11.2294 10.1027 11.471 10.284C11.7108 10.4638 12.0728 10.5947 12.5 10.5947C12.9272 10.5947 13.2892 10.4638 13.529 10.284C13.7706 10.1027 13.8462 9.91163 13.8462 9.77039C13.8462 9.62914 13.7706 9.43806 13.529 9.25681C13.2892 9.07693 12.9272 8.94605 12.5 8.94605C11.8651 8.94605 11.2656 8.754 10.8093 8.41176C10.3549 8.07089 10 7.54067 10 6.88519C10 6.22971 10.3549 5.6995 10.8093 5.35863C11.1242 5.12246 11.5072 4.95781 11.9231 4.87844V4.61826C11.9231 4.2768 12.1814 4 12.5 4C12.8186 4 13.0769 4.2768 13.0769 4.61826V4.87844C13.4928 4.95781 13.8758 5.12246 14.1907 5.35863C14.6451 5.6995 15 6.22971 15 6.88519C15 7.22665 14.7417 7.50345 14.4231 7.50345C14.1045 7.50345 13.8462 7.22665 13.8462 6.88519C13.8462 6.74395 13.7706 6.55286 13.529 6.37162C13.2892 6.19174 12.9272 6.06085 12.5 6.06085C12.0728 6.06085 11.7108 6.19174 11.471 6.37162Z"
+			fill={ getIconColor() }
+		/>
+	</SVG>
 );
 
 export const settings = {
```
</details>

The Paywall block icon will appear green in the Inserter (and the Editor), taking the place of the former Contact Info block icon for more sterile testing purposes:

<table>
<tr>
<td>
<img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/a3c3f308-4ff5-49cc-afd4-1317fa5ee7e5" />
</td>
<td>
<img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/7add8721-3098-4384-94b6-8b33c1849bf8" />
</td>
</tr>
</table>

With the applied changes from https://github.com/Automattic/jetpack/pull/32638 to remove the fills from the Paywall icon SVG code, the Paywall icon now displays as the correct color. 

<details><summary>paywall-icon-in-contact-info-fill-removed.patch diff</summary>

```diff
diff --git a/projects/plugins/jetpack/extensions/blocks/contact-info/index.js b/projects/plugins/jetpack/extensions/blocks/contact-info/index.js
index cd9a2b775f..2ba7a02832 100644
--- a/projects/plugins/jetpack/extensions/blocks/contact-info/index.js
+++ b/projects/plugins/jetpack/extensions/blocks/contact-info/index.js
@@ -1,6 +1,6 @@
 import { InnerBlocks } from '@wordpress/block-editor';
 import { createBlock } from '@wordpress/blocks';
-import { Path } from '@wordpress/components';
+import { SVG, Path } from '@wordpress/components';
 import { __, _x } from '@wordpress/i18n';
 import { getIconColor } from '../../shared/block-icons';
 import renderMaterialIcon from '../../shared/render-material-icon';
@@ -23,7 +23,15 @@ const save = ( { className } ) => (
 export const name = 'contact-info';
 
 const icon = renderMaterialIcon(
-	<Path d="M19 5v14H5V5h14m0-2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7 9c-1.65 0-3-1.35-3-3s1.35-3 3-3 3 1.35 3 3-1.35 3-3 3zm0-4c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1zm6 10H6v-1.53c0-2.5 3.97-3.58 6-3.58s6 1.08 6 3.58V18zm-9.69-2h7.38c-.69-.56-2.38-1.12-3.69-1.12s-3.01.56-3.69 1.12z" />
+	<SVG width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
+		<Path d="M4 16.7134L20 16.7134V15.106H4V16.7134Z" />
+		<Path d="M16 21H20V19.3925H16V21Z" />
+		<Path d="M14 21H10V19.3925H14V21Z" />
+		<Path d="M4 21H8V19.3925H4V21Z" />
+		<Path
+			d="M11.471 6.37162C11.2294 6.55286 11.1538 6.74395 11.1538 6.88519C11.1538 7.02644 11.2294 7.21752 11.471 7.39877C11.7108 7.57865 12.0728 7.70953 12.5 7.70953C13.1349 7.70953 13.7344 7.90158 14.1907 8.24382C14.6451 8.5847 15 9.11491 15 9.77039C15 10.4259 14.6451 10.9561 14.1907 11.297C13.8758 11.5331 13.4928 11.6978 13.0769 11.7771V12.0373C13.0769 12.3788 12.8186 12.6556 12.5 12.6556C12.1814 12.6556 11.9231 12.3788 11.9231 12.0373V11.7771C11.5072 11.6978 11.1242 11.5331 10.8093 11.297C10.3549 10.9561 10 10.4259 10 9.77039C10 9.42893 10.2583 9.15213 10.5769 9.15213C10.8955 9.15213 11.1538 9.42893 11.1538 9.77039C11.1538 9.91163 11.2294 10.1027 11.471 10.284C11.7108 10.4638 12.0728 10.5947 12.5 10.5947C12.9272 10.5947 13.2892 10.4638 13.529 10.284C13.7706 10.1027 13.8462 9.91163 13.8462 9.77039C13.8462 9.62914 13.7706 9.43806 13.529 9.25681C13.2892 9.07693 12.9272 8.94605 12.5 8.94605C11.8651 8.94605 11.2656 8.754 10.8093 8.41176C10.3549 8.07089 10 7.54067 10 6.88519C10 6.22971 10.3549 5.6995 10.8093 5.35863C11.1242 5.12246 11.5072 4.95781 11.9231 4.87844V4.61826C11.9231 4.2768 12.1814 4 12.5 4C12.8186 4 13.0769 4.2768 13.0769 4.61826V4.87844C13.4928 4.95781 13.8758 5.12246 14.1907 5.35863C14.6451 5.6995 15 6.22971 15 6.88519C15 7.22665 14.7417 7.50345 14.4231 7.50345C14.1045 7.50345 13.8462 7.22665 13.8462 6.88519C13.8462 6.74395 13.7706 6.55286 13.529 6.37162C13.2892 6.19174 12.9272 6.06085 12.5 6.06085C12.0728 6.06085 11.7108 6.19174 11.471 6.37162Z"
+		/>
+	</SVG>
 );
 
 export const settings = {
```
</details>

<table>
<tr>
<td>
<img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/6388aa43-86b6-4a1b-8272-27840da9846e" />
</td>
<td>
<img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/623e3602-dba2-4a8a-ba8c-54c2bb4a89de" />
</td>
</tr>
</table>

**Comment by dcalhoun** [comment]
I pulled the latest from `trunk` into our feature branch, so this is now resolved. Thank you!
