### ISSUE TITLE
Missing characters in the action button for the MediaPlaceholder component

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/gutenberg-mobile#6168]
**Describe the bug**
Currently, there's a bug where some characters are missing when using a different language like Spanish.

**To Reproduce**
1. Add a media block
2. The action button text has missing characters

**Expected behavior**
The action button should show the right translations

**Screenshots**
<kbd><img src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/4885740/68b3cea6-e0e3-46d8-a908-1fb5300d92eb" width=240 /></kbd>

**Smartphone (please complete the following information):**
 - Device: iPhone/Android
 - OS: 16.4/13
 - Version 22.1, 22.2

**Additional context**
This is a regression from the recent UX design changes, where `sentenceCase` was added from the `change-case` library which doesn't support localization. The solution would be to remove its usage and just change the original strings.

**Comment by fluiddot** [comment]
I saw that there are [several issues reported in the `change-case` repository](https://github.com/blakeembrey/change-case/issues) related to this. As you pointed out @geriux, as a workaround we could simply remove the library and use the original string 👍 .

**Comment by derekblank** [comment]
I wonder if this issue is possibly related as well -- my main testing device is set to `en-AU` locale, but I noted that the color picker displays both `en-US` and `en-AU` spellings of the word color/colour:

* https://github.com/wordpress-mobile/gutenberg-mobile/issues/5838

_Edit:_  The color/colour issue does not seem related to `sentenceCase` as it's not used in the ColorPicker, so there's likely another cause for the locales being mixed.

**Comment by derekblank** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/54281.
