### ISSUE TITLE
Introduce a “Retry all” option in the bottom sheet displayed upon upload failure

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/gutenberg-mobile#6408]
Ideally, uploads should automatically restart when reestablishing a connection. Providing an explicit option within the ActionSheet to retry all failed uploads can be valuable, especially when adding Gallery blocks.

**NOTE**: This change would primarily affect the iOS version, as the Android version already restarts all uploads when tapping on the “Retry” button.

![Image](https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/6f6b6597-3d26-4d5e-95db-17de52af767a)

**Comment by dcalhoun** [comment]
The [original design feedback](https://github.com/wordpress-mobile/WordPress-Android/pull/12672#issuecomment-679934085) on the Android implementation was that having both a "Retry" and "Retry all" button is confusing and that we should retry _all_ uploads when a user clicks the "Retry" button. Because of this, I plan to update iOS to mirror the current Android behavior, rather than add a "Retry all" button.
