### ISSUE TITLE
UI for invalid blocks

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/gutenberg-mobile#969]
Show a UI similar to the unsupported block if a block fails validation

For reference, this is what the web displays:

<img width="388" alt="screen-shot-2019-05-11-at-15 30 58" src="https://user-images.githubusercontent.com/8739/57788975-546fd580-7738-11e9-858b-1ccefcfc4d61.png">

For 2.0, we just want to show a non-actionable message.

**Comment by dmsnell** [comment]
Note that there are outstanding issues with this block and the screenshot may be affected by it (I'm noting the lack of the static fallback HTML render).

I'm working slowly on trying to make this whole thing better in WordPress/gutenberg#15078 and in WordPress/gutenberg#15674 so if you have ideas I'd be happy to collaborate.

**Comment by iamthomasbishop** [comment]
In terms of an error state, I agree we re-use the same style as the unsupported state. 

I'm not 100% sure about the messaging here, but the messaging in the example above doesn't read as "approachable", so if this is a someone "generic" error message I'd just as soon simplify it and _if the user taps it_, show more detailed error information in a dialog or some other element.

Here's a few options for how we could display this using the default placeholder style – assuming (for now) we don't need to show resolution/action buttons:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/1200432/57880555-a837f880-77e4-11e9-96a8-85a86f67bc40.png">


My preference would be Option 2 (top-right) or Option 1 (top-left), because they are the most visually balanced.

// cc @koke

**Comment by dmsnell** [comment]
While it doesn't show too well in the original screenshots the purpose of the message is to wrap the fallback static render so that the editor can get an approximate idea of what the block is supposed to do. By covering it with a graphic we remove that ability to quickly assess what's happening.

If the VideoPress block is just showing a URL then it's more complicated because the underlying fallback render isn't that great, but we can also update that block to give a better fallback.

**Comment by koke** [comment]
> the purpose of the message is to wrap the fallback static render so that the editor can get an approximate idea of what the block is supposed to do

That is a clever UI, but that works well on the web because you can just take the HTML and render it in place. To do a similar thing we would have to deal with embedding a web view, which we haven't done yet, opening the door to a number of new problems to solve.

**Comment by etoledom** [comment]
@iamthomasbishop - This is an early version of how it looks so far:

![IMG_1852](https://user-images.githubusercontent.com/9772967/58199205-438f0900-7cd0-11e9-8516-c9d51b0d1a76.png)

Note that I added the invalid content warning in between an Unsupported block (Quote) and an Image block on empty state, so you can see how do they look and compare with each other.

Could you please share the design details?
